package com.justeam.rdp.governance;

import com.justeam.rdp.audit.AuditService;
import com.justeam.rdp.common.BusinessException;
import com.justeam.rdp.security.CurrentUser;
import com.justeam.rdp.security.TokenService;
import com.justeam.rdp.security.UserPrincipal;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.Array;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

@Service
public class GovernanceService {
    private static final Set<String> CATEGORY_TYPES=Set.of("SCIENTIFIC","INDUSTRY");
    private static final Set<String> RESOURCE_TYPES=Set.of("menu","button","api");
    private final JdbcClient jdbc;private final AuditService audit;private final TokenService tokens;
    public GovernanceService(JdbcClient jdbc,AuditService audit,TokenService tokens){this.jdbc=jdbc;this.audit=audit;this.tokens=tokens;}

    public Map<String,Object> overview(){Map<String,Object> result=new LinkedHashMap<>();result.put("categories",categories(null));result.put("categoryMappings",categoryMappings());result.put("tags",tags());result.put("dictionaries",dictionaries());result.put("dictionaryItems",dictionaryItems(null));result.put("menus",menus());result.put("uiConfig",uiConfig());return result;}
    public Map<String,Object> businessOptions(){Map<String,Object> result=new LinkedHashMap<>();result.put("categories",categories(null).stream().filter(v->number(v,"status")==1).toList());result.put("categoryMappings",categoryMappings());result.put("tags",tags().stream().filter(v->number(v,"status")==1).toList());List<Map<String,Object>> enabledDictionaries=dictionaries().stream().filter(v->number(v,"status")==1).toList();Set<Long> enabledDictionaryIds=enabledDictionaries.stream().map(v->number(v,"id")).collect(java.util.stream.Collectors.toSet());result.put("dictionaries",enabledDictionaries);result.put("dictionaryItems",dictionaryItems(null).stream().filter(v->number(v,"status")==1&&enabledDictionaryIds.contains(number(v,"dictionaryId"))).toList());return result;}
    public List<Map<String,Object>> navigation(){UserPrincipal user=CurrentUser.require();List<Map<String,Object>> all=jdbc.sql("SELECT * FROM sys_menu WHERE deleted=0 ORDER BY sort_order,id").query(this::menuRow).list();Map<Long,Map<String,Object>> byId=all.stream().collect(java.util.stream.Collectors.toMap(v->number(v,"id"),v->v));return all.stream().filter(menu->number(menu,"status")==1&&menuAncestorsEnabled(menu,byId,new java.util.HashSet<>())).filter(menu->{String permission=(String)menu.get("permissionCode");return permission==null||permission.isBlank()||user.admin()||Arrays.stream(permission.split("\\|")).anyMatch(user.permissions()::contains);}).toList();}

    public List<Map<String,Object>> departments(){return jdbc.sql("""
            SELECT d.*,coalesce(u.real_name,'') leader_name,
                   (SELECT count(*) FROM sys_user x WHERE x.department_id=d.id AND x.deleted=0) user_count,
                   (SELECT count(*) FROM sys_department c WHERE c.parent_id=d.id AND c.deleted=0) child_count
            FROM sys_department d LEFT JOIN sys_user u ON u.id=d.leader_id WHERE d.deleted=0 ORDER BY d.dept_path,d.sort_order,d.id
            """).query(this::departmentRow).list();}
    public List<Map<String,Object>> departmentLeaders(){return jdbc.sql("SELECT id,username,real_name FROM sys_user WHERE status=1 AND deleted=0 ORDER BY real_name,username LIMIT 1000").query((rs,n)->Map.<String,Object>of("id",rs.getLong("id"),"username",rs.getString("username"),"name",rs.getString("real_name"))).list();}
    @Transactional public long createDepartment(String name,String code,Long parentId,Long leaderId,int sortOrder,int status){treeLock(4101);long id=jdbc.sql("INSERT INTO sys_department(dept_name,dept_code,parent_id,leader_id,sort_order,status,dept_path) VALUES (:name,:code,:parent,:leader,:sort,:status,'') RETURNING id").param("name",required(name,"部门名称")).param("code",code(code)).param("parent",validDepartmentParent(parentId,null)).param("leader",validUser(leaderId)).param("sort",sortOrder).param("status",flag(status)).query(Long.class).single();String path=departmentPath(parentId)+"/"+id;jdbc.sql("UPDATE sys_department SET dept_path=:path WHERE id=:id").param("path",path).param("id",id).update();audit.record("CREATE","DEPARTMENT","创建部门",Map.of("departmentId",id,"name",name,"code",code,"parentId",parentId==null?0:parentId));return id;}
    @Transactional public void updateDepartment(long id,String name,String code,Long parentId,Long leaderId,int sortOrder,int status){treeLock(4101);referenceLockExclusive(4203);Map<String,Object> before=department(id,true);Long actualParent=validDepartmentParent(parentId,id);String oldPath=(String)before.get("path"),newPath=departmentPath(actualParent)+"/"+id;if(actualParent!=null&&newPath.startsWith(oldPath+"/"))throw BusinessException.badRequest("不能把部门移动到其子部门下");jdbc.sql("UPDATE sys_department SET dept_name=:name,dept_code=:code,parent_id=:parent,leader_id=:leader,sort_order=:sort,status=:status,updated_time=now() WHERE id=:id AND deleted=0").param("name",required(name,"部门名称")).param("code",code(code)).param("parent",actualParent).param("leader",validUser(leaderId)).param("sort",sortOrder).param("status",flag(status)).param("id",id).update();jdbc.sql("UPDATE sys_department SET dept_path=:newPath||substring(dept_path FROM :start),updated_time=now() WHERE deleted=0 AND (dept_path=:oldPath OR dept_path LIKE :prefix)").param("newPath",newPath).param("start",oldPath.length()+1).param("oldPath",oldPath).param("prefix",oldPath+"/%").update();Map<String,Object> after=department(id,true);audit.record("UPDATE","DEPARTMENT","修改部门",Map.of("departmentId",id,"before",before,"after",after));}
    @Transactional public void deleteDepartment(long id,String reason){treeLock(4101);referenceLockExclusive(4203);Map<String,Object> before=department(id,true);long shares=jdbc.sql("SELECT count(*) FROM sys_share_rule WHERE grantee_type='DEPARTMENT' AND grantee_id=:id").param("id",id).query(Long.class).single();long dependencies=number(before,"userCount")+number(before,"childCount")+shares;if(dependencies>0)throw new BusinessException(409,"部门仍有关联用户、子部门或共享规则，不能删除");jdbc.sql("UPDATE sys_department SET deleted=1,status=0,updated_time=now() WHERE id=:id").param("id",id).update();audit.record("DELETE","DEPARTMENT","删除空部门",Map.of("departmentId",id,"before",before,"reason",required(reason,"删除原因")));}

    public List<Map<String,Object>> permissions(){return jdbc.sql("SELECT * FROM sys_permission WHERE deleted=0 ORDER BY sort_order,id").query(this::permissionRow).list();}
    public List<Map<String,Object>> roles(){return jdbc.sql("""
            SELECT r.*,(SELECT count(*) FROM sys_user_role ur WHERE ur.role_id=r.id) user_count,
                   ARRAY(SELECT permission_id FROM sys_role_permission rp WHERE rp.role_id=r.id ORDER BY permission_id) permission_ids
            FROM sys_role r WHERE r.deleted=0 ORDER BY r.sort_order,r.id
            """).query(this::roleRow).list();}
    @Transactional public long createRole(String name,String code,String description,int sortOrder,int status,List<Long> permissionIds){List<Long> normalizedPermissions=ids(permissionIds);validateDelegablePermissions(normalizedPermissions);long id=jdbc.sql("INSERT INTO sys_role(role_name,role_code,description,sort_order,status) VALUES (:name,:code,:description,:sort,:status) RETURNING id").param("name",required(name,"角色名称")).param("code",code(code)).param("description",trim(description)).param("sort",sortOrder).param("status",flag(status)).query(Long.class).single();replaceRolePermissions(id,normalizedPermissions);audit.record("CREATE","ROLE","创建角色并分配权限",Map.of("roleId",id,"name",name,"code",code,"permissionIds",normalizedPermissions));return id;}
    @Transactional public void updateRole(long id,String name,String description,int sortOrder,int status,List<Long> permissionIds,int expectedVersion){referenceLockExclusive(4204);Map<String,Object> before=role(id,true);List<Long> normalizedPermissions=ids(permissionIds);if("ADMIN".equals(before.get("code"))){if(status==0)throw BusinessException.badRequest("系统管理员角色不能停用");long required=jdbc.sql("SELECT count(*) FROM sys_permission WHERE status=1 AND deleted=0").query(Long.class).single();if(normalizedPermissions.size()!=required)throw BusinessException.badRequest("系统管理员角色必须保留全部启用权限");}validateDelegablePermissions(normalizedPermissions);List<Long> affected=roleUsers(id);int updated=jdbc.sql("UPDATE sys_role SET role_name=:name,description=:description,sort_order=:sort,status=:status,version=version+1,updated_time=now() WHERE id=:id AND version=:version AND deleted=0").param("name",required(name,"角色名称")).param("description",trim(description)).param("sort",sortOrder).param("status",flag(status)).param("id",id).param("version",expectedVersion).update();if(updated==0)throw new BusinessException(409,"角色版本已变化，请刷新后重试");replaceRolePermissions(id,normalizedPermissions);affected.forEach(tokens::revoke);audit.record("UPDATE","ROLE","修改角色与权限并撤销受影响会话",Map.of("roleId",id,"before",before,"after",role(id,true),"revokedUsers",affected));}
    @Transactional public void deleteRole(long id,String reason){referenceLockExclusive(4204);Map<String,Object> before=role(id,true);if("ADMIN".equals(before.get("code")))throw BusinessException.badRequest("系统管理员角色不能删除");long shares=jdbc.sql("SELECT count(*) FROM sys_share_rule WHERE grantee_type='ROLE' AND grantee_id=:id").param("id",id).query(Long.class).single();if(number(before,"userCount")+shares>0)throw new BusinessException(409,"角色仍关联用户或共享规则，不能删除");jdbc.sql("DELETE FROM sys_role_permission WHERE role_id=:id").param("id",id).update();jdbc.sql("UPDATE sys_role SET deleted=1,status=0,updated_time=now() WHERE id=:id").param("id",id).update();audit.record("DELETE","ROLE","删除未使用角色",Map.of("roleId",id,"before",before,"reason",required(reason,"删除原因")));}

    public List<Map<String,Object>> dataScopes(){return jdbc.sql("""
            SELECT s.*,
             (SELECT count(*) FROM sys_user_data_scope u WHERE u.data_scope_id=s.id) user_count,
             ((SELECT count(*) FROM tpl_template t WHERE t.data_scope_id=s.id AND t.deleted=0)+
              (SELECT count(*) FROM data_dataset d WHERE d.data_scope_id=s.id AND d.deleted=0)+
              (SELECT count(*) FROM trace_entity e WHERE e.data_scope_id=s.id AND e.deleted=0)+
              (SELECT count(*) FROM device v WHERE v.data_scope_id=s.id)+
              (SELECT count(*) FROM file_asset f WHERE f.data_scope_id=s.id AND f.status<>'DELETED')+
              (SELECT count(*) FROM lifecycle_retention_policy p WHERE p.data_scope_id=s.id)+
              (SELECT count(*) FROM tpl_template_version tv WHERE tv.data_scope_id=s.id)+
              (SELECT count(*) FROM lifecycle_archive_item ai WHERE ai.data_scope_id=s.id AND ai.state<>'SUPERSEDED')+
              (SELECT count(*) FROM sys_share_rule r WHERE r.resource_type='DATA_SCOPE' AND r.resource_id=s.id)) resource_count
            FROM sys_data_scope s WHERE s.deleted=0 ORDER BY s.id
            """).query(this::scopeRow).list();}
    @Transactional public long createDataScope(String name,String code,String type,String description,boolean active){String normalizedType=scopeType(type);long id=jdbc.sql("INSERT INTO sys_data_scope(scope_name,scope_code,scope_type,description,active) VALUES (:name,:code,:type,:description,:active) RETURNING id").param("name",required(name,"数据域名称")).param("code",code(code)).param("type",normalizedType).param("description",trim(description)).param("active",active).query(Long.class).single();audit.record("CREATE","DATA_SCOPE","创建数据域",Map.of("dataScopeId",id,"name",name,"code",code,"type",normalizedType,"active",active));return id;}
    @Transactional public void updateDataScope(long id,String name,String type,String description,boolean active,int expectedVersion){referenceLockExclusive(4205);Map<String,Object> before=dataScope(id);if("GLOBAL".equals(before.get("code"))&&!active)throw BusinessException.badRequest("全局数据域不能停用");int updated=jdbc.sql("UPDATE sys_data_scope SET scope_name=:name,scope_type=:type,description=:description,active=:active,version=version+1,updated_by=:actor,updated_time=now() WHERE id=:id AND version=:version AND deleted=0").param("name",required(name,"数据域名称")).param("type",scopeType(type)).param("description",trim(description)).param("active",active).param("actor",actor()).param("id",id).param("version",expectedVersion).update();if(updated==0)throw new BusinessException(409,"数据域版本已变化，请刷新后重试");audit.record("UPDATE","DATA_SCOPE","修改数据域",Map.of("dataScopeId",id,"before",before,"after",dataScope(id)));}
    @Transactional public void deleteDataScope(long id,String reason,int expectedVersion){referenceLockExclusive(4205);Map<String,Object> before=dataScope(id);if("GLOBAL".equals(before.get("code")))throw BusinessException.badRequest("全局数据域不能删除");if(number(before,"userCount")+number(before,"resourceCount")>0)throw new BusinessException(409,"数据域仍关联用户或业务资源，只能停用，不能删除");int updated=jdbc.sql("UPDATE sys_data_scope SET deleted=1,active=FALSE,version=version+1,updated_by=:actor,updated_time=now() WHERE id=:id AND version=:version AND deleted=0").param("actor",actor()).param("id",id).param("version",expectedVersion).update();if(updated==0)throw new BusinessException(409,"数据域版本已变化，请刷新后重试");audit.record("DELETE","DATA_SCOPE","删除未使用数据域",Map.of("dataScopeId",id,"before",before,"reason",required(reason,"删除原因")));}

    public List<Map<String,Object>> categories(String rawType){String type=rawType==null?null:categoryType(rawType);return jdbc.sql("""
            SELECT c.*,(SELECT count(*) FROM gov_category x WHERE x.parent_id=c.id AND x.deleted=0) child_count,
                   (SELECT count(*) FROM data_dataset d WHERE d.deleted=0 AND (d.scientific_category_id=c.id OR d.industry_category_id=c.id)) dataset_count
            FROM gov_category c WHERE c.deleted=0 AND (CAST(:type AS text) IS NULL OR c.category_type=CAST(:type AS text)) ORDER BY c.category_type,c.sort_order,c.id
            """).param("type",type).query(this::categoryRow).list();}
    @Transactional public long createCategory(String type,String name,String code,Long parentId,List<String> productCodes,int sortOrder,int status){treeLock(4102);String normalized=categoryType(type);Long parent=validCategoryParent(parentId,normalized,null);long id=jdbc.sql("INSERT INTO gov_category(category_type,category_name,category_code,parent_id,product_codes,sort_order,status,created_by) VALUES (:type,:name,:code,:parent,:products,:sort,:status,:actor) RETURNING id").param("type",normalized).param("name",required(name,"分类名称")).param("code",code(code)).param("parent",parent).param("products",strings(productCodes)).param("sort",sortOrder).param("status",flag(status)).param("actor",actor()).query(Long.class).single();audit.record("CREATE","CATEGORY","创建分类节点",Map.of("categoryId",id,"type",normalized,"name",name,"code",code));return id;}
    @Transactional public void updateCategory(long id,String name,String code,Long parentId,List<String> productCodes,int sortOrder,int status){treeLock(4102);referenceLockExclusive(4201);Map<String,Object> before=category(id,true);String type=(String)before.get("type");Long parent=validCategoryParent(parentId,type,id);ensureCategoryNotDescendant(id,parent);jdbc.sql("UPDATE gov_category SET category_name=:name,category_code=:code,parent_id=:parent,product_codes=:products,sort_order=:sort,status=:status,updated_by=:actor,updated_time=now() WHERE id=:id AND deleted=0").param("name",required(name,"分类名称")).param("code",code(code)).param("parent",parent).param("products",strings(productCodes)).param("sort",sortOrder).param("status",flag(status)).param("actor",actor()).param("id",id).update();audit.record("UPDATE","CATEGORY","修改分类节点",Map.of("categoryId",id,"before",before,"after",category(id,true)));}
    @Transactional public void deleteCategory(long id,String reason){treeLock(4102);referenceLockExclusive(4201);Map<String,Object> before=category(id,true);long mappings=jdbc.sql("SELECT count(*) FROM gov_category_mapping WHERE scientific_category_id=:id OR industry_category_id=:id").param("id",id).query(Long.class).single();if(number(before,"childCount")+number(before,"datasetCount")+mappings>0)throw new BusinessException(409,"分类存在子节点、映射或关联数据，不能删除");jdbc.sql("UPDATE gov_category SET deleted=1,status=0,updated_by=:actor,updated_time=now() WHERE id=:id").param("actor",actor()).param("id",id).update();audit.record("DELETE","CATEGORY","删除未使用分类",Map.of("categoryId",id,"before",before,"reason",required(reason,"删除原因")));}
    public List<Map<String,Object>> categoryMappings(){return jdbc.sql("SELECT scientific_category_id,industry_category_id,created_time FROM gov_category_mapping ORDER BY scientific_category_id,industry_category_id").query((rs,n)->Map.<String,Object>of("scientificCategoryId",rs.getLong(1),"industryCategoryId",rs.getLong(2),"createdTime",rs.getObject(3))).list();}
    @Transactional public void replaceCategoryMappings(long scientificId,List<Long> industryIds){treeLock(4102);referenceLockShared(4201);categoryOfType(scientificId,"SCIENTIFIC");List<Long> normalized=ids(industryIds);normalized.forEach(id->categoryOfType(id,"INDUSTRY"));List<Long> before=jdbc.sql("SELECT industry_category_id FROM gov_category_mapping WHERE scientific_category_id=:id ORDER BY industry_category_id").param("id",scientificId).query(Long.class).list();jdbc.sql("DELETE FROM gov_category_mapping WHERE scientific_category_id=:id").param("id",scientificId).update();for(Long id:normalized)jdbc.sql("INSERT INTO gov_category_mapping(scientific_category_id,industry_category_id,created_by) VALUES (:scientific,:industry,:actor)").param("scientific",scientificId).param("industry",id).param("actor",actor()).update();audit.record("UPDATE","CATEGORY_MAPPING","修改科学与产业分类映射",Map.of("scientificCategoryId",scientificId,"before",before,"after",normalized));}

    public List<Map<String,Object>> tags(){return jdbc.sql("""
            SELECT t.*,
             ((SELECT count(*) FROM data_dataset_tag dt JOIN data_dataset d ON d.id=dt.dataset_id AND d.deleted=0 WHERE dt.tag_id=t.id)+
              (SELECT count(*) FROM tpl_template_tag tt JOIN tpl_template x ON x.id=tt.template_id AND x.deleted=0 WHERE tt.tag_id=t.id)) usage_count
            FROM gov_tag t WHERE t.deleted=0 ORDER BY t.tag_group,t.tag_name,t.id
            """).query(this::tagRow).list();}
    @Transactional public long createTag(String name,String color,String group,int status){String normalized=required(name,"标签名称").toLowerCase(Locale.ROOT);long id=jdbc.sql("INSERT INTO gov_tag(tag_name,tag_color,tag_group,status,created_by) VALUES (:name,:color,:group,:status,:actor) RETURNING id").param("name",normalized).param("color",color(color)).param("group",required(group,"标签分组")).param("status",flag(status)).param("actor",actor()).query(Long.class).single();audit.record("CREATE","TAG","创建数据标签",Map.of("tagId",id,"name",normalized,"color",color,"group",group));return id;}
    @Transactional public void updateTag(long id,String name,String color,String group,int status){referenceLockExclusive(4202);Map<String,Object> before=tag(id,true);String normalized=required(name,"标签名称").toLowerCase(Locale.ROOT);if(!normalized.equals(String.valueOf(before.get("name")).toLowerCase(Locale.ROOT))&&number(before,"usageCount")>0)throw new BusinessException(409,"标签正在被模板或数据集使用，不能重命名");jdbc.sql("UPDATE gov_tag SET tag_name=:name,tag_color=:color,tag_group=:group,status=:status,updated_by=:actor,updated_time=now() WHERE id=:id AND deleted=0").param("name",normalized).param("color",color(color)).param("group",required(group,"标签分组")).param("status",flag(status)).param("actor",actor()).param("id",id).update();audit.record("UPDATE","TAG","修改数据标签",Map.of("tagId",id,"before",before,"after",tag(id,true)));}
    @Transactional public void deleteTag(long id,String reason){referenceLockExclusive(4202);Map<String,Object> before=tag(id,true);if(number(before,"usageCount")>0)throw new BusinessException(409,"标签仍被模板或数据集使用，不能删除");jdbc.sql("UPDATE gov_tag SET deleted=1,status=0,updated_by=:actor,updated_time=now() WHERE id=:id").param("actor",actor()).param("id",id).update();audit.record("DELETE","TAG","删除未使用数据标签",Map.of("tagId",id,"before",before,"reason",required(reason,"删除原因")));}

    public List<Map<String,Object>> dictionaries(){return jdbc.sql("SELECT d.*,(SELECT count(*) FROM gov_dictionary_item i WHERE i.dictionary_id=d.id AND i.deleted=0) item_count FROM gov_dictionary d WHERE d.deleted=0 ORDER BY d.dictionary_name,d.id").query(this::dictionaryRow).list();}
    public List<Map<String,Object>> dictionaryItems(Long dictionaryId){return jdbc.sql("SELECT * FROM gov_dictionary_item WHERE deleted=0 AND (CAST(:dictionary AS bigint) IS NULL OR dictionary_id=CAST(:dictionary AS bigint)) ORDER BY dictionary_id,sort_order,id").param("dictionary",dictionaryId).query(this::dictionaryItemRow).list();}
    @Transactional public long createDictionary(String name,String code,String description,int status){long id=jdbc.sql("INSERT INTO gov_dictionary(dictionary_name,dictionary_code,description,status,created_by) VALUES (:name,:code,:description,:status,:actor) RETURNING id").param("name",required(name,"字典名称")).param("code",code(code)).param("description",trim(description)).param("status",flag(status)).param("actor",actor()).query(Long.class).single();audit.record("CREATE","DICTIONARY","创建数据字典",Map.of("dictionaryId",id,"name",name,"code",code));return id;}
    @Transactional public void updateDictionary(long id,String name,String description,int status){referenceLockExclusive(4206);Map<String,Object> before=dictionary(id,true);jdbc.sql("UPDATE gov_dictionary SET dictionary_name=:name,description=:description,status=:status,updated_by=:actor,updated_time=now() WHERE id=:id AND deleted=0").param("name",required(name,"字典名称")).param("description",trim(description)).param("status",flag(status)).param("actor",actor()).param("id",id).update();audit.record("UPDATE","DICTIONARY","修改数据字典",Map.of("dictionaryId",id,"before",before,"after",dictionary(id,true)));}
    @Transactional public void deleteDictionary(long id,String reason){referenceLockExclusive(4206);Map<String,Object> before=dictionary(id,true);if(number(before,"itemCount")>0)throw new BusinessException(409,"字典仍有字典项，不能删除");jdbc.sql("UPDATE gov_dictionary SET deleted=1,status=0,updated_by=:actor,updated_time=now() WHERE id=:id").param("actor",actor()).param("id",id).update();audit.record("DELETE","DICTIONARY","删除空字典",Map.of("dictionaryId",id,"before",before,"reason",required(reason,"删除原因")));}
    @Transactional public long createDictionaryItem(long dictionaryId,String label,String value,int sortOrder,int status){referenceLockShared(4206);dictionary(dictionaryId,true);long id=jdbc.sql("INSERT INTO gov_dictionary_item(dictionary_id,item_label,item_value,sort_order,status,created_by) VALUES (:dictionary,:label,:value,:sort,:status,:actor) RETURNING id").param("dictionary",dictionaryId).param("label",required(label,"字典项名称")).param("value",required(value,"字典项值")).param("sort",sortOrder).param("status",flag(status)).param("actor",actor()).query(Long.class).single();audit.record("CREATE","DICTIONARY_ITEM","创建字典项",Map.of("itemId",id,"dictionaryId",dictionaryId,"label",label,"value",value));return id;}
    @Transactional public void updateDictionaryItem(long id,String label,String value,int sortOrder,int status){referenceLockExclusive(4206);Map<String,Object> before=dictionaryItem(id,true);String normalized=required(value,"字典项值");if(!normalized.equals(before.get("value"))&&dictionaryItemUsage(id)>0)throw new BusinessException(409,"字典项正在被业务数据使用，不能修改其值");jdbc.sql("UPDATE gov_dictionary_item SET item_label=:label,item_value=:value,sort_order=:sort,status=:status,updated_by=:actor,updated_time=now() WHERE id=:id AND deleted=0").param("label",required(label,"字典项名称")).param("value",normalized).param("sort",sortOrder).param("status",flag(status)).param("actor",actor()).param("id",id).update();audit.record("UPDATE","DICTIONARY_ITEM","修改字典项",Map.of("itemId",id,"before",before,"after",dictionaryItem(id,true)));}
    @Transactional public void deleteDictionaryItem(long id,String reason){referenceLockExclusive(4206);Map<String,Object> before=dictionaryItem(id,true);if(dictionaryItemUsage(id)>0)throw new BusinessException(409,"字典项正在被设备、数据集或生命周期策略使用，只能停用，不能删除");jdbc.sql("UPDATE gov_dictionary_item SET deleted=1,status=0,updated_by=:actor,updated_time=now() WHERE id=:id").param("actor",actor()).param("id",id).update();audit.record("DELETE","DICTIONARY_ITEM","删除未使用字典项",Map.of("itemId",id,"before",before,"reason",required(reason,"删除原因")));}

    public List<Map<String,Object>> menus(){return jdbc.sql("SELECT m.*,(SELECT count(*) FROM sys_menu c WHERE c.parent_id=m.id AND c.deleted=0) child_count FROM sys_menu m WHERE m.deleted=0 ORDER BY m.sort_order,m.id").query(this::menuRow).list();}
    @Transactional public long createMenu(String name,String code,String route,String icon,String permission,Long parentId,int sortOrder,int status){treeLock(4103);validMenuParent(parentId,null);validPermissionCode(permission);long id=jdbc.sql("INSERT INTO sys_menu(menu_name,menu_code,route_path,icon,permission_code,parent_id,sort_order,status,created_by) VALUES (:name,:code,:route,:icon,:permission,:parent,:sort,:status,:actor) RETURNING id").param("name",required(name,"菜单名称")).param("code",code(code)).param("route",route(route)).param("icon",trim(icon)).param("permission",blank(permission)).param("parent",parentId).param("sort",sortOrder).param("status",flag(status)).param("actor",actor()).query(Long.class).single();audit.record("CREATE","MENU","创建菜单",Map.of("menuId",id,"name",name,"code",code));return id;}
    @Transactional public void updateMenu(long id,String name,String route,String icon,String permission,Long parentId,int sortOrder,int status){treeLock(4103);Map<String,Object> before=menu(id,true);validMenuParent(parentId,id);ensureMenuNotDescendant(id,parentId);validPermissionCode(permission);jdbc.sql("UPDATE sys_menu SET menu_name=:name,route_path=:route,icon=:icon,permission_code=:permission,parent_id=:parent,sort_order=:sort,status=:status,updated_by=:actor,updated_time=now() WHERE id=:id AND deleted=0").param("name",required(name,"菜单名称")).param("route",route(route)).param("icon",trim(icon)).param("permission",blank(permission)).param("parent",parentId).param("sort",sortOrder).param("status",flag(status)).param("actor",actor()).param("id",id).update();audit.record("UPDATE","MENU","修改菜单",Map.of("menuId",id,"before",before,"after",menu(id,true)));}
    @Transactional public void deleteMenu(long id,String reason){treeLock(4103);Map<String,Object> before=menu(id,true);if(number(before,"childCount")>0)throw new BusinessException(409,"菜单仍有子菜单，不能删除");jdbc.sql("UPDATE sys_menu SET deleted=1,status=0,updated_by=:actor,updated_time=now() WHERE id=:id").param("actor",actor()).param("id",id).update();audit.record("DELETE","MENU","删除菜单",Map.of("menuId",id,"before",before,"reason",required(reason,"删除原因")));}

    public Map<String,Object> uiConfig(){return jdbc.sql("SELECT * FROM sys_ui_config WHERE id=1").query(this::uiConfigRow).single();}
    @Transactional public void updateUiConfig(String primaryColor,int fontSize,int borderRadius,int contentSpacing,int expectedVersion){Map<String,Object> before=uiConfig();int updated=jdbc.sql("UPDATE sys_ui_config SET primary_color=:color,font_size=:font,border_radius=:radius,content_spacing=:spacing,version=version+1,updated_by=:actor,updated_time=now() WHERE id=1 AND version=:version").param("color",color(primaryColor)).param("font",range(fontSize,12,20,"字体大小")).param("radius",range(borderRadius,0,24,"圆角大小")).param("spacing",range(contentSpacing,8,40,"内容间距")).param("actor",actor()).param("version",expectedVersion).update();if(updated==0)throw new BusinessException(409,"界面配置版本已变化，请刷新后重试");audit.record("UPDATE","UI_CONFIG","修改全局界面配置",Map.of("before",before,"after",uiConfig()));}

    private Map<String,Object> department(long id,boolean required){return jdbc.sql("""
            SELECT d.*,coalesce(u.real_name,'') leader_name,(SELECT count(*) FROM sys_user x WHERE x.department_id=d.id AND x.deleted=0) user_count,(SELECT count(*) FROM sys_department c WHERE c.parent_id=d.id AND c.deleted=0) child_count FROM sys_department d LEFT JOIN sys_user u ON u.id=d.leader_id WHERE d.id=:id AND d.deleted=0
            """).param("id",id).query(this::departmentRow).optional().orElseThrow(()->BusinessException.notFound("部门不存在"));}
    private Map<String,Object> role(long id,boolean required){return roles().stream().filter(v->number(v,"id")==id).findFirst().orElseThrow(()->BusinessException.notFound("角色不存在"));}
    private Map<String,Object> category(long id,boolean required){return categories(null).stream().filter(v->number(v,"id")==id).findFirst().orElseThrow(()->BusinessException.notFound("分类不存在"));}
    private Map<String,Object> tag(long id,boolean required){return tags().stream().filter(v->number(v,"id")==id).findFirst().orElseThrow(()->BusinessException.notFound("标签不存在"));}
    private Map<String,Object> dictionary(long id,boolean required){return dictionaries().stream().filter(v->number(v,"id")==id).findFirst().orElseThrow(()->BusinessException.notFound("字典不存在"));}
    private Map<String,Object> dictionaryItem(long id,boolean required){return dictionaryItems(null).stream().filter(v->number(v,"id")==id).findFirst().orElseThrow(()->BusinessException.notFound("字典项不存在"));}
    private Map<String,Object> menu(long id,boolean required){return menus().stream().filter(v->number(v,"id")==id).findFirst().orElseThrow(()->BusinessException.notFound("菜单不存在"));}
    private Map<String,Object> dataScope(long id){return dataScopes().stream().filter(v->number(v,"id")==id).findFirst().orElseThrow(()->BusinessException.notFound("数据域不存在"));}
    private Long validDepartmentParent(Long parent,Long self){if(parent==null)return null;if(self!=null&&parent.equals(self))throw BusinessException.badRequest("上级部门不能是自身");department(parent,true);return parent;}
    private String departmentPath(Long parent){return parent==null?"":String.valueOf(department(parent,true).get("path"));}
    private Long validUser(Long id){if(id==null)return null;referenceLockShared(4207);long count=jdbc.sql("SELECT count(*) FROM sys_user WHERE id=:id AND status=1 AND deleted=0").param("id",id).query(Long.class).single();if(count==0)throw BusinessException.badRequest("部门负责人不存在或未启用");return id;}
    private Long validCategoryParent(Long parent,String type,Long self){if(parent==null)return null;if(self!=null&&parent.equals(self))throw BusinessException.badRequest("上级分类不能是自身");categoryOfType(parent,type);return parent;}
    private void categoryOfType(long id,String type){long count=jdbc.sql("SELECT count(*) FROM gov_category WHERE id=:id AND category_type=:type AND deleted=0").param("id",id).param("type",type).query(Long.class).single();if(count==0)throw BusinessException.badRequest("分类类型或上级分类不正确");}
    private void ensureCategoryNotDescendant(long id,Long parent){if(parent==null)return;long count=jdbc.sql("WITH RECURSIVE descendants AS (SELECT id FROM gov_category WHERE parent_id=:id AND deleted=0 UNION ALL SELECT c.id FROM gov_category c JOIN descendants d ON c.parent_id=d.id WHERE c.deleted=0) SELECT count(*) FROM descendants WHERE id=:parent").param("id",id).param("parent",parent).query(Long.class).single();if(count>0)throw BusinessException.badRequest("不能把分类移动到其子分类下");}
    private void validMenuParent(Long parent,Long self){if(parent==null)return;if(self!=null&&parent.equals(self))throw BusinessException.badRequest("上级菜单不能是自身");menu(parent,true);}
    private void ensureMenuNotDescendant(long id,Long parent){if(parent==null)return;long count=jdbc.sql("WITH RECURSIVE descendants AS (SELECT id FROM sys_menu WHERE parent_id=:id AND deleted=0 UNION ALL SELECT c.id FROM sys_menu c JOIN descendants d ON c.parent_id=d.id WHERE c.deleted=0) SELECT count(*) FROM descendants WHERE id=:parent").param("id",id).param("parent",parent).query(Long.class).single();if(count>0)throw BusinessException.badRequest("不能把菜单移动到其子菜单下");}
    private void validPermissionCode(String code){String value=blank(code);if(value==null)return;List<String> values=Arrays.stream(value.split("\\|")).map(String::trim).filter(v->!v.isBlank()).distinct().toList();if(values.isEmpty()||values.size()!=value.split("\\|").length)throw BusinessException.badRequest("菜单权限标识不正确");long count=jdbc.sql("SELECT count(*) FROM sys_permission WHERE permission_code IN (:codes) AND status=1 AND deleted=0").param("codes",values).query(Long.class).single();if(count!=values.size())throw BusinessException.badRequest("菜单权限标识不存在或未启用");}
    private void validatePermissions(List<Long> raw){List<Long> values=ids(raw);if(values.isEmpty())return;long count=jdbc.sql("SELECT count(*) FROM sys_permission WHERE id IN (:ids) AND status=1 AND deleted=0").param("ids",values).query(Long.class).single();if(count!=values.size())throw BusinessException.badRequest("包含无效权限");}
    private void validateDelegablePermissions(List<Long> values){validatePermissions(values);UserPrincipal user=CurrentUser.require();if(user.admin()||values.isEmpty())return;List<String> requested=jdbc.sql("SELECT permission_code FROM sys_permission WHERE id IN (:ids) AND status=1 AND deleted=0").param("ids",values).query(String.class).list();if(!user.permissions().containsAll(requested))throw new BusinessException(403,"不能向角色授予当前账号自身不具备的权限");}
    private long dictionaryItemUsage(long id){return jdbc.sql("""
            SELECT CASE d.dictionary_code
              WHEN 'DEVICE_PROTOCOL' THEN (SELECT count(*) FROM device x WHERE x.protocol=i.item_value)
              WHEN 'DATA_IMPORTANCE' THEN ((SELECT count(*) FROM data_dataset x WHERE x.importance_level=i.item_value AND x.deleted=0)+(SELECT count(*) FROM lifecycle_retention_policy p WHERE p.importance_level=i.item_value))
              ELSE 0 END
            FROM gov_dictionary_item i JOIN gov_dictionary d ON d.id=i.dictionary_id WHERE i.id=:id AND i.deleted=0 FOR SHARE OF i,d
            """).param("id",id).query(Long.class).optional().orElseThrow(()->BusinessException.notFound("字典项不存在"));}
    private boolean menuAncestorsEnabled(Map<String,Object> menu,Map<Long,Map<String,Object>> byId,Set<Long> visited){Object raw=menu.get("parentId");if(raw==null)return true;long parentId=((Number)raw).longValue();if(!visited.add(parentId))return false;Map<String,Object> parent=byId.get(parentId);return parent!=null&&number(parent,"status")==1&&menuAncestorsEnabled(parent,byId,visited);}
    private void treeLock(long key){jdbc.sql("SELECT 1 FROM (SELECT pg_advisory_xact_lock(:key)) locked").param("key",key).query(Long.class).single();}
    private void referenceLockShared(long key){jdbc.sql("SELECT 1 FROM (SELECT pg_advisory_xact_lock_shared(:key)) locked").param("key",key).query(Long.class).single();}
    private void referenceLockExclusive(long key){jdbc.sql("SELECT 1 FROM (SELECT pg_advisory_xact_lock(:key)) locked").param("key",key).query(Long.class).single();}
    private void replaceRolePermissions(long roleId,List<Long> raw){List<Long> values=ids(raw);jdbc.sql("DELETE FROM sys_role_permission WHERE role_id=:id").param("id",roleId).update();for(Long permission:values)jdbc.sql("INSERT INTO sys_role_permission(role_id,permission_id) VALUES (:role,:permission)").param("role",roleId).param("permission",permission).update();}
    private List<Long> roleUsers(long roleId){return jdbc.sql("SELECT user_id FROM sys_user_role WHERE role_id=:id ORDER BY user_id").param("id",roleId).query(Long.class).list();}
    private long actor(){return CurrentUser.require().id();}
    private String categoryType(String value){String normalized=required(value,"分类类型").toUpperCase(Locale.ROOT);if(!CATEGORY_TYPES.contains(normalized))throw BusinessException.badRequest("分类类型不正确");return normalized;}
    private String scopeType(String value){String normalized=required(value,"数据域类型").toUpperCase(Locale.ROOT);if(!Set.of("GLOBAL","DEPARTMENT","PROJECT","PRODUCT_LINE").contains(normalized))throw BusinessException.badRequest("数据域类型不正确");return normalized;}
    private String code(String value){String normalized=required(value,"编码").trim().toUpperCase(Locale.ROOT);if(!normalized.matches("^[A-Z][A-Z0-9_-]{1,49}$"))throw BusinessException.badRequest("编码必须以字母开头，只能包含大写字母、数字、下划线或横线");return normalized;}
    private String route(String value){String normalized=blank(value);if(normalized!=null&&(!normalized.startsWith("/")||normalized.contains("..")||normalized.contains(";")||normalized.contains("\\")))throw BusinessException.badRequest("菜单路由不正确");return normalized;}
    private String color(String value){String normalized=required(value,"颜色");if(!normalized.matches("^#[0-9A-Fa-f]{6}$"))throw BusinessException.badRequest("颜色必须是六位十六进制值");return normalized.toUpperCase(Locale.ROOT);}
    private int flag(int value){if(value!=0&&value!=1)throw BusinessException.badRequest("状态只能是启用或停用");return value;}
    private int range(int value,int min,int max,String name){if(value<min||value>max)throw BusinessException.badRequest(name+"超出范围");return value;}
    private String required(String value,String name){if(value==null||value.isBlank())throw BusinessException.badRequest(name+"不能为空");return value.trim();}
    private String trim(String value){return value==null?null:value.trim();}
    private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
    private List<Long> ids(List<Long> raw){if(raw==null)return List.of();LinkedHashSet<Long> values=new LinkedHashSet<>();for(Long value:raw){if(value==null||value<=0)throw BusinessException.badRequest("ID必须为正数");values.add(value);}if(values.size()!=raw.size())throw BusinessException.badRequest("ID不能重复");return new ArrayList<>(values);}
    private String[] strings(List<String> raw){if(raw==null)return new String[0];return raw.stream().map(String::trim).filter(v->!v.isBlank()).distinct().toArray(String[]::new);}
    private long number(Map<String,Object> value,String key){Object raw=value.get(key);return raw instanceof Number n?n.longValue():0;}
    private List<String> stringArray(Array value)throws SQLException{return value==null?List.of():Arrays.stream((Object[])value.getArray()).map(String::valueOf).toList();}
    private List<Long> longArray(Array value)throws SQLException{return value==null?List.of():Arrays.stream((Object[])value.getArray()).map(v->((Number)v).longValue()).toList();}
    private Map<String,Object> base(ResultSet rs,String id,String name,String code)throws SQLException{Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getLong(id));row.put("name",rs.getString(name));row.put("code",rs.getString(code));return row;}
    private Map<String,Object> departmentRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=base(rs,"id","dept_name","dept_code");r.put("parentId",rs.getObject("parent_id"));r.put("path",rs.getString("dept_path"));r.put("leaderId",rs.getObject("leader_id"));r.put("leaderName",rs.getString("leader_name"));r.put("sortOrder",rs.getInt("sort_order"));r.put("status",rs.getInt("status"));r.put("userCount",rs.getLong("user_count"));r.put("childCount",rs.getLong("child_count"));r.put("createdTime",rs.getObject("created_time"));return r;}
    private Map<String,Object> permissionRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=base(rs,"id","permission_name","permission_code");r.put("resourceType",rs.getString("resource_type"));r.put("resourcePath",rs.getString("resource_path"));r.put("httpMethod",rs.getString("http_method"));r.put("parentId",rs.getObject("parent_id"));r.put("description",rs.getString("description"));r.put("sortOrder",rs.getInt("sort_order"));r.put("status",rs.getInt("status"));return r;}
    private Map<String,Object> roleRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=base(rs,"id","role_name","role_code");r.put("description",rs.getString("description"));r.put("status",rs.getInt("status"));r.put("sortOrder",rs.getInt("sort_order"));r.put("userCount",rs.getLong("user_count"));r.put("permissionIds",longArray(rs.getArray("permission_ids")));r.put("version",rs.getInt("version"));r.put("createdTime",rs.getObject("created_time"));return r;}
    private Map<String,Object> categoryRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=base(rs,"id","category_name","category_code");r.put("type",rs.getString("category_type"));r.put("parentId",rs.getObject("parent_id"));r.put("productCodes",stringArray(rs.getArray("product_codes")));r.put("sortOrder",rs.getInt("sort_order"));r.put("status",rs.getInt("status"));r.put("childCount",rs.getLong("child_count"));r.put("datasetCount",rs.getLong("dataset_count"));r.put("createdTime",rs.getObject("created_time"));return r;}
    private Map<String,Object> tagRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=base(rs,"id","tag_name","tag_name");r.remove("code");r.put("color",rs.getString("tag_color"));r.put("group",rs.getString("tag_group"));r.put("status",rs.getInt("status"));r.put("usageCount",rs.getLong("usage_count"));r.put("createdTime",rs.getObject("created_time"));return r;}
    private Map<String,Object> dictionaryRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=base(rs,"id","dictionary_name","dictionary_code");r.put("description",rs.getString("description"));r.put("status",rs.getInt("status"));r.put("itemCount",rs.getLong("item_count"));r.put("createdTime",rs.getObject("created_time"));return r;}
    private Map<String,Object> dictionaryItemRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=new LinkedHashMap<>();r.put("id",rs.getLong("id"));r.put("dictionaryId",rs.getLong("dictionary_id"));r.put("label",rs.getString("item_label"));r.put("value",rs.getString("item_value"));r.put("sortOrder",rs.getInt("sort_order"));r.put("status",rs.getInt("status"));r.put("createdTime",rs.getObject("created_time"));return r;}
    private Map<String,Object> menuRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=base(rs,"id","menu_name","menu_code");r.put("route",rs.getString("route_path"));r.put("icon",rs.getString("icon"));r.put("permissionCode",rs.getString("permission_code"));r.put("parentId",rs.getObject("parent_id"));r.put("sortOrder",rs.getInt("sort_order"));r.put("status",rs.getInt("status"));try{r.put("childCount",rs.getLong("child_count"));}catch(SQLException ignored){}r.put("createdTime",rs.getObject("created_time"));return r;}
    private Map<String,Object> uiConfigRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=new LinkedHashMap<>();r.put("primaryColor",rs.getString("primary_color"));r.put("fontSize",rs.getInt("font_size"));r.put("borderRadius",rs.getInt("border_radius"));r.put("contentSpacing",rs.getInt("content_spacing"));r.put("version",rs.getInt("version"));r.put("updatedTime",rs.getObject("updated_time"));return r;}
    private Map<String,Object> scopeRow(ResultSet rs,int n)throws SQLException{Map<String,Object> r=base(rs,"id","scope_name","scope_code");r.put("type",rs.getString("scope_type"));r.put("description",rs.getString("description"));r.put("active",rs.getBoolean("active"));r.put("version",rs.getInt("version"));r.put("userCount",rs.getLong("user_count"));r.put("resourceCount",rs.getLong("resource_count"));r.put("createdTime",rs.getObject("created_time"));return r;}
}
