package com.justeam.rdp.admin;

import com.justeam.rdp.audit.AuditService;
import com.justeam.rdp.common.BusinessException;
import com.justeam.rdp.security.CurrentUser;
import com.justeam.rdp.security.TokenService;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.web.multipart.MultipartFile;

import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;

@Service
public class UserAdministrationService {
    private final JdbcClient jdbc;private final PasswordEncoder passwords;private final TokenService tokens;private final AuditService audit;private final TransactionTemplate transactions;private final SecureRandom random=new SecureRandom();
    public UserAdministrationService(JdbcClient jdbc,PasswordEncoder passwords,TokenService tokens,AuditService audit,TransactionTemplate transactions){this.jdbc=jdbc;this.passwords=passwords;this.tokens=tokens;this.audit=audit;this.transactions=transactions;}

    @Transactional public Map<String,Object> create(String username,String realName,String email,String phone,Long departmentId,List<Long> roleIds,List<Long> scopeIds,int status,String reason){return createInternal(username,realName,email,phone,departmentId,roleIds,scopeIds,status,reason);}
    @Transactional public void update(long id,String realName,String email,String phone,String reason){adminMutationLock();referenceLockShared(4204);requireManageableTarget(id);Map<String,Object> before=user(id);String normalizedEmail=normalizeEmail(email),normalizedPhone=blank(phone);requirePendingRegistrationContactUnchanged(id,before,normalizedEmail,normalizedPhone);int updated=jdbc.sql("UPDATE sys_user SET real_name=:name,email=:email,phone=:phone,updated_by=:actor,updated_time=now() WHERE id=:id AND deleted=0").param("name",required(realName,"姓名")).param("email",normalizedEmail).param("phone",normalizedPhone).param("actor",actor()).param("id",id).update();if(updated==0)throw BusinessException.notFound("用户不存在");tokens.revoke(id);audit.record("UPDATE","USER","修改用户资料并撤销目标会话",Map.of("userId",id,"before",before,"after",user(id),"reason",required(reason,"修改原因")));}
    @Transactional public Map<String,String> resetPassword(long id,String reason){adminMutationLock();referenceLockShared(4204);requireManageableTarget(id);Map<String,Object> before=user(id);String temporary=temporaryPassword();jdbc.sql("UPDATE sys_user SET password=:password,secondary_password=NULL,must_change_password=TRUE,password_changed_time=now(),failed_attempts=0,updated_by=:actor,updated_time=now() WHERE id=:id AND deleted=0").param("password",passwords.encode(temporary)).param("actor",actor()).param("id",id).update();tokens.revoke(id);audit.record("RESET_PASSWORD","USER","重置用户密码并撤销会话",Map.of("userId",id,"username",before.get("username"),"reason",required(reason,"重置原因"),"mustChangePassword",true,"secondaryCredentialCleared",true));return Map.of("temporaryPassword",temporary);}
    @Transactional public void delete(long id,String reason){adminMutationLock();referenceLockShared(4204);referenceLockExclusive(4207);if(id==actor())throw BusinessException.badRequest("不能删除当前账号");requireManageableTarget(id);Map<String,Object> before=user(id);if(isSoleAdmin(id))throw BusinessException.badRequest("不能删除唯一启用管理员");if(departmentLeadershipCount(id)>0)throw new BusinessException(409,"该用户仍是部门负责人，请先完成负责人移交");if(jdbc.sql("SELECT count(*) FROM sys_share_rule WHERE grantee_type='USER' AND grantee_id=:id AND status='ACTIVE'").param("id",id).query(Long.class).single()>0)throw new BusinessException(409,"该用户仍有生效共享规则，请先撤销共享");jdbc.sql("DELETE FROM sys_user_role WHERE user_id=:id").param("id",id).update();jdbc.sql("DELETE FROM sys_user_data_scope WHERE user_id=:id").param("id",id).update();jdbc.sql("UPDATE sys_user SET deleted=1,status=0,email=NULL,phone=NULL,secondary_password=NULL,updated_by=:actor,updated_time=now() WHERE id=:id AND deleted=0").param("actor",actor()).param("id",id).update();tokens.revoke(id);audit.record("DELETE","USER","逻辑删除用户并撤销会话",Map.of("userId",id,"before",before,"reason",required(reason,"删除原因")));}

    public Map<String,Object> importUsers(MultipartFile file,String reason){if(file==null||file.isEmpty())throw BusinessException.badRequest("请选择导入文件");if(file.getSize()>5*1024*1024)throw new BusinessException(413,"用户导入文件不能超过5MB");List<Map<String,String>> rows=readRows(file);if(rows.size()>1000)throw BusinessException.badRequest("单次最多导入1000个用户");List<Map<String,Object>> successes=new ArrayList<>(),failures=new ArrayList<>();int rowNumber=1;for(Map<String,String> row:rows){rowNumber++;int current=rowNumber;try{Map<String,Object> result=transactions.execute(status->{List<Long> roleIds=idsByCodes("sys_role","role_code",split(row.get("roleCodes")),"角色");List<Long> scopeIds=idsByCodes("sys_data_scope","scope_code",split(row.get("scopeCodes")),"数据域");Long department=departmentByCode(row.get("departmentCode"));return createInternal(row.get("username"),row.get("realName"),row.get("email"),row.get("phone"),department,roleIds,scopeIds,parseStatus(row.get("status")),"批量导入："+reason);});Map<String,Object> success=new LinkedHashMap<>(result);success.put("rowNumber",current);successes.add(success);}catch(Exception ex){failures.add(Map.of("rowNumber",current,"username",String.valueOf(row.getOrDefault("username","")),"message",safeMessage(ex)));}}
        audit.record("IMPORT","USER","批量导入用户",Map.of("fileName",safeName(file.getOriginalFilename()),"total",rows.size(),"success",successes.size(),"failure",failures.size(),"reason",required(reason,"导入原因")));return Map.of("total",rows.size(),"successCount",successes.size(),"failureCount",failures.size(),"successes",successes,"failures",failures);}

    private Map<String,Object> createInternal(String username,String realName,String email,String phone,Long departmentId,List<Long> roleIds,List<Long> scopeIds,int status,String reason){adminMutationLock();referenceLockShared(4203);referenceLockShared(4204);referenceLockShared(4205);String account=required(username,"用户名").toLowerCase(Locale.ROOT);if(!account.matches("^[a-z][a-z0-9_.-]{2,49}$"))throw BusinessException.badRequest("用户名须为3-50位小写字母、数字、点、横线或下划线");validDepartment(departmentId);requireGrantableDepartment(departmentId);validateIds(roleIds,scopeIds);requireGrantableRoles(roleIds);requireGrantableScopes(scopeIds);String temporary=temporaryPassword();long id=jdbc.sql("INSERT INTO sys_user(username,real_name,email,phone,password,status,department_id,must_change_password,created_by) VALUES (:username,:name,:email,:phone,:password,:status,:department,TRUE,:actor) RETURNING id").param("username",account).param("name",required(realName,"姓名")).param("email",normalizeEmail(email)).param("phone",blank(phone)).param("password",passwords.encode(temporary)).param("status",flag(status)).param("department",departmentId).param("actor",actor()).query(Long.class).single();replaceAssignments(id,roleIds,scopeIds);audit.record("CREATE","USER","创建用户并分配初始授权",Map.of("userId",id,"username",account,"roleIds",roleIds,"scopeIds",scopeIds==null?List.of():scopeIds,"departmentId",departmentId==null?0:departmentId,"status",status,"reason",required(reason,"创建原因"),"temporaryPasswordIssued",true));Map<String,Object> result=new LinkedHashMap<>();result.put("id",id);result.put("username",account);result.put("temporaryPassword",temporary);return result;}
    private void replaceAssignments(long userId,List<Long> roleIds,List<Long> scopeIds){for(Long role:roleIds)jdbc.sql("INSERT INTO sys_user_role(user_id,role_id) VALUES (:user,:role)").param("user",userId).param("role",role).update();if(scopeIds!=null)for(Long scope:scopeIds)jdbc.sql("INSERT INTO sys_user_data_scope(user_id,data_scope_id) VALUES (:user,:scope)").param("user",userId).param("scope",scope).update();}
    private void validateIds(List<Long> roleIds,List<Long> scopeIds){if(roleIds==null||roleIds.isEmpty())throw BusinessException.badRequest("至少分配一个角色");if(roleIds.stream().distinct().count()!=roleIds.size())throw BusinessException.badRequest("角色不能重复");long roles=jdbc.sql("SELECT count(*) FROM sys_role WHERE id IN (:ids) AND status=1 AND deleted=0").param("ids",roleIds).query(Long.class).single();if(roles!=roleIds.size())throw BusinessException.badRequest("包含无效角色");if(scopeIds!=null&&!scopeIds.isEmpty()){if(scopeIds.stream().distinct().count()!=scopeIds.size())throw BusinessException.badRequest("数据域不能重复");long scopes=jdbc.sql("SELECT count(*) FROM sys_data_scope WHERE id IN (:ids) AND active=TRUE").param("ids",scopeIds).query(Long.class).single();if(scopes!=scopeIds.size())throw BusinessException.badRequest("包含无效数据域");}}
    private List<Long> idsByCodes(String table,String column,List<String> codes,String name){if(codes.isEmpty()&&"角色".equals(name))throw BusinessException.badRequest("角色编码不能为空");if(codes.isEmpty())return List.of();String active="sys_role".equals(table)?"status=1 AND deleted=0":"active=TRUE";List<Long> ids=jdbc.sql("SELECT id FROM "+table+" WHERE "+column+" IN (:codes) AND "+active+" ORDER BY id").param("codes",codes).query(Long.class).list();if(ids.size()!=codes.size())throw BusinessException.badRequest("包含不存在或停用的"+name+"编码");return ids;}
    private Long departmentByCode(String code){String value=blank(code);if(value==null)return null;return jdbc.sql("SELECT id FROM sys_department WHERE dept_code=:code AND status=1 AND deleted=0").param("code",value.toUpperCase(Locale.ROOT)).query(Long.class).optional().orElseThrow(()->BusinessException.badRequest("部门编码不存在或已停用"));}
    private void validDepartment(Long id){if(id==null)return;long count=jdbc.sql("SELECT count(*) FROM sys_department WHERE id=:id AND status=1 AND deleted=0").param("id",id).query(Long.class).single();if(count==0)throw BusinessException.badRequest("部门不存在或已停用");}
    private Map<String,Object> user(long id){return jdbc.sql("SELECT id,username,real_name,email,phone,status,department_id,must_change_password,created_time,updated_time FROM sys_user WHERE id=:id AND deleted=0").param("id",id).query((rs,n)->{Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getLong("id"));row.put("username",rs.getString("username"));row.put("realName",rs.getString("real_name"));row.put("email",rs.getString("email"));row.put("phone",rs.getString("phone"));row.put("status",rs.getInt("status"));row.put("departmentId",rs.getObject("department_id"));row.put("mustChangePassword",rs.getBoolean("must_change_password"));row.put("createdTime",rs.getObject("created_time"));row.put("updatedTime",rs.getObject("updated_time"));return row;}).optional().orElseThrow(()->BusinessException.notFound("用户不存在"));}
    private boolean isSoleAdmin(long id){long admins=jdbc.sql("SELECT count(DISTINCT u.id) FROM sys_user u JOIN sys_user_role ur ON ur.user_id=u.id JOIN sys_role r ON r.id=ur.role_id WHERE u.status=1 AND u.deleted=0 AND r.role_code='ADMIN' AND r.status=1 AND r.deleted=0").query(Long.class).single();long target=jdbc.sql("SELECT count(*) FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=:id AND r.role_code='ADMIN' AND r.status=1 AND r.deleted=0").param("id",id).query(Long.class).single();return admins<=1&&target>0;}
    private long departmentLeadershipCount(long userId){return jdbc.sql("SELECT count(*) FROM sys_department WHERE leader_id=:id AND deleted=0").param("id",userId).query(Long.class).single();}
    private void requireGrantableRoles(List<Long> roleIds){var user=CurrentUser.require();if(user.admin())return;long held=jdbc.sql("SELECT count(DISTINCT ur.role_id) FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id AND r.status=1 AND r.deleted=0 WHERE ur.user_id=:user AND ur.role_id IN (:ids)").param("user",user.id()).param("ids",roleIds).query(Long.class).single();if(held!=roleIds.stream().distinct().count())throw new BusinessException(403,"非系统管理员只能授予自己当前持有的角色");List<String> permissions=jdbc.sql("SELECT DISTINCT p.permission_code FROM sys_role_permission rp JOIN sys_permission p ON p.id=rp.permission_id AND p.status=1 AND p.deleted=0 WHERE rp.role_id IN (:ids)").param("ids",roleIds).query(String.class).list();if(!user.permissions().containsAll(permissions))throw new BusinessException(403,"不能授予当前账号自身不具备的角色权限");}
    private void requireGrantableScopes(List<Long> scopeIds){var user=CurrentUser.require();if(user.admin()||scopeIds==null||scopeIds.isEmpty())return;if(!user.assignedScopes().containsAll(scopeIds))throw new BusinessException(403,"不能授予当前账号未直接拥有的数据域");long global=jdbc.sql("SELECT count(*) FROM sys_data_scope WHERE id IN (:ids) AND scope_type='GLOBAL'").param("ids",scopeIds).query(Long.class).single();if(global>0)throw new BusinessException(403,"只有系统管理员可以授予全局数据域");}
    private void requireGrantableDepartment(Long departmentId){var user=CurrentUser.require();if(user.admin()||departmentId==null)return;Long own=jdbc.sql("SELECT department_id FROM sys_user WHERE id=:id AND deleted=0").param("id",user.id()).query(Long.class).optional().orElse(null);if(!Objects.equals(own,departmentId))throw new BusinessException(403,"不能分配当前账号管理范围外的部门");}
    private void requirePendingRegistrationContactUnchanged(long id,Map<String,Object> before,String email,String phone){String channel=jdbc.sql("SELECT verification_channel FROM sys_registration_application WHERE user_id=:id AND status='PENDING'").param("id",id).query(String.class).optional().orElse(null);if(channel==null)return;String currentEmail=normalizeEmail((String)before.get("email")),currentPhone=blank((String)before.get("phone"));if(!Objects.equals(currentEmail,email)||!Objects.equals(currentPhone,phone))throw new BusinessException(409,"待审核注册账号的已验证联系方式不能修改");}
    private void requireManageableTarget(long userId){var user=CurrentUser.require();if(user.admin())return;long adminRole=jdbc.sql("SELECT count(*) FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=:id AND r.role_code='ADMIN' AND r.status=1 AND r.deleted=0").param("id",userId).query(Long.class).single();List<String> permissions=jdbc.sql("SELECT DISTINCT p.permission_code FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id AND r.status=1 AND r.deleted=0 JOIN sys_role_permission rp ON rp.role_id=r.id JOIN sys_permission p ON p.id=rp.permission_id AND p.status=1 AND p.deleted=0 WHERE ur.user_id=:id").param("id",userId).query(String.class).list();if(adminRole>0||!user.permissions().containsAll(permissions))throw new BusinessException(403,"不能管理权限高于当前账号的用户");}
    private List<Map<String,String>> readRows(MultipartFile file){String name=safeName(file.getOriginalFilename()).toLowerCase(Locale.ROOT);try{if(name.endsWith(".xlsx")){try(var workbook=WorkbookFactory.create(file.getInputStream())){var sheet=workbook.getSheetAt(0);if(sheet.getPhysicalNumberOfRows()<2)return List.of();DataFormatter formatter=new DataFormatter();Map<String,Integer> headers=new LinkedHashMap<>();Row header=sheet.getRow(sheet.getFirstRowNum());if(header==null)throw BusinessException.badRequest("用户导入文件缺少表头");for(int i=0;i<header.getLastCellNum();i++)headers.put(formatter.formatCellValue(header.getCell(i)).trim(),i);List<String> missing=requiredHeaders().stream().filter(key->!headers.containsKey(key)).toList();if(!missing.isEmpty())throw BusinessException.badRequest("用户导入文件缺少表头："+String.join(",",missing));List<Map<String,String>> rows=new ArrayList<>();for(int n=header.getRowNum()+1;n<=sheet.getLastRowNum();n++){Row row=sheet.getRow(n);if(row==null)continue;Map<String,String> value=new LinkedHashMap<>();for(String key:requiredHeaders())value.put(key,formatter.formatCellValue(row.getCell(headers.get(key))).trim());if(value.values().stream().allMatch(String::isBlank))continue;rows.add(value);}return rows;}}if(!name.endsWith(".csv"))throw BusinessException.badRequest("用户批量导入仅支持CSV或XLSX");try(CSVParser parser=CSVFormat.DEFAULT.builder().setHeader().setSkipHeaderRecord(true).get().parse(new InputStreamReader(file.getInputStream(),StandardCharsets.UTF_8))){List<String> missing=requiredHeaders().stream().filter(key->!parser.getHeaderMap().containsKey(key)).toList();if(!missing.isEmpty())throw BusinessException.badRequest("用户导入文件缺少表头："+String.join(",",missing));List<Map<String,String>> rows=new ArrayList<>();for(var record:parser){Map<String,String> value=new LinkedHashMap<>();for(String key:requiredHeaders())value.put(key,record.get(key).trim());rows.add(value);}return rows;}}catch(BusinessException ex){throw ex;}catch(Exception ex){throw BusinessException.badRequest("用户导入文件无法解析");}}
    private List<String> requiredHeaders(){return List.of("username","realName","email","phone","departmentCode","roleCodes","scopeCodes","status");}
    private List<String> split(String raw){String value=blank(raw);if(value==null)return List.of();return java.util.Arrays.stream(value.split("[,|]")).map(String::trim).filter(v->!v.isBlank()).map(v->v.toUpperCase(Locale.ROOT)).distinct().toList();}
    private int parseStatus(String raw){String value=blank(raw);if(value==null)return 1;try{return flag(Integer.parseInt(value));}catch(NumberFormatException ex){throw BusinessException.badRequest("状态只能是0或1");}}
    private String temporaryPassword(){byte[] bytes=new byte[9];random.nextBytes(bytes);return "Tmp@7"+Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);}
    private int flag(int value){if(value!=0&&value!=1)throw BusinessException.badRequest("状态只能是0或1");return value;}
    private long actor(){return CurrentUser.require().id();}
    private String required(String value,String name){if(value==null||value.isBlank())throw BusinessException.badRequest(name+"不能为空");return value.trim();}
    private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
    private String normalizeEmail(String value){String result=blank(value);return result==null?null:result.toLowerCase(Locale.ROOT);}
    private String safeName(String value){return value==null?"users":value.replaceAll("[^A-Za-z0-9._-]","_");}
    private String safeMessage(Exception ex){
        if(ex instanceof BusinessException business)return business.getMessage();
        if(ex instanceof DataIntegrityViolationException)return "用户名、邮箱或手机号已存在";
        return "导入失败，请检查字段格式或联系管理员";
    }
    private void adminMutationLock(){jdbc.sql("SELECT 1 FROM (SELECT pg_advisory_xact_lock(34882201)) x").query(Long.class).single();}
    private void referenceLockShared(long key){jdbc.sql("SELECT 1 FROM (SELECT pg_advisory_xact_lock_shared(:key)) locked").param("key",key).query(Long.class).single();}
    private void referenceLockExclusive(long key){jdbc.sql("SELECT 1 FROM (SELECT pg_advisory_xact_lock(:key)) locked").param("key",key).query(Long.class).single();}
}
