package com.justeam.rdp.lifecycle;

import com.justeam.rdp.audit.AuditService;
import com.justeam.rdp.common.BusinessException;
import com.justeam.rdp.common.JsonSupport;
import com.justeam.rdp.common.PageResponse;
import com.justeam.rdp.governance.DictionaryOptionService;
import com.justeam.rdp.security.CurrentUser;
import com.justeam.rdp.security.DataScopeService;
import com.justeam.rdp.security.UserPrincipal;
import com.mongodb.client.gridfs.model.GridFSFile;
import org.bson.Document;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.springframework.data.mongodb.gridfs.GridFsTemplate;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.FilterInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.security.DigestInputStream;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import java.util.zip.ZipOutputStream;

@Service
public class LifecycleService {
    private static final Set<String> IMPORTANCE=Set.of("LOW","NORMAL","HIGH","CRITICAL");
    private final JdbcClient jdbc;private final MongoTemplate mongo;private final GridFsTemplate gridFs;
    private final JsonSupport json;private final AuditService audit;private final DataScopeService scopes;
    private final TransactionTemplate transactions;private final Path archiveRoot;private final long staleTransitionMinutes;private final DictionaryOptionService dictionaries;

    public LifecycleService(JdbcClient jdbc, MongoTemplate mongo, GridFsTemplate gridFs, JsonSupport json,
                            AuditService audit, DataScopeService scopes, TransactionTemplate transactions,DictionaryOptionService dictionaries,
                            @Value("${rdp.lifecycle.archive-root:./data/archive}") String archiveRoot,
                            @Value("${rdp.lifecycle.stale-transition-minutes:15}") long staleTransitionMinutes) {
        this.jdbc=jdbc;this.mongo=mongo;this.gridFs=gridFs;this.json=json;this.audit=audit;this.scopes=scopes;
        this.transactions=transactions;this.dictionaries=dictionaries;this.archiveRoot=Path.of(archiveRoot).toAbsolutePath().normalize();this.staleTransitionMinutes=Math.max(1,staleTransitionMinutes);
    }

    public List<Map<String,Object>> policies(){UserPrincipal user=CurrentUser.require();String visible=user.admin()?"TRUE":user.assignedScopes().isEmpty()?"p.data_scope_id IS NULL":"(p.data_scope_id IS NULL OR p.data_scope_id IN (:scopes))";JdbcClient.StatementSpec query=jdbc.sql("""
            SELECT p.*,s.scope_name,u.username created_username,uu.username updated_username
            FROM lifecycle_retention_policy p LEFT JOIN sys_data_scope s ON s.id=p.data_scope_id
            LEFT JOIN sys_user u ON u.id=p.created_by LEFT JOIN sys_user uu ON uu.id=p.updated_by
            WHERE 
            """+visible+" ORDER BY p.data_scope_id NULLS FIRST,p.importance_level");if(!user.admin()&&!user.assignedScopes().isEmpty())query=query.param("scopes",user.assignedScopes());return query.query(this::policyRow).list();}

    public long savePolicy(Long id,String importance,Long scopeId,int onlineDays,String target,boolean autoArchive,boolean active,Integer expectedVersion){
        String level=normalizeImportance(importance);if(onlineDays<0||onlineDays>36500)throw BusinessException.badRequest("在线保存天数须在0至36500之间");if(target==null||target.isBlank()||target.length()>100)throw BusinessException.badRequest("归档目标不能为空且最长100字符");
        if(autoArchive&&active)verifyArchiveTarget();
        UserPrincipal user=CurrentUser.require();authorizePolicyScope(user,scopeId);
        return transactions.execute(status->{
            dictionaries.requireEnabled("DATA_IMPORTANCE",level,"数据重要性");if(scopeId!=null)scopes.require(scopeId);
            if(id==null){
                long created;
                try{created=jdbc.sql("INSERT INTO lifecycle_retention_policy(importance_level,data_scope_id,online_days,archive_target,auto_archive,active,created_by) VALUES (:level,:scope,:days,:target,:auto,:active,:actor) RETURNING id").param("level",level).param("scope",scopeId).param("days",onlineDays).param("target",target.trim()).param("auto",autoArchive).param("active",active).param("actor",user.id()).query(Long.class).single();}
                catch(Exception ex){throw new BusinessException(409,"相同数据域和重要级别的策略已存在");}
                audit.record("LIFECYCLE_POLICY_CREATE","LIFECYCLE","创建生命周期策略",Map.of("policyId",created,"after",policySnapshot(created)));
                return created;
            }
            if(expectedVersion==null||expectedVersion<1)throw BusinessException.badRequest("更新策略必须提供版本");
            PolicyScope original=jdbc.sql("SELECT data_scope_id FROM lifecycle_retention_policy WHERE id=:id FOR UPDATE").param("id",id).query((rs,n)->{Object value=rs.getObject("data_scope_id");return new PolicyScope(value==null?null:((Number)value).longValue());}).optional().orElseThrow(()->BusinessException.notFound("生命周期策略不存在"));
            authorizePolicyScope(user,original.scopeId());Map<String,Object> before=policySnapshot(id);
            int changed=jdbc.sql("UPDATE lifecycle_retention_policy SET importance_level=:level,data_scope_id=:scope,online_days=:days,archive_target=:target,auto_archive=:auto,active=:active,updated_by=:actor,updated_time=now(),version=version+1 WHERE id=:id AND version=:version").param("level",level).param("scope",scopeId).param("days",onlineDays).param("target",target.trim()).param("auto",autoArchive).param("active",active).param("actor",user.id()).param("id",id).param("version",expectedVersion).update();
            if(changed==0)throw new BusinessException(409,"策略版本已变化，请刷新后重试");
            audit.record("LIFECYCLE_POLICY_UPDATE","LIFECYCLE","更新生命周期策略",Map.of("policyId",id,"before",before,"after",policySnapshot(id)));
            return id;
        });
    }

    public void setImportance(long datasetId,String importance){String level=normalizeImportance(importance);Map<String,Object> dataset=dataset(datasetId);scopes.require(((Number)dataset.get("dataScopeId")).longValue());String before=String.valueOf(dataset.get("importanceLevel"));transactions.executeWithoutResult(status->{dictionaries.requireEnabled("DATA_IMPORTANCE",level,"数据重要性");jdbc.sql("UPDATE data_dataset SET importance_level=:level,updated_time=now(),version=version+1 WHERE id=:id").param("level",level).param("id",datasetId).update();audit.record("LIFECYCLE_IMPORTANCE","LIFECYCLE","调整数据集重要性",Map.of("datasetId",datasetId,"before",before,"after",level));});}

    public List<Map<String,Object>> preview(int limit){UserPrincipal user=CurrentUser.require();int size=Math.max(1,Math.min(limit,500));String scope=user.admin()?"TRUE":user.assignedScopes().isEmpty()?"FALSE":"d.data_scope_id IN (:scopes)";JdbcClient.StatementSpec spec=jdbc.sql("""
            SELECT w.dataset_id,w.record_id,d.name dataset_name,d.importance_level,d.data_scope_id,
                   coalesce(w.published_time,w.record_created_time,w.updated_time) business_time,p.online_days,p.archive_target,p.auto_archive
            FROM dataset_record_workflow w JOIN data_dataset d ON d.id=w.dataset_id AND d.deleted=0
            JOIN LATERAL (SELECT p.online_days,p.archive_target,p.auto_archive FROM lifecycle_retention_policy p
                 WHERE p.active=TRUE AND p.importance_level=d.importance_level
                   AND (p.data_scope_id=d.data_scope_id OR p.data_scope_id IS NULL)
                 ORDER BY p.data_scope_id NULLS LAST LIMIT 1) p ON TRUE
            WHERE w.status='PUBLISHED' AND coalesce(w.published_time,w.record_created_time,w.updated_time)<now()-make_interval(days=>p.online_days)
              AND NOT EXISTS(SELECT 1 FROM lifecycle_hold h WHERE h.resource_type='DATASET_RECORD'
                  AND h.resource_ref=w.dataset_id||':'||w.record_id AND h.active=TRUE AND (h.valid_to IS NULL OR h.valid_to>now()))
              AND NOT EXISTS(SELECT 1 FROM lifecycle_archive_item i WHERE i.dataset_id=w.dataset_id AND i.record_id=w.record_id AND i.state IN ('ARCHIVING','ARCHIVED','RESTORING'))
              AND 
            """+scope+" ORDER BY business_time,w.dataset_id,w.record_id LIMIT :limit").param("limit",size);if(!user.admin()&&!user.assignedScopes().isEmpty())spec=spec.param("scopes",user.assignedScopes());return spec.query((rs,n)->{Map<String,Object> row=new LinkedHashMap<>();row.put("datasetId",rs.getLong("dataset_id"));row.put("recordId",rs.getString("record_id"));row.put("datasetName",rs.getString("dataset_name"));row.put("importanceLevel",rs.getString("importance_level"));row.put("dataScopeId",rs.getLong("data_scope_id"));row.put("businessTime",rs.getObject("business_time"));row.put("onlineDays",rs.getInt("online_days"));row.put("archiveTarget",rs.getString("archive_target"));row.put("autoArchive",rs.getBoolean("auto_archive"));return row;}).list();}

    public Map<String,Object> archive(long datasetId,String recordId){UserPrincipal user=CurrentUser.require();requirePermission(user,"lifecycle:archive");Map<String,Object> dataset=dataset(datasetId);scopes.require(((Number)dataset.get("dataScopeId")).longValue());return responseItem(archiveInternal(datasetId,recordId,"MANUAL",new Actor(user.id(),user.username()),null));}

    @Scheduled(initialDelayString="${rdp.lifecycle.auto-initial-delay-ms:120000}",fixedDelayString="${rdp.lifecycle.auto-delay-ms:3600000}")
    public void autoArchive(){List<RecordCandidate> candidates=autoCandidates(20);for(RecordCandidate candidate:candidates){try{archiveInternal(candidate.datasetId(),candidate.recordId(),"AUTO",new Actor(null,"system"),null);}catch(Exception ex){/* 作业与审计已记录失败，下一轮可重试。 */}}}

    public Map<String,Object> restore(long itemId){UserPrincipal user=CurrentUser.require();requirePermission(user,"lifecycle:restore");Map<String,Object> item=item(itemId);scopes.require(((Number)item.get("dataScopeId")).longValue());if(Boolean.TRUE.equals(item.get("cleanupPending"))){cleanupItem(itemId);item=item(itemId);if(Boolean.TRUE.equals(item.get("cleanupPending")))throw new BusinessException(409,"上一次转换仍在清理外部临时数据，请稍后恢复");}return responseItem(restoreInternal(item,new Actor(user.id(),user.username())));}

    public Map<String,Object> retry(long itemId){UserPrincipal user=CurrentUser.require();Map<String,Object> failed=item(itemId);if(!"FAILED".equals(failed.get("state")))throw BusinessException.badRequest("仅失败归档项可以重试");scopes.require(((Number)failed.get("dataScopeId")).longValue());if(Boolean.TRUE.equals(failed.get("cleanupPending"))){cleanupItem(itemId);failed=item(itemId);if(Boolean.TRUE.equals(failed.get("cleanupPending")))throw new BusinessException(409,"上一次转换仍在清理外部临时数据，请稍后重试");}Actor actor=new Actor(user.id(),user.username());if(failed.get("archivePath")!=null){requirePermission(user,"lifecycle:restore");return responseItem(restoreInternal(failed,actor));}requirePermission(user,"lifecycle:archive");return responseItem(archiveInternal(((Number)failed.get("datasetId")).longValue(),String.valueOf(failed.get("recordId")),"RETRY",actor,itemId));}

    public PageResponse<Map<String,Object>> items(String state,String keyword,int pageNum,int pageSize){int page=Math.max(1,pageNum),size=Math.max(1,Math.min(100,pageSize));String normalized=state==null||state.isBlank()?null:state.trim().toUpperCase(Locale.ROOT),term=keyword==null||keyword.isBlank()?null:keyword.trim();if(normalized!=null&&!Set.of("ARCHIVING","ARCHIVED","RESTORING","ONLINE","FAILED","SUPERSEDED").contains(normalized))throw BusinessException.badRequest("归档状态不正确");UserPrincipal user=CurrentUser.require();String scope=user.admin()?"TRUE":user.assignedScopes().isEmpty()?"FALSE":"i.data_scope_id IN (:scopes)";String where=" FROM lifecycle_archive_item i JOIN data_dataset d ON d.id=i.dataset_id WHERE (CAST(:state AS text) IS NULL OR i.state=CAST(:state AS text)) AND (CAST(:keyword AS text) IS NULL OR i.record_id ILIKE :like OR d.name ILIKE :like OR i.search_data::text ILIKE :like) AND "+scope;JdbcClient.StatementSpec count=jdbc.sql("SELECT count(*)"+where).param("state",normalized).param("keyword",term).param("like",term==null?null:"%"+term.replace("%","\\%").replace("_","\\_")+"%");JdbcClient.StatementSpec query=jdbc.sql("SELECT i.*,d.name dataset_name"+where+" ORDER BY i.updated_time DESC,i.id DESC LIMIT :limit OFFSET :offset").param("state",normalized).param("keyword",term).param("like",term==null?null:"%"+term.replace("%","\\%").replace("_","\\_")+"%").param("limit",size).param("offset",(page-1)*size);if(!user.admin()&&!user.assignedScopes().isEmpty()){count=count.param("scopes",user.assignedScopes());query=query.param("scopes",user.assignedScopes());}return PageResponse.of(count.query(Long.class).single(),page,size,query.query(this::itemRow).list().stream().map(this::responseItem).toList());}

    public List<Map<String,Object>> holds(){expireHolds();UserPrincipal user=CurrentUser.require();String scope=user.admin()?"TRUE":user.assignedScopes().isEmpty()?"FALSE":"d.data_scope_id IN (:scopes)";JdbcClient.StatementSpec query=jdbc.sql("SELECT h.*,d.name dataset_name FROM lifecycle_hold h JOIN data_dataset d ON d.id=split_part(h.resource_ref,':',1)::bigint WHERE "+scope+" ORDER BY h.active DESC,h.created_time DESC LIMIT 500");if(!user.admin()&&!user.assignedScopes().isEmpty())query=query.param("scopes",user.assignedScopes());return query.query(this::holdRow).list();}

    public long createHold(long datasetId,String recordId,String reason,Instant validTo){expireHolds();if(reason==null||reason.isBlank())throw BusinessException.badRequest("保留原因不能为空");Map<String,Object> dataset=dataset(datasetId);long scope=((Number)dataset.get("dataScopeId")).longValue();scopes.require(scope);objectId(recordId);if(validTo!=null&&!validTo.isAfter(Instant.now()))throw BusinessException.badRequest("保留结束时间必须晚于当前时间");UserPrincipal user=CurrentUser.require();try{return transactions.execute(status->{String current=jdbc.sql("SELECT status FROM dataset_record_workflow WHERE dataset_id=:dataset AND record_id=:record FOR UPDATE").param("dataset",datasetId).param("record",recordId).query(String.class).optional().orElseThrow(()->BusinessException.notFound("记录工作流不存在"));if(Set.of("DELETING","ARCHIVING","ARCHIVED","RESTORING").contains(current))throw BusinessException.badRequest("记录正在删除、归档或已归档，不能新建保留例外");long id=jdbc.sql("INSERT INTO lifecycle_hold(resource_ref,reason,valid_to,created_by) VALUES (:ref,:reason,:validTo,:actor) RETURNING id").param("ref",datasetId+":"+recordId).param("reason",reason.trim()).param("validTo",validTo==null?null:java.sql.Timestamp.from(validTo)).param("actor",user.id()).query(Long.class).single();audit.record("LIFECYCLE_HOLD","LIFECYCLE","创建数据保留例外",Map.of("holdId",id,"resourceRef",datasetId+":"+recordId,"reason",reason.trim()));return id;});}catch(BusinessException ex){throw ex;}catch(Exception ex){throw new BusinessException(409,"该记录已有生效保留例外");}}

    @Scheduled(initialDelayString="${rdp.lifecycle.hold-expire-initial-delay-ms:60000}",fixedDelayString="${rdp.lifecycle.hold-expire-delay-ms:60000}")
    public void expireHolds(){while(true){Integer changed=transactions.execute(status->{List<Map<String,Object>> due=jdbc.sql("SELECT id,resource_ref FROM lifecycle_hold WHERE active=TRUE AND valid_to IS NOT NULL AND valid_to<=now() ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 500").query((rs,n)->Map.<String,Object>of("id",rs.getLong("id"),"resourceRef",rs.getString("resource_ref"))).list();for(Map<String,Object> row:due){long id=((Number)row.get("id")).longValue();int updated=jdbc.sql("UPDATE lifecycle_hold SET active=FALSE,released_time=now(),release_reason='AUTO_EXPIRED',version=version+1 WHERE id=:id AND active=TRUE").param("id",id).update();if(updated==1)audit.recordAs(null,"system","LIFECYCLE_HOLD_EXPIRE","LIFECYCLE","数据保留例外到期自动解除",Map.of("holdId",id,"resourceRef",row.get("resourceRef")));}return due.size();});if(changed==null||changed==0)break;}}

    @Scheduled(initialDelayString="${rdp.lifecycle.reconcile-initial-delay-ms:180000}",fixedDelayString="${rdp.lifecycle.reconcile-delay-ms:300000}")
    public void reconcileStaleTransitions(){reconcileStale();}

    public Map<String,Integer> reconcileNow(){return reconcileStale();}

    private Map<String,Integer> reconcileStale(){
        List<Long> candidates=jdbc.sql("SELECT id FROM lifecycle_archive_item WHERE state IN ('ARCHIVING','RESTORING') AND updated_time<now()-make_interval(mins=>CAST(:minutes AS integer)) ORDER BY id LIMIT 500").param("minutes",staleTransitionMinutes).query(Long.class).list();
        int archiving=0,restoring=0;
        for(long id:candidates){
            StaleTransition recovered=transactions.execute(status->{
                StaleTransition locked=jdbc.sql("SELECT id,job_id,dataset_id,record_id,state,version FROM lifecycle_archive_item WHERE id=:id AND state IN ('ARCHIVING','RESTORING') AND updated_time<now()-make_interval(mins=>CAST(:minutes AS integer)) FOR UPDATE SKIP LOCKED").param("id",id).param("minutes",staleTransitionMinutes).query((rs,n)->new StaleTransition(rs.getLong("id"),rs.getLong("job_id"),rs.getLong("dataset_id"),rs.getString("record_id"),rs.getString("state"),rs.getInt("version"))).optional().orElse(null);
                if(locked==null)return null;
                if("ARCHIVING".equals(locked.state())){jdbc.sql("UPDATE dataset_record_workflow SET status='PUBLISHED',updated_time=now() WHERE dataset_id=:dataset AND record_id=:record AND status='ARCHIVING'").param("dataset",locked.datasetId()).param("record",locked.recordId()).update();jdbc.sql("UPDATE lifecycle_archive_item SET state='FAILED',error_message='STALE_ARCHIVING_RECOVERED',manifest=jsonb_set(manifest,'{failurePhase}','\"ARCHIVE_STALE\"'::jsonb,TRUE),archive_artifact_cleanup_pending=TRUE,retry_count=retry_count+1,version=version+1,updated_time=now() WHERE id=:id").param("id",id).update();failJob(locked.jobId(),"陈旧归档转换已安全回收");}
                else{jdbc.sql("UPDATE dataset_record_workflow SET status='ARCHIVED',updated_time=now() WHERE dataset_id=:dataset AND record_id=:record AND status='RESTORING'").param("dataset",locked.datasetId()).param("record",locked.recordId()).update();jdbc.sql("UPDATE lifecycle_archive_item SET state='FAILED',error_message='STALE_RESTORING_RECOVERED',manifest=jsonb_set(manifest,'{failurePhase}','\"RESTORE_STALE\"'::jsonb,TRUE),retry_count=retry_count+1,version=version+1,updated_time=now() WHERE id=:id").param("id",id).update();}
                audit.recordAs(null,"system","LIFECYCLE_STALE_RECOVER","LIFECYCLE","回收进程中断的生命周期转换",Map.of("archiveItemId",id,"phase",locked.state(),"datasetId",locked.datasetId(),"recordId",locked.recordId()));return locked;
            });
            if(recovered==null)continue;
            if("ARCHIVING".equals(recovered.state())){archiving++;try{mongo.updateFirst(Query.query(Criteria.where("_id").is(objectId(recovered.recordId())).and("archivedItemId").is(recovered.id()).and("archivedTransitionVersion").is(recovered.version())),new Update().unset("archived").unset("archivedItemId").unset("archivedTransitionVersion"),collection(recovered.datasetId()));}catch(Exception ignored){}}
            else{restoring++;try{mongo.remove(Query.query(Criteria.where("_id").is(objectId(recovered.recordId())).and("_restoreItemId").is(recovered.id()).and("_restoreVersion").is(recovered.version())),collection(recovered.datasetId()));gridFs.delete(Query.query(Criteria.where("metadata.restoredFromArchiveItem").is(recovered.id()).and("metadata.restoredTransitionVersion").is(recovered.version())));}catch(Exception ignored){}}
            cleanupItem(recovered.id());
        }
        return Map.of("recoveredArchiving",archiving,"recoveredRestoring",restoring,"completedCleanup",cleanupCommittedTransitions());
    }

    private int cleanupCommittedTransitions(){int cleaned=0;List<Long> pending=jdbc.sql("SELECT id FROM lifecycle_archive_item WHERE (external_cleanup_pending=TRUE OR archive_artifact_cleanup_pending=TRUE) AND state IN ('ARCHIVED','ONLINE','FAILED') ORDER BY updated_time,id LIMIT 500").query(Long.class).list();for(long id:pending)if(cleanupItem(id))cleaned++;return cleaned;}
    private boolean deleteAbandonedArchive(long datasetId,String recordId,long itemId){Path dir=archiveRoot.resolve(Long.toString(datasetId)).resolve(recordId).normalize();if(!dir.startsWith(archiveRoot))return false;try{Files.deleteIfExists(dir.resolve(itemId+".zip"));if(Files.isDirectory(dir))try(var files=Files.newDirectoryStream(dir,itemId+"-*.tmp")){for(Path file:files)Files.deleteIfExists(file);}return true;}catch(Exception ignored){return false;}}
    private boolean cleanupItem(long itemId){CompletedTransition item=jdbc.sql("SELECT id,dataset_id,record_id,state,version,archive_path IS NOT NULL restore_artifact,external_cleanup_pending,archive_artifact_cleanup_pending FROM lifecycle_archive_item WHERE id=:id").param("id",itemId).query((rs,n)->new CompletedTransition(rs.getLong("id"),rs.getLong("dataset_id"),rs.getString("record_id"),rs.getString("state"),rs.getInt("version"),rs.getBoolean("restore_artifact"),rs.getBoolean("external_cleanup_pending"),rs.getBoolean("archive_artifact_cleanup_pending"))).optional().orElse(null);if(item==null||!Set.of("ARCHIVED","ONLINE","FAILED").contains(item.state()))return false;try{if(item.artifactCleanupPending()&&!deleteAbandonedArchive(item.datasetId(),item.recordId(),item.id()))return false;if(item.externalCleanupPending()){int markerVersion=item.version()-1;if(markerVersion<1)return false;if("ONLINE".equals(item.state()))mongo.updateFirst(Query.query(Criteria.where("_id").is(objectId(item.recordId())).and("_restoreItemId").is(item.id()).and("_restoreVersion").is(markerVersion)),new Update().unset("archived").unset("_restoreItemId").unset("_restoreVersion"),collection(item.datasetId()));else if("ARCHIVED".equals(item.state()))mongo.remove(Query.query(Criteria.where("_id").is(objectId(item.recordId())).and("archivedItemId").is(item.id()).and("archivedTransitionVersion").is(markerVersion)),collection(item.datasetId()));else if(item.restoreArtifact())mongo.remove(Query.query(Criteria.where("_id").is(objectId(item.recordId())).and("_restoreItemId").is(item.id()).and("_restoreVersion").is(markerVersion)),collection(item.datasetId()));else mongo.updateFirst(Query.query(Criteria.where("_id").is(objectId(item.recordId())).and("archivedItemId").is(item.id()).and("archivedTransitionVersion").is(markerVersion)),new Update().unset("archived").unset("archivedItemId").unset("archivedTransitionVersion"),collection(item.datasetId()));}int changed=jdbc.sql("UPDATE lifecycle_archive_item SET external_cleanup_pending=FALSE,archive_artifact_cleanup_pending=FALSE,updated_time=now() WHERE id=:id AND state=:state AND version=:version AND (external_cleanup_pending=TRUE OR archive_artifact_cleanup_pending=TRUE)").param("id",item.id()).param("state",item.state()).param("version",item.version()).update();return changed==1;}catch(Exception ignored){return false;}}

    public void releaseHold(long id,int expectedVersion,String reason){if(reason==null||reason.isBlank())throw BusinessException.badRequest("解除原因不能为空");Map<String,Object> hold=jdbc.sql("SELECT * FROM lifecycle_hold WHERE id=:id").param("id",id).query(this::holdRowRaw).optional().orElseThrow(()->BusinessException.notFound("保留例外不存在"));String[] ref=String.valueOf(hold.get("resourceRef")).split(":",2);Map<String,Object> dataset=dataset(Long.parseLong(ref[0]));scopes.require(((Number)dataset.get("dataScopeId")).longValue());transactions.executeWithoutResult(status->{int changed=jdbc.sql("UPDATE lifecycle_hold SET active=FALSE,released_by=:actor,released_time=now(),release_reason=:reason,version=version+1 WHERE id=:id AND active=TRUE AND version=:version").param("actor",CurrentUser.require().id()).param("reason",reason.trim()).param("id",id).param("version",expectedVersion).update();if(changed==0)throw new BusinessException(409,"保留例外已解除或版本已变化");audit.record("LIFECYCLE_HOLD_RELEASE","LIFECYCLE","解除数据保留例外",Map.of("holdId",id,"resourceRef",hold.get("resourceRef"),"reason",reason.trim()));});}

    private Map<String,Object> archiveInternal(long datasetId,String recordId,String trigger,Actor actor,Long retryItemId){
        Map<String,Object> dataset=dataset(datasetId);long scope=((Number)dataset.get("dataScopeId")).longValue();objectId(recordId);
        long jobId=jdbc.sql("INSERT INTO lifecycle_archive_job(trigger_type,status,requested_by,requested_by_name,total_count) VALUES (:trigger,'RUNNING',:actor,:name,1) RETURNING id").param("trigger",trigger).param("actor",actor.id()).param("name",actor.name()).query(Long.class).single();
        ArchiveStart start;
        try{
            start=transactions.execute(status->{
                String previous=jdbc.sql("SELECT status FROM dataset_record_workflow WHERE dataset_id=:dataset AND record_id=:record FOR UPDATE").param("dataset",datasetId).param("record",recordId).query(String.class).optional().orElseThrow(()->BusinessException.notFound("记录工作流不存在"));
                if(!"PUBLISHED".equals(previous))throw BusinessException.badRequest("仅已发布在线记录可以归档");
                Policy selected=policyLocked(datasetId,recordId,"AUTO".equals(trigger));
                if(isHeld(datasetId,recordId))throw BusinessException.badRequest("该记录处于保留例外，不能归档");
                long created=jdbc.sql("INSERT INTO lifecycle_archive_item(job_id,dataset_id,record_id,data_scope_id,previous_status,state,archive_target,archived_by) VALUES (:job,:dataset,:record,:scope,:previous,'ARCHIVING',:target,:actor) RETURNING id").param("job",jobId).param("dataset",datasetId).param("record",recordId).param("scope",scope).param("previous",previous).param("target",selected.target()).param("actor",actor.id()).query(Long.class).single();
                if(retryItemId!=null){int superseded=jdbc.sql("UPDATE lifecycle_archive_item SET state='SUPERSEDED',external_cleanup_pending=FALSE,archive_artifact_cleanup_pending=FALSE,manifest=jsonb_set(manifest,'{retriedAs}',to_jsonb(CAST(:newId AS bigint)),TRUE),updated_time=now(),version=version+1 WHERE id=:id AND dataset_id=:dataset AND record_id=:record AND state='FAILED' AND archive_path IS NULL AND external_cleanup_pending=FALSE AND archive_artifact_cleanup_pending=FALSE").param("newId",created).param("id",retryItemId).param("dataset",datasetId).param("record",recordId).update();if(superseded!=1)throw new BusinessException(409,"失败归档项已变化，不能重复重试");}
                int locked=jdbc.sql("UPDATE dataset_record_workflow SET status='ARCHIVING',updated_time=now() WHERE dataset_id=:dataset AND record_id=:record AND status='PUBLISHED'").param("dataset",datasetId).param("record",recordId).update();if(locked!=1)throw new BusinessException(409,"记录状态已变化，归档已取消");
                return new ArchiveStart(created,selected,1);
            });
        }catch(BusinessException ex){failJob(jobId,message(ex));throw ex;}catch(Exception ex){failJob(jobId,"记录已有归档/恢复作业");throw new BusinessException(409,"记录已有归档或恢复作业");}
        long itemId=start.itemId();Policy policy=start.policy();int transitionVersion=start.version();
        Path path=null;boolean committed=false;try{
            Document record=mongo.findOne(Query.query(Criteria.where("_id").is(objectId(recordId)).and("deleted").ne(true).and("archived").ne(true)),Document.class,collection(datasetId));List<Map<String,Object>> files=fileRows(datasetId,recordId);
            if(record==null)throw BusinessException.notFound("在线记录不存在");
            ArchiveFile archive=writeArchive(itemId,transitionVersion,datasetId,recordId,record,files,policy);path=archive.path();
            heartbeatTransition(itemId,"ARCHIVING",transitionVersion);
            var marker=mongo.updateFirst(Query.query(Criteria.where("_id").is(objectId(recordId)).and("archived").ne(true)),new Update().set("archived",true).set("archivedItemId",itemId).set("archivedTransitionVersion",transitionVersion),collection(datasetId));if(marker.getModifiedCount()!=1)throw new BusinessException(409,"在线记录归档标记已变化，归档已取消");
            Path finalPath=path;transactions.executeWithoutResult(status->{
                jdbc.sql("SELECT 1 FROM lifecycle_archive_item WHERE id=:id AND state='ARCHIVING' AND version=:version FOR UPDATE").param("id",itemId).param("version",transitionVersion).query(Long.class).optional().orElseThrow(()->new BusinessException(409,"归档租约已失效，已取消提交"));
                jdbc.sql("SELECT 1 FROM dataset_record_workflow WHERE dataset_id=:dataset AND record_id=:record AND status='ARCHIVING' FOR UPDATE").param("dataset",datasetId).param("record",recordId).query(Long.class).optional().orElseThrow(()->new BusinessException(409,"记录状态已变化，归档已取消"));
                if(isHeld(datasetId,recordId))throw BusinessException.badRequest("记录新增了保留例外，归档已取消");
                List<Long> snapshotIds=files.stream().map(file->((Number)file.get("id")).longValue()).toList(),currentIds=fileRows(datasetId,recordId).stream().map(file->((Number)file.get("id")).longValue()).toList();if(!snapshotIds.equals(currentIds))throw new BusinessException(409,"归档期间附件集合发生变化，已取消归档");
                int workflowChanged=jdbc.sql("UPDATE dataset_record_workflow SET status='ARCHIVED',updated_time=now() WHERE dataset_id=:dataset AND record_id=:record AND status='ARCHIVING'").param("dataset",datasetId).param("record",recordId).update();
                if(workflowChanged!=1)throw new BusinessException(409,"记录状态已变化，归档已取消");
                if(!snapshotIds.isEmpty()){int archivedFiles=jdbc.sql("UPDATE file_asset SET status='ARCHIVED' WHERE id IN (:ids) AND status='AVAILABLE'").param("ids",snapshotIds).update();if(archivedFiles!=snapshotIds.size())throw new BusinessException(409,"归档期间附件状态发生变化，已取消归档");}
                jdbc.sql("UPDATE data_dataset SET data_count=greatest(data_count-1,0),updated_time=now() WHERE id=:dataset").param("dataset",datasetId).update();
                int itemChanged=jdbc.sql("UPDATE lifecycle_archive_item SET state='ARCHIVED',archive_path=:path,archive_digest=:digest,manifest=CAST(:manifest AS jsonb),search_data=CAST(:searchData AS jsonb),archived_time=now(),version=version+1,updated_time=now() WHERE id=:id AND state='ARCHIVING' AND version=:version").param("path",archiveRoot.relativize(finalPath).toString()).param("digest",archive.digest()).param("manifest",json.write(archive.manifest())).param("searchData",json.write(archive.searchData())).param("id",itemId).param("version",transitionVersion).update();if(itemChanged!=1)throw new BusinessException(409,"归档租约已失效，已取消提交");
                completeJob(jobId);recordAudit(actor,"ARCHIVE","数据记录已归档",Map.of("archiveItemId",itemId,"datasetId",datasetId,"recordId",recordId,"digest",archive.digest(),"target",policy.target(),"recordDigest",archive.manifest().get("recordDigest"),"workflowDigest",archive.manifest().get("workflowDigest"),"fileCount",archive.manifest().get("fileCount"),"totalPayloadBytes",archive.totalBytes()));
            });
            committed=true;
            // 权威状态、清单和审计已原子提交；此后的在线副本清理只能重试，绝不能反向删除唯一归档。
            cleanupItem(itemId);
            for(Map<String,Object> file:files)deleteGrid(file);
            return item(itemId);
        }catch(Exception ex){
            if(committed){try{return item(itemId);}catch(Exception ignored){throw new BusinessException(500,"归档已安全提交，但结果回读失败；请在归档清单中刷新查看");}}
            try{mongo.updateFirst(Query.query(Criteria.where("_id").is(objectId(recordId)).and("archivedItemId").is(itemId).and("archivedTransitionVersion").is(transitionVersion)),new Update().unset("archived").unset("archivedItemId").unset("archivedTransitionVersion"),collection(datasetId));}catch(Exception ignored){}
            transactions.executeWithoutResult(status->{boolean owns=jdbc.sql("SELECT 1 FROM lifecycle_archive_item WHERE id=:id AND state='ARCHIVING' AND version=:version FOR UPDATE").param("id",itemId).param("version",transitionVersion).query(Long.class).optional().isPresent();if(owns){jdbc.sql("UPDATE dataset_record_workflow SET status='PUBLISHED',updated_time=now() WHERE dataset_id=:dataset AND record_id=:record AND status='ARCHIVING'").param("dataset",datasetId).param("record",recordId).update();failItem(itemId,jobId,"ARCHIVE",message(ex),actor);}});cleanupItem(itemId);
            throw new BusinessException(503,"归档失败，原在线数据保持可用，可在生命周期中心重试");
        }}

    private Map<String,Object> restoreInternal(Map<String,Object> item,Actor actor){
        long itemId=((Number)item.get("id")).longValue(),datasetId=((Number)item.get("datasetId")).longValue();String recordId=String.valueOf(item.get("recordId"));
        if(!"ARCHIVED".equals(item.get("state"))&&!"FAILED".equals(item.get("state")))throw BusinessException.badRequest("仅已归档或恢复失败的记录可以恢复");
        if(item.get("archivePath")==null||item.get("archiveDigest")==null)throw BusinessException.badRequest("该失败项没有可恢复的归档文件，请重试归档");Path path=resolveArchive(String.valueOf(item.get("archivePath")));String expected=String.valueOf(item.get("archiveDigest"));
        if(!Files.isRegularFile(path)){String error="归档文件不存在，请检查备份挂载";failRestoreVerification(itemId,actor,error);throw new BusinessException(503,error);}
        transactions.executeWithoutResult(status->{int changed=jdbc.sql("UPDATE lifecycle_archive_item SET state='RESTORING',error_message=NULL,external_cleanup_pending=TRUE,version=version+1,updated_time=now() WHERE id=:id AND state IN ('ARCHIVED','FAILED') AND external_cleanup_pending=FALSE").param("id",itemId).update();if(changed==0)throw new BusinessException(409,"归档状态已变化或外部清理尚未完成");int workflowChanged=jdbc.sql("UPDATE dataset_record_workflow SET status='RESTORING',updated_time=now() WHERE dataset_id=:dataset AND record_id=:record AND status='ARCHIVED'").param("dataset",datasetId).param("record",recordId).update();if(workflowChanged!=1)throw new BusinessException(409,"记录归档状态已变化");});int transitionVersion=itemVersion(itemId);
        Path verifiedPath=null;List<RestoredFile> restored=new ArrayList<>();boolean committed=false;
        try{
            verifiedPath=Files.createTempFile("rdp-restore-"+itemId+"-",".zip");
            Files.copy(path,verifiedPath,StandardCopyOption.REPLACE_EXISTING);
            if(!expected.equals(digest(verifiedPath)))throw new IllegalStateException("归档摘要校验失败，已阻止恢复");
            try(ZipFile zip=new ZipFile(verifiedPath.toFile())){
            Map<String,Object> embeddedManifest=json.map(new String(zip.getInputStream(required(zip,"manifest.json")).readAllBytes(),java.nio.charset.StandardCharsets.UTF_8));if(!String.valueOf(itemId).equals(String.valueOf(embeddedManifest.get("archiveItemId")))||!(datasetId+":"+recordId).equals(String.valueOf(embeddedManifest.get("resourceRef"))))throw new IllegalStateException("归档内嵌清单与归档项不一致");
            byte[] workflowBytes=zip.getInputStream(required(zip,"workflow.json")).readAllBytes();Object expectedWorkflowDigest=embeddedManifest.get("workflowDigest");if(expectedWorkflowDigest==null||!String.valueOf(expectedWorkflowDigest).equalsIgnoreCase(sha256(workflowBytes)))throw new IllegalStateException("归档工作流摘要与清单不一致");Map<String,Object> archivedWorkflow=json.map(new String(workflowBytes,java.nio.charset.StandardCharsets.UTF_8));if(!String.valueOf(datasetId).equals(String.valueOf(archivedWorkflow.get("datasetId")))||!recordId.equals(String.valueOf(archivedWorkflow.get("recordId"))))throw new IllegalStateException("归档工作流快照与归档项不一致");
            byte[] recordBytes=zip.getInputStream(required(zip,"record.bson.json")).readAllBytes();Object expectedRecordDigest=embeddedManifest.get("recordDigest");if(expectedRecordDigest==null||!String.valueOf(expectedRecordDigest).equalsIgnoreCase(sha256(recordBytes)))throw new IllegalStateException("归档记录摘要与清单不一致");Document record=Document.parse(new String(recordBytes,java.nio.charset.StandardCharsets.UTF_8));record.put("_id",objectId(recordId));record.remove("archivedItemId");record.remove("archivedTransitionVersion");record.put("archived",true);record.put("_restoreItemId",itemId);record.put("_restoreVersion",transitionVersion);
            Document stale=mongo.findOne(Query.query(Criteria.where("_id").is(objectId(recordId))),Document.class,collection(datasetId));if(stale!=null){Number restoreItem=stale.get("_restoreItemId",Number.class),restoreVersion=stale.get("_restoreVersion",Number.class),archivedItem=stale.get("archivedItemId",Number.class);boolean priorRestore=restoreItem!=null&&restoreItem.longValue()==itemId&&restoreVersion!=null&&restoreVersion.intValue()<=transitionVersion,priorArchive=archivedItem!=null&&archivedItem.longValue()==itemId;if(!priorRestore&&!priorArchive)throw new BusinessException(409,"在线库已存在同ID记录，已阻止覆盖");mongo.remove(Query.query(Criteria.where("_id").is(objectId(recordId))),collection(datasetId));}mongo.insert(record,collection(datasetId));
            List<Map<String,Object>> manifestFiles=manifestFiles(embeddedManifest);validateFileManifest(fileManifest(item),manifestFiles);for(Map<String,Object> file:manifestFiles){long fileId=((Number)file.get("id")).longValue();String originalName=String.valueOf(file.get("originalName")),contentType=String.valueOf(file.get("contentType"));ZipEntry entry=required(zip,"attachments/"+fileId);ObjectId newId=null;try(VerifyingInputStream input=new VerifyingInputStream(zip.getInputStream(entry),itemId,"RESTORING",transitionVersion)){newId=gridFs.store(input,originalName,contentType,new Document("restoredFromArchiveItem",itemId).append("restoredTransitionVersion",transitionVersion));long expectedSize=((Number)file.get("sizeBytes")).longValue();String expectedFileDigest=String.valueOf(file.get("sha256"));if(input.count()!=expectedSize||!input.digestHex().equalsIgnoreCase(expectedFileDigest))throw new IllegalStateException("归档附件摘要校验失败 #"+fileId);restored.add(new RestoredFile(fileId,newId,expectedSize,expectedFileDigest,originalName,contentType));}catch(Exception ex){if(newId!=null)try{gridFs.delete(Query.query(Criteria.where("_id").is(newId)));}catch(Exception ignored){}throw ex;}}
            if(!expected.equals(digest(verifiedPath)))throw new IllegalStateException("恢复读取期间归档快照发生变化，已阻止提交");
            transactions.executeWithoutResult(status->{
                jdbc.sql("SELECT 1 FROM lifecycle_archive_item WHERE id=:id AND state='RESTORING' AND version=:version FOR UPDATE").param("id",itemId).param("version",transitionVersion).query(Long.class).optional().orElseThrow(()->new BusinessException(409,"恢复租约已失效，已取消提交"));
                for(RestoredFile file:restored){int fileChanged=jdbc.sql("UPDATE file_asset SET gridfs_id=:grid,status='AVAILABLE' WHERE id=:id AND business_type='DATASET_RECORD' AND business_ref=:ref AND status='ARCHIVED' AND size_bytes=:size AND lower(sha256)=lower(:sha) AND original_name=:name AND content_type=:contentType").param("grid",file.gridId().toHexString()).param("id",file.fileId()).param("ref",datasetId+":"+recordId).param("size",file.size()).param("sha",file.sha256()).param("name",file.originalName()).param("contentType",file.contentType()).update();if(fileChanged!=1)throw new BusinessException(409,"归档附件元数据已变化，恢复已取消");}
                int workflowChanged=jdbc.sql("UPDATE dataset_record_workflow SET status=:status,updated_time=now() WHERE dataset_id=:dataset AND record_id=:record AND status='RESTORING'").param("status",item.get("previousStatus")).param("dataset",datasetId).param("record",recordId).update();if(workflowChanged!=1)throw new BusinessException(409,"记录恢复状态已变化，恢复已取消");
                jdbc.sql("UPDATE data_dataset SET data_count=data_count+1,updated_time=now() WHERE id=:dataset").param("dataset",datasetId).update();
                int itemChanged=jdbc.sql("UPDATE lifecycle_archive_item SET state='ONLINE',restored_by=:actor,restored_time=now(),version=version+1,updated_time=now() WHERE id=:id AND state='RESTORING' AND version=:version").param("actor",actor.id()).param("id",itemId).param("version",transitionVersion).update();if(itemChanged!=1)throw new BusinessException(409,"恢复租约已失效，已取消提交");
                recordAudit(actor,"RESTORE","归档记录已恢复到在线存储",Map.of("archiveItemId",itemId,"datasetId",datasetId,"recordId",recordId,"verifiedDigest",expected));
            });
            committed=true;
            cleanupItem(itemId);
            return item(itemId);}
        }catch(Exception ex){
            if(committed){try{return item(itemId);}catch(Exception ignored){throw new BusinessException(500,"恢复已安全提交，但结果回读失败；请刷新归档清单");}}
            try{mongo.remove(Query.query(Criteria.where("_id").is(objectId(recordId)).and("_restoreItemId").is(itemId).and("_restoreVersion").is(transitionVersion)),collection(datasetId));for(RestoredFile file:restored)gridFs.delete(Query.query(Criteria.where("_id").is(file.gridId()).and("metadata.restoredFromArchiveItem").is(itemId).and("metadata.restoredTransitionVersion").is(transitionVersion)));}catch(Exception ignored){}
            transactions.execute(status->{boolean leased=jdbc.sql("SELECT 1 FROM lifecycle_archive_item WHERE id=:id AND state='RESTORING' AND version=:version FOR UPDATE").param("id",itemId).param("version",transitionVersion).query(Long.class).optional().isPresent();if(!leased)return false;jdbc.sql("UPDATE dataset_record_workflow SET status='ARCHIVED',updated_time=now() WHERE dataset_id=:dataset AND record_id=:record AND status='RESTORING'").param("dataset",datasetId).param("record",recordId).update();int failed=jdbc.sql("UPDATE lifecycle_archive_item SET state='FAILED',error_message=:error,retry_count=retry_count+1,version=version+1,updated_time=now() WHERE id=:id AND state='RESTORING' AND version=:version").param("error",message(ex)).param("id",itemId).param("version",transitionVersion).update();if(failed==1)recordAudit(actor,"RESTORE_FAILED","归档恢复失败",Map.of("archiveItemId",itemId,"error",message(ex)));return failed==1;});cleanupItem(itemId);
            throw new BusinessException(503,"恢复失败，归档文件保持不变，可重试");
        }finally{if(verifiedPath!=null)try{Files.deleteIfExists(verifiedPath);}catch(Exception ignored){}}}

    private ArchiveFile writeArchive(long itemId,int transitionVersion,long datasetId,String recordId,Document record,List<Map<String,Object>> files,Policy policy)throws Exception{
        Path dir=archiveRoot.resolve(Long.toString(datasetId)).resolve(recordId);Files.createDirectories(dir);Path target=dir.resolve(itemId+".zip"),temp=Files.createTempFile(dir,itemId+"-",".tmp");boolean completed=false;
        Map<String,Object> manifest=new LinkedHashMap<>();manifest.put("formatVersion",1);manifest.put("resourceType","DATASET_RECORD");manifest.put("resourceRef",datasetId+":"+recordId);manifest.put("archiveItemId",itemId);manifest.put("transitionVersion",transitionVersion);manifest.put("archiveTarget",policy.target());manifest.put("createdTime",Instant.now().toString());Map<String,Object> workflow=workflowSnapshot(datasetId,recordId),searchData=recordSearchData(record);workflow.put("searchData",searchData);workflow.put("searchProjectionReady",true);byte[] recordBytes=record.toJson().getBytes(java.nio.charset.StandardCharsets.UTF_8),workflowBytes=json.write(workflow).getBytes(java.nio.charset.StandardCharsets.UTF_8);manifest.put("recordDigest",sha256(recordBytes));manifest.put("workflowDigest",sha256(workflowBytes));List<Map<String,Object>> manifestFiles=new ArrayList<>();long totalBytes=recordBytes.length+workflowBytes.length;
        try{
            try(OutputStream raw=Files.newOutputStream(temp,StandardOpenOption.TRUNCATE_EXISTING);ZipOutputStream zip=new ZipOutputStream(new BufferedOutputStream(raw))){
                writeEntry(zip,"record.bson.json",recordBytes);writeEntry(zip,"workflow.json",workflowBytes);heartbeatTransition(itemId,"ARCHIVING",transitionVersion);
                for(Map<String,Object> file:files){
                    GridFSFile stored=gridFs.findOne(Query.query(Criteria.where("_id").is(new ObjectId(String.valueOf(file.get("gridFsId"))))));if(stored==null)throw new IllegalStateException("附件内容缺失 #"+file.get("id"));
                    ZipEntry entry=new ZipEntry("attachments/"+file.get("id"));zip.putNextEntry(entry);FileDigest actual;
                    try(InputStream input=new BufferedInputStream(gridFs.getResource(stored).getInputStream())){actual=copyVerified(input,zip,itemId,"ARCHIVING",transitionVersion);}finally{zip.closeEntry();}
                    long expectedSize=((Number)file.get("sizeBytes")).longValue();String expectedDigest=String.valueOf(file.get("sha256"));if(actual.size()!=expectedSize||!actual.sha256().equalsIgnoreCase(expectedDigest))throw new IllegalStateException("附件内容与元数据摘要不一致 #"+file.get("id"));
                    Map<String,Object> info=new LinkedHashMap<>();info.put("id",file.get("id"));info.put("originalName",file.get("originalName"));info.put("contentType",file.get("contentType"));info.put("sizeBytes",actual.size());info.put("sha256",actual.sha256());manifestFiles.add(info);totalBytes+=actual.size();
                }
                manifest.put("files",manifestFiles);manifest.put("fileCount",manifestFiles.size());manifest.put("totalPayloadBytes",totalBytes);writeEntry(zip,"manifest.json",json.write(manifest).getBytes(java.nio.charset.StandardCharsets.UTF_8));
            }
            try{Files.move(temp,target,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(java.nio.file.AtomicMoveNotSupportedException ex){Files.move(temp,target,StandardCopyOption.REPLACE_EXISTING);}String archiveDigest=digestWithHeartbeat(target,itemId,"ARCHIVING",transitionVersion);if(archiveDigest.isBlank())throw new IllegalStateException("归档摘要生成失败");completed=true;return new ArchiveFile(target,archiveDigest,manifest,totalBytes,searchData);
        }finally{if(!completed){try{Files.deleteIfExists(temp);}catch(IOException ignored){}try{Files.deleteIfExists(target);}catch(IOException ignored){}}}
    }

    private FileDigest copyVerified(InputStream input,OutputStream output,long itemId,String state,int version)throws Exception{MessageDigest digest=MessageDigest.getInstance("SHA-256");byte[] buffer=new byte[64*1024];long count=0,nextHeartbeat=System.nanoTime()+30_000_000_000L;for(int read;(read=input.read(buffer))!=-1;){output.write(buffer,0,read);digest.update(buffer,0,read);count+=read;if(System.nanoTime()>=nextHeartbeat){heartbeatTransition(itemId,state,version);nextHeartbeat=System.nanoTime()+30_000_000_000L;}}heartbeatTransition(itemId,state,version);return new FileDigest(count,HexFormat.of().formatHex(digest.digest()));}

    private void writeEntry(ZipOutputStream zip,String name,byte[] bytes)throws IOException{zip.putNextEntry(new ZipEntry(name));zip.write(bytes);zip.closeEntry();}
    private ZipEntry required(ZipFile zip,String name){ZipEntry entry=zip.getEntry(name);if(entry==null)throw new IllegalStateException("归档清单缺少 "+name);return entry;}
    private Path resolveArchive(String relative){Path resolved=archiveRoot.resolve(relative).normalize();if(!resolved.startsWith(archiveRoot))throw new BusinessException(500,"归档路径越界");return resolved;}
    private String digest(Path path){try(InputStream input=Files.newInputStream(path);DigestInputStream signed=new DigestInputStream(input,MessageDigest.getInstance("SHA-256"))){signed.transferTo(OutputStream.nullOutputStream());return HexFormat.of().formatHex(signed.getMessageDigest().digest());}catch(Exception ex){throw new IllegalStateException("归档摘要读取失败",ex);}}
    private String digestWithHeartbeat(Path path,long itemId,String state,int version)throws Exception{MessageDigest hash=MessageDigest.getInstance("SHA-256");byte[] buffer=new byte[64*1024];long nextHeartbeat=System.nanoTime()+30_000_000_000L;try(InputStream input=Files.newInputStream(path)){for(int read;(read=input.read(buffer))!=-1;){hash.update(buffer,0,read);if(System.nanoTime()>=nextHeartbeat){heartbeatTransition(itemId,state,version);nextHeartbeat=System.nanoTime()+30_000_000_000L;}}}heartbeatTransition(itemId,state,version);return HexFormat.of().formatHex(hash.digest());}
    private String sha256(byte[] bytes){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}catch(Exception ex){throw new IllegalStateException(ex);}}
    private void verifyArchiveTarget(){try{Files.createDirectories(archiveRoot);Path probe=Files.createTempFile(archiveRoot,"rdp-archive-health-",".tmp");Files.writeString(probe,"ok",StandardOpenOption.TRUNCATE_EXISTING);Files.delete(probe);}catch(Exception ex){throw new BusinessException(503,"归档目标不可写，禁止启用自动归档");}}
    private int itemVersion(long itemId){return jdbc.sql("SELECT version FROM lifecycle_archive_item WHERE id=:id").param("id",itemId).query(Integer.class).single();}
    private void heartbeatTransition(long itemId,String state,int version){int touched=jdbc.sql("UPDATE lifecycle_archive_item SET updated_time=now() WHERE id=:id AND state=:state AND version=:version").param("id",itemId).param("state",state).param("version",version).update();if(touched!=1)throw new IllegalStateException("生命周期转换租约已失效");}
    private void deleteGrid(Map<String,Object> file){try{gridFs.delete(Query.query(Criteria.where("_id").is(new ObjectId(String.valueOf(file.get("gridFsId"))))));}catch(Exception ignored){}}
    private void completeJob(long id){jdbc.sql("UPDATE lifecycle_archive_job SET status='COMPLETED',success_count=1,finished_time=now() WHERE id=:id").param("id",id).update();}
    private void failJob(long id,String error){jdbc.sql("UPDATE lifecycle_archive_job SET status='FAILED',failure_count=1,error_message=:error,finished_time=now() WHERE id=:id").param("error",error).param("id",id).update();}
    private void failItem(long itemId,long jobId,String phase,String error,Actor actor){jdbc.sql("UPDATE lifecycle_archive_item SET state='FAILED',error_message=:error,retry_count=retry_count+1,manifest=jsonb_build_object('failurePhase',:phase),archive_artifact_cleanup_pending=CASE WHEN :phase LIKE 'ARCHIVE%' THEN TRUE ELSE archive_artifact_cleanup_pending END,version=version+1,updated_time=now() WHERE id=:id").param("error",error).param("phase",phase).param("id",itemId).update();failJob(jobId,error);try{recordAudit(actor,"ARCHIVE_FAILED","数据归档失败",Map.of("archiveItemId",itemId,"error",error));}catch(Exception ignored){}}
    private void failRestoreVerification(long itemId,Actor actor,String error){transactions.executeWithoutResult(status->{jdbc.sql("UPDATE lifecycle_archive_item SET state='FAILED',error_message=:error,manifest=jsonb_set(manifest,'{failurePhase}','\"RESTORE_VERIFY\"'::jsonb,TRUE),retry_count=retry_count+1,version=version+1,updated_time=now() WHERE id=:id AND state IN ('ARCHIVED','FAILED')").param("error",error).param("id",itemId).update();recordAudit(actor,"RESTORE_FAILED","归档恢复校验失败",Map.of("archiveItemId",itemId,"error",error));});}
    private void recordAudit(Actor actor,String operation,String description,Map<String,Object> details){if(actor.id()==null)audit.recordAs(null,actor.name(),operation,"LIFECYCLE",description,details);else audit.record(operation,"LIFECYCLE",description,details);}
    private boolean isHeld(long datasetId,String recordId){return jdbc.sql("SELECT count(*) FROM lifecycle_hold WHERE resource_type='DATASET_RECORD' AND resource_ref=:ref AND active=TRUE AND (valid_to IS NULL OR valid_to>now())").param("ref",datasetId+":"+recordId).query(Long.class).single()>0;}
    private Policy policyLocked(long datasetId,String recordId,boolean automatic){Map<String,Object> current=jdbc.sql("SELECT d.data_scope_id,d.importance_level FROM data_dataset d JOIN sys_data_scope s ON s.id=d.data_scope_id AND s.active=TRUE WHERE d.id=:dataset AND d.deleted=0 FOR SHARE OF d,s").param("dataset",datasetId).query((rs,n)->Map.<String,Object>of("scope",rs.getLong("data_scope_id"),"importance",rs.getString("importance_level"))).optional().orElseThrow(()->BusinessException.badRequest("数据集或数据域已停用"));Policy selected=jdbc.sql("SELECT archive_target,online_days,auto_archive FROM lifecycle_retention_policy WHERE active=TRUE AND importance_level=:importance AND (data_scope_id=:scope OR data_scope_id IS NULL) ORDER BY data_scope_id NULLS LAST LIMIT 1 FOR SHARE").param("importance",current.get("importance")).param("scope",current.get("scope")).query((rs,n)->new Policy(rs.getString("archive_target"),rs.getInt("online_days"),rs.getBoolean("auto_archive"))).optional().orElseThrow(()->BusinessException.badRequest("未配置适用的生命周期策略"));if(automatic){if(!selected.autoArchive())throw BusinessException.badRequest("当前数据域策略已关闭自动归档");long due=jdbc.sql("SELECT count(*) FROM dataset_record_workflow WHERE dataset_id=:dataset AND record_id=:record AND status='PUBLISHED' AND coalesce(published_time,record_created_time,updated_time)<now()-make_interval(days=>:days)").param("dataset",datasetId).param("record",recordId).param("days",selected.onlineDays()).query(Long.class).single();if(due!=1)throw BusinessException.badRequest("记录按当前策略尚未到期");}return selected;}
    private String workflow(long datasetId,String recordId){if(!ObjectId.isValid(recordId))throw BusinessException.badRequest("记录ID不正确");return jdbc.sql("SELECT status FROM dataset_record_workflow WHERE dataset_id=:dataset AND record_id=:record").param("dataset",datasetId).param("record",recordId).query(String.class).optional().orElseThrow(()->BusinessException.notFound("记录工作流不存在"));}
    private Map<String,Object> dataset(long id){return jdbc.sql("SELECT id,name,data_scope_id,importance_level FROM data_dataset WHERE id=:id AND deleted=0").param("id",id).query((rs,n)->Map.<String,Object>of("id",rs.getLong("id"),"name",rs.getString("name"),"dataScopeId",rs.getLong("data_scope_id"),"importanceLevel",rs.getString("importance_level"))).optional().orElseThrow(()->BusinessException.notFound("数据集不存在"));}
    private Map<String,Object> item(long id){return jdbc.sql("SELECT i.*,d.name dataset_name FROM lifecycle_archive_item i JOIN data_dataset d ON d.id=i.dataset_id WHERE i.id=:id").param("id",id).query(this::itemRow).optional().orElseThrow(()->BusinessException.notFound("归档项不存在"));}
    private List<Map<String,Object>> fileRows(long datasetId,String recordId){return jdbc.sql("SELECT id,original_name,content_type,size_bytes,sha256,gridfs_id FROM file_asset WHERE business_type='DATASET_RECORD' AND business_ref=:ref AND status='AVAILABLE' ORDER BY id").param("ref",datasetId+":"+recordId).query((rs,n)->{Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getLong("id"));row.put("originalName",rs.getString("original_name"));row.put("contentType",rs.getString("content_type"));row.put("sizeBytes",rs.getLong("size_bytes"));row.put("sha256",rs.getString("sha256"));row.put("gridFsId",rs.getString("gridfs_id"));return row;}).list();}
    private Map<String,Object> workflowSnapshot(long datasetId,String recordId){Map<String,Object> snapshot=jdbc.sql("""
            SELECT record_version,owner_id,status,submitted_by,submitted_time,reviewed_by,reviewed_time,
                   review_comment,published_by,published_time,updated_time,record_created_time,
                   record_updated_time,search_data,search_projection_ready
            FROM dataset_record_workflow WHERE dataset_id=:dataset AND record_id=:record
            """).param("dataset",datasetId).param("record",recordId).query((rs,n)->{Map<String,Object> row=new LinkedHashMap<>();row.put("datasetId",datasetId);row.put("recordId",recordId);row.put("recordVersion",rs.getInt("record_version"));row.put("ownerId",rs.getLong("owner_id"));row.put("transitionStatus",rs.getString("status"));row.put("archivedFromStatus","PUBLISHED");row.put("submittedBy",rs.getObject("submitted_by"));row.put("submittedTime",rs.getObject("submitted_time"));row.put("reviewedBy",rs.getObject("reviewed_by"));row.put("reviewedTime",rs.getObject("reviewed_time"));row.put("reviewComment",rs.getString("review_comment"));row.put("publishedBy",rs.getObject("published_by"));row.put("publishedTime",rs.getObject("published_time"));row.put("updatedTime",rs.getObject("updated_time"));row.put("recordCreatedTime",rs.getObject("record_created_time"));row.put("recordUpdatedTime",rs.getObject("record_updated_time"));row.put("searchData",json.map(rs.getString("search_data")));row.put("searchProjectionReady",rs.getBoolean("search_projection_ready"));return row;}).optional().orElseThrow(()->BusinessException.notFound("记录工作流不存在"));
        List<Map<String,Object>> signatures=jdbc.sql("""
            SELECT id,target_version,signer_id,signer_username,meaning,reason,signed_payload,evidence_digest,signature_key_id,signature_ip,signed_time
            FROM electronic_signature WHERE target_type='DATASET_RECORD' AND target_id=:target ORDER BY id
            """).param("target",datasetId+":"+recordId).query((rs,n)->{Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getLong("id"));row.put("targetVersion",rs.getInt("target_version"));row.put("signerId",rs.getLong("signer_id"));row.put("signerUsername",rs.getString("signer_username"));row.put("meaning",rs.getString("meaning"));row.put("reason",rs.getString("reason"));row.put("signedPayload",rs.getString("signed_payload"));row.put("evidenceDigest",rs.getString("evidence_digest"));row.put("signatureKeyId",rs.getString("signature_key_id"));row.put("signatureIp",rs.getString("signature_ip"));row.put("signedTime",rs.getObject("signed_time"));return row;}).list();snapshot.put("electronicSignatures",signatures);return snapshot;}
    @SuppressWarnings("unchecked") private Map<String,Object> recordSearchData(Document record){Object raw=record.get("data");if(raw instanceof Document document)return new LinkedHashMap<>(document);if(raw instanceof Map<?,?> map)return new LinkedHashMap<>((Map<String,Object>)map);return Map.of();}
    private Map<String,Object> responseItem(Map<String,Object> raw){Map<String,Object> result=new LinkedHashMap<>(raw);Object manifest=result.remove("manifest");if(manifest instanceof Map<?,?> map){Map<String,Object> summary=new LinkedHashMap<>();for(String key:List.of("formatVersion","resourceType","resourceRef","archiveItemId","transitionVersion","archiveTarget","createdTime","recordDigest","workflowDigest","fileCount","totalPayloadBytes"))if(map.containsKey(key))summary.put(key,map.get(key));result.put("manifestSummary",summary);}result.remove("cleanupPending");return result;}
    private Map<String,Object> policySnapshot(long id){return jdbc.sql("SELECT importance_level,data_scope_id,online_days,archive_target,auto_archive,active,version FROM lifecycle_retention_policy WHERE id=:id").param("id",id).query((rs,n)->{Map<String,Object> row=new LinkedHashMap<>();row.put("importanceLevel",rs.getString("importance_level"));row.put("dataScopeId",rs.getObject("data_scope_id"));row.put("onlineDays",rs.getInt("online_days"));row.put("archiveTarget",rs.getString("archive_target"));row.put("autoArchive",rs.getBoolean("auto_archive"));row.put("active",rs.getBoolean("active"));row.put("version",rs.getInt("version"));return row;}).single();}
    @SuppressWarnings("unchecked") private List<Map<String,Object>> fileManifest(Map<String,Object> item){Object raw=item.get("manifest");if(raw instanceof Map<?,?> map&&map.get("files") instanceof List<?> files)return (List<Map<String,Object>>)(List<?>)files;return List.of();}
    @SuppressWarnings("unchecked") private List<Map<String,Object>> manifestFiles(Map<String,Object> manifest){Object raw=manifest.get("files");if(raw instanceof List<?> files)return (List<Map<String,Object>>)(List<?>)files;return List.of();}
    private void validateFileManifest(List<Map<String,Object>> expected,List<Map<String,Object>> actual){Map<Long,FileManifestSpec> left=manifestIndex(expected),right=manifestIndex(actual);if(!left.equals(right))throw new IllegalStateException("归档内嵌附件清单与数据库清单不一致");}
    private Map<Long,FileManifestSpec> manifestIndex(List<Map<String,Object>> rows){Map<Long,FileManifestSpec> result=new LinkedHashMap<>();for(Map<String,Object> row:rows){Object rawId=row.get("id"),rawSize=row.get("sizeBytes");if(!(rawId instanceof Number id)||!(rawSize instanceof Number size))throw new IllegalStateException("归档附件清单字段不完整");FileManifestSpec value=new FileManifestSpec(String.valueOf(row.get("originalName")),String.valueOf(row.get("contentType")),size.longValue(),String.valueOf(row.get("sha256")).toLowerCase(Locale.ROOT));if(result.put(id.longValue(),value)!=null)throw new IllegalStateException("归档附件清单包含重复ID");}return result;}
    private List<RecordCandidate> autoCandidates(int limit){return jdbc.sql("""
            SELECT w.dataset_id,w.record_id FROM dataset_record_workflow w JOIN data_dataset d ON d.id=w.dataset_id AND d.deleted=0 JOIN sys_data_scope s ON s.id=d.data_scope_id AND s.active=TRUE
            JOIN LATERAL (SELECT p.online_days,p.auto_archive FROM lifecycle_retention_policy p WHERE p.active=TRUE
                AND p.importance_level=d.importance_level AND (p.data_scope_id=d.data_scope_id OR p.data_scope_id IS NULL)
                ORDER BY p.data_scope_id NULLS LAST LIMIT 1) p ON TRUE
            WHERE w.status='PUBLISHED' AND p.auto_archive=TRUE AND coalesce(w.published_time,w.record_created_time,w.updated_time)<now()-make_interval(days=>p.online_days)
              AND NOT EXISTS(SELECT 1 FROM lifecycle_hold h WHERE h.resource_ref=w.dataset_id||':'||w.record_id AND h.active=TRUE AND (h.valid_to IS NULL OR h.valid_to>now()))
              AND NOT EXISTS(SELECT 1 FROM lifecycle_archive_item i WHERE i.dataset_id=w.dataset_id AND i.record_id=w.record_id AND i.state IN ('ARCHIVING','ARCHIVED','RESTORING'))
            ORDER BY coalesce(w.published_time,w.record_created_time,w.updated_time) LIMIT :limit
            """).param("limit",limit).query((rs,n)->new RecordCandidate(rs.getLong("dataset_id"),rs.getString("record_id"))).list();}
    private String collection(long datasetId){return "dataset_data_"+datasetId;}
    private ObjectId objectId(String value){try{return new ObjectId(value);}catch(Exception ex){throw BusinessException.badRequest("记录ID不正确");}}
    private void authorizePolicyScope(UserPrincipal user,Long scopeId){if(scopeId==null){if(!user.admin())throw BusinessException.forbidden("仅管理员可维护全局生命周期策略");return;}scopes.require(scopeId);}
    private void requirePermission(UserPrincipal user,String permission){if(!user.admin()&&!user.permissions().contains(permission))throw BusinessException.forbidden("缺少生命周期操作权限");}
    private String normalizeImportance(String value){String normalized=value==null?"":value.trim().toUpperCase(Locale.ROOT);if(!IMPORTANCE.contains(normalized))throw BusinessException.badRequest("重要性级别不正确");return dictionaries.requireEnabled("DATA_IMPORTANCE",normalized,"数据重要性");}
    private String message(Exception ex){String value=ex.getMessage()==null?ex.getClass().getSimpleName():ex.getMessage();return value.substring(0,Math.min(value.length(),2000));}
    private Map<String,Object> policyRow(ResultSet rs,int n)throws SQLException{Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getLong("id"));row.put("resourceType",rs.getString("resource_type"));row.put("importanceLevel",rs.getString("importance_level"));row.put("dataScopeId",rs.getObject("data_scope_id"));row.put("dataScopeName",rs.getString("scope_name"));row.put("onlineDays",rs.getInt("online_days"));row.put("archiveTarget",rs.getString("archive_target"));row.put("autoArchive",rs.getBoolean("auto_archive"));row.put("active",rs.getBoolean("active"));row.put("version",rs.getInt("version"));row.put("createdUsername",rs.getString("created_username"));row.put("updatedUsername",rs.getString("updated_username"));row.put("createdTime",rs.getObject("created_time"));row.put("updatedTime",rs.getObject("updated_time"));return row;}
    private Map<String,Object> itemRow(ResultSet rs,int n)throws SQLException{Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getLong("id"));row.put("jobId",rs.getLong("job_id"));row.put("datasetId",rs.getLong("dataset_id"));row.put("datasetName",rs.getString("dataset_name"));row.put("recordId",rs.getString("record_id"));row.put("dataScopeId",rs.getLong("data_scope_id"));row.put("previousStatus",rs.getString("previous_status"));String state=rs.getString("state");row.put("state",state);row.put("archiveTarget",rs.getString("archive_target"));String archivePath=rs.getString("archive_path");row.put("archivePath",archivePath);row.put("retryOperation","SUPERSEDED".equals(state)?null:archivePath==null?"ARCHIVE":"RESTORE");row.put("archiveDigest",rs.getString("archive_digest"));row.put("manifest",json.map(rs.getString("manifest")));row.put("errorMessage",rs.getString("error_message"));row.put("archivedTime",rs.getObject("archived_time"));row.put("restoredTime",rs.getObject("restored_time"));row.put("retryCount",rs.getInt("retry_count"));row.put("cleanupPending",rs.getBoolean("external_cleanup_pending")||rs.getBoolean("archive_artifact_cleanup_pending"));row.put("version",rs.getInt("version"));row.put("updatedTime",rs.getObject("updated_time"));return row;}
    private Map<String,Object> holdRow(ResultSet rs,int n)throws SQLException{Map<String,Object> row=holdRowRaw(rs,n);row.put("datasetName",rs.getString("dataset_name"));return row;}
    private Map<String,Object> holdRowRaw(ResultSet rs,int n)throws SQLException{Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getLong("id"));row.put("resourceRef",rs.getString("resource_ref"));row.put("reason",rs.getString("reason"));row.put("validTo",rs.getObject("valid_to"));row.put("active",rs.getBoolean("active"));row.put("createdBy",rs.getLong("created_by"));row.put("createdTime",rs.getObject("created_time"));row.put("releasedBy",rs.getObject("released_by"));row.put("releasedTime",rs.getObject("released_time"));row.put("releaseReason",rs.getString("release_reason"));row.put("version",rs.getInt("version"));return row;}
    private record Actor(Long id,String name){} private record Policy(String target,int onlineDays,boolean autoArchive){} private record PolicyScope(Long scopeId){} private record ArchiveStart(long itemId,Policy policy,int version){}
    private final class VerifyingInputStream extends FilterInputStream{private final long itemId;private final String state;private final int version;private final MessageDigest digest;private long count,nextHeartbeat=System.nanoTime()+30_000_000_000L;private String digestHex;private VerifyingInputStream(InputStream input,long itemId,String state,int version)throws Exception{super(input);this.itemId=itemId;this.state=state;this.version=version;this.digest=MessageDigest.getInstance("SHA-256");heartbeat();}private void accepted(byte[] bytes,int offset,int length)throws IOException{if(length<=0)return;digest.update(bytes,offset,length);count+=length;if(System.nanoTime()>=nextHeartbeat)heartbeat();}private void heartbeat()throws IOException{try{heartbeatTransition(itemId,state,version);nextHeartbeat=System.nanoTime()+30_000_000_000L;}catch(Exception ex){throw new IOException("生命周期转换租约已失效",ex);}}@Override public int read()throws IOException{int value=in.read();if(value>=0){byte[] one={(byte)value};accepted(one,0,1);}return value;}@Override public int read(byte[] bytes,int offset,int length)throws IOException{int read=in.read(bytes,offset,length);accepted(bytes,offset,read);return read;}private long count(){return count;}private String digestHex(){if(digestHex==null)digestHex=HexFormat.of().formatHex(digest.digest());return digestHex;}}
    private record RecordCandidate(long datasetId,String recordId){} private record RestoredFile(long fileId,ObjectId gridId,long size,String sha256,String originalName,String contentType){} private record FileManifestSpec(String originalName,String contentType,long size,String sha256){} private record StaleTransition(long id,long jobId,long datasetId,String recordId,String state,int version){} private record CompletedTransition(long id,long datasetId,String recordId,String state,int version,boolean restoreArtifact,boolean externalCleanupPending,boolean artifactCleanupPending){} private record FileDigest(long size,String sha256){}
    private record ArchiveFile(Path path,String digest,Map<String,Object> manifest,long totalBytes,Map<String,Object> searchData){}
}
