<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {http,dataOf} from '../api/http'
import {stepUpHeader,withStepUp} from '../api/stepUp'
import {ElMessage,ElMessageBox} from 'element-plus'
import {useAuthStore} from '../stores/auth'

const route=useRoute(),router=useRouter(),auth=useAuthStore()
const users=ref<any[]>([]),registrations=ref<any[]>([]),shareUsers=ref<any[]>([]),datasets=ref<any[]>([]),options=ref<any>({roles:[],scopes:[],departments:[]}),shares=ref<any[]>([])
const loading=ref(false),dialog=ref(false),reviewDialog=ref(false),shareDialog=ref(false),userDialog=ref(false),importDialog=ref(false),selected=ref<any>(null),reviewApplication=ref<any>(null),importFile=ref<File|null>(null),importResult=ref<any>(null)
const canAssignRoles=computed(()=>auth.can('user:manage')&&auth.can('permission:assign'))
const filter=reactive<any>({keyword:'',status:null,departmentId:null}),registrationFilter=reactive<any>({keyword:'',status:'PENDING'}),userForm=reactive<any>({id:null,username:'',realName:'',email:'',phone:'',departmentId:null,roleIds:[],scopeIds:[],status:1,reason:''}),importReason=ref('批量创建平台用户')
const assignment=reactive<{roleIds:number[],scopeIds:number[],departmentId:number|null,reason:string,version:number}>({roleIds:[],scopeIds:[],departmentId:null,reason:'',version:1})
const registrationReview=reactive<any>({decision:'APPROVE',comment:'资料核验通过，批准账号申请',roleIds:[],scopeIds:[],departmentId:null,applicationVersion:1,authorizationVersion:1})
const share=reactive<any>({resourceType:'DATA_SCOPE',resourceId:null,granteeType:'DEPARTMENT',granteeId:null,operations:['READ'],validTo:null,reason:''})
const grantees=computed(()=>share.granteeType==='USER'?shareUsers.value:share.granteeType==='ROLE'?options.value.roles:options.value.departments)
const resources=computed(()=>share.resourceType==='DATA_SCOPE'?options.value.scopes:datasets.value)

async function load(){loading.value=true;try{if(auth.can('user:manage')){const [page,opts,applications]=await Promise.all([http.get('/admin/users',{params:{pageSize:200,keyword:filter.keyword||undefined,status:filter.status,departmentId:filter.departmentId}}),http.get('/admin/options'),http.get('/admin/registrations',{params:{pageSize:200,keyword:registrationFilter.keyword||undefined,status:registrationFilter.status||undefined}})]);users.value=dataOf<any>(page).list;options.value=dataOf(opts);registrations.value=dataOf<any>(applications).list}if(auth.can('share:manage')){const shareOptions=dataOf<any>(await http.get('/shares/options'));shareUsers.value=shareOptions.users||[];datasets.value=shareOptions.datasets||[];options.value={...options.value,roles:shareOptions.roles||[],scopes:shareOptions.scopes||[],departments:shareOptions.departments||[]}}if(auth.can('share:read'))shares.value=dataOf<any>(await http.get('/shares',{params:{pageSize:200}})).list;if(route.query.shareDataset&&auth.can('share:manage')){openShare('DATASET',Number(route.query.shareDataset));await router.replace({path:'/admin',query:{}})}}finally{loading.value=false}}
function openRegistrationReview(row:any,decision:'APPROVE'|'REJECT'='APPROVE'){reviewApplication.value=row;Object.assign(registrationReview,{decision,comment:decision==='APPROVE'?'资料核验通过，批准账号申请':'资料不符合账号开通要求',roleIds:options.value.roles.filter((r:any)=>row.roles.includes(r.code)).map((r:any)=>r.id),scopeIds:[...row.dataScopes],departmentId:row.departmentId||null,applicationVersion:row.applicationVersion,authorizationVersion:row.authorizationVersion});reviewDialog.value=true}
async function submitRegistrationReview(){const row=reviewApplication.value,endpoint=`/admin/registrations/${row.id}/review`;const body={decision:registrationReview.decision,comment:registrationReview.comment.trim(),roleIds:registrationReview.decision==='APPROVE'?[...registrationReview.roleIds]:[],scopeIds:registrationReview.decision==='APPROVE'?[...registrationReview.scopeIds]:[],departmentId:registrationReview.decision==='APPROVE'?registrationReview.departmentId:null,applicationVersion:registrationReview.applicationVersion,authorizationVersion:registrationReview.authorizationVersion};await withStepUp({purpose:'PRIVILEGE',method:'POST',target:endpoint,label:`${body.decision==='APPROVE'?'批准':'驳回'}注册申请 ${row.username}`,payload:body},token=>http.post(endpoint,body,{headers:stepUpHeader(token)}));ElMessage.success('注册申请审核完成');reviewDialog.value=false;await load()}
function authorize(row:any){selected.value=row;assignment.roleIds=options.value.roles.filter((r:any)=>row.roles.includes(r.code)).map((r:any)=>r.id);assignment.scopeIds=[...row.dataScopes];assignment.departmentId=row.departmentId||null;assignment.reason='岗位与数据域授权调整';assignment.version=row.version;dialog.value=true}
async function save(){const endpoint=`/admin/users/${selected.value.id}/assignments`;const body={roleIds:[...assignment.roleIds],scopeIds:[...assignment.scopeIds],departmentId:assignment.departmentId,reason:assignment.reason,version:assignment.version};await withStepUp({purpose:'PRIVILEGE',method:'PUT',target:endpoint,label:`调整用户 ${selected.value.username} 的角色、部门和数据域授权`,payload:body},token=>http.put(endpoint,body,{headers:stepUpHeader(token)}));ElMessage.success('授权已更新，新权限从下一次请求起生效');dialog.value=false;load()}
async function toggle(row:any){const target=row.status===1?0:1;const {value}=await ElMessageBox.prompt(`请输入${target?'启用/审批':'停用'}原因`,`变更 ${row.username} 状态`,{inputPattern:/\S+/,inputErrorMessage:'原因不能为空',type:'warning'});const endpoint=`/admin/users/${row.id}/status`;const body={status:target,reason:value};await withStepUp({purpose:'PRIVILEGE',method:'PUT',target:endpoint,label:`${target?'审批启用':'停用'}用户 ${row.username}`,payload:body},token=>http.put(endpoint,body,{headers:stepUpHeader(token)}));ElMessage.success('用户状态已更新');load()}
function openUser(row:any=null){selected.value=row;Object.assign(userForm,row?{id:row.id,username:row.username,realName:row.realName,email:row.email||'',phone:row.phone||'',departmentId:row.departmentId,roleIds:[],scopeIds:[],status:row.status,reason:'用户资料调整'}:{id:null,username:'',realName:'',email:'',phone:'',departmentId:null,roleIds:[],scopeIds:[],status:1,reason:'创建业务账号'});if(row){userForm.roleIds=options.value.roles.filter((r:any)=>row.roles.includes(r.code)).map((r:any)=>r.id);userForm.scopeIds=[...row.dataScopes]}userDialog.value=true}
async function saveUser(){const endpoint=userForm.id?`/admin/users/${userForm.id}`:'/admin/users';const method=userForm.id?'PUT':'POST';const body=userForm.id?{realName:userForm.realName,email:userForm.email||null,phone:userForm.phone||null,reason:userForm.reason}:{username:userForm.username,realName:userForm.realName,email:userForm.email||null,phone:userForm.phone||null,departmentId:userForm.departmentId,roleIds:[...userForm.roleIds],scopeIds:[...userForm.scopeIds],status:userForm.status,reason:userForm.reason};const response=await withStepUp({purpose:'PRIVILEGE',method,target:endpoint,label:userForm.id?`编辑用户 ${userForm.username}`:`创建用户 ${userForm.username}`,payload:body},token=>http.request({method,url:endpoint,data:body,headers:stepUpHeader(token)}));userDialog.value=false;if(!userForm.id){const password=dataOf<any>(response).temporaryPassword;await ElMessageBox.alert(`账号：${userForm.username}\n一次性临时密码：${password}\n用户首次登录必须修改密码。`,'用户创建成功',{confirmButtonText:'我已安全保存'})}else ElMessage.success('用户资料已更新；部门变更请使用“授权”');await load()}
async function resetPassword(row:any){const {value}=await ElMessageBox.prompt('请输入重置原因','重置登录密码',{inputPattern:/\S+/,inputErrorMessage:'原因不能为空',type:'warning'});const endpoint=`/admin/users/${row.id}/reset-password`,body={reason:value};const response=await withStepUp({purpose:'PRIVILEGE',method:'POST',target:endpoint,label:`重置用户 ${row.username} 登录密码`,payload:body},token=>http.post(endpoint,body,{headers:stepUpHeader(token)}));await ElMessageBox.alert(`一次性临时密码：${dataOf<any>(response).temporaryPassword}\n用户首次登录必须修改，旧会话和二级密码均已撤销。`,'密码重置成功',{confirmButtonText:'我已安全保存'})}
async function deleteUser(row:any){const {value}=await ElMessageBox.prompt('请输入删除原因','删除用户',{inputPattern:/\S+/,inputErrorMessage:'原因不能为空',type:'warning'});const endpoint=`/admin/users/${row.id}`,body={reason:value};await withStepUp({purpose:'PRIVILEGE',method:'DELETE',target:endpoint,label:`删除用户 ${row.username}`,payload:body},token=>http.delete(endpoint,{data:body,headers:stepUpHeader(token)}));ElMessage.success('用户已逻辑删除');await load()}
function selectImport(file:any){importFile.value=file.raw||file;return false}
function openImport(){importFile.value=null;importResult.value=null;importReason.value='批量创建平台用户';importDialog.value=true}
function closeImport(){importResult.value=null;importFile.value=null;importDialog.value=false}
async function importUsers(){if(!importFile.value||!importReason.value.trim())return ElMessage.warning('请选择CSV/XLSX文件并填写原因');const endpoint='/admin/users/import',file=importFile.value,reason=importReason.value.trim();const bytes=await file.arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',bytes),sha256=Array.from(new Uint8Array(hash)).map(v=>v.toString(16).padStart(2,'0')).join('');const proofPayload={reason,size:file.size,sha256};const result=await withStepUp({purpose:'PRIVILEGE',method:'POST',target:endpoint,label:'批量导入用户',payload:proofPayload},async token=>{const data=new FormData();data.append('file',file);data.append('reason',reason);return http.post(endpoint,data,{headers:stepUpHeader(token)})});importResult.value=dataOf(result);ElMessage.success(`导入完成：成功 ${importResult.value.successCount}，失败 ${importResult.value.failureCount}`);await load()}
function openShare(type='DATA_SCOPE',id:number|null=null){Object.assign(share,{resourceType:type,resourceId:id,granteeType:'DEPARTMENT',granteeId:null,operations:['READ'],validTo:null,reason:''});shareDialog.value=true}
async function createShare(){if(!share.resourceId||!share.granteeId||!share.reason.trim())return ElMessage.warning('请完整选择资源、共享目标并填写原因');const endpoint='/shares';const body={...share,validTo:share.validTo instanceof Date?share.validTo.toISOString():share.validTo};await withStepUp({purpose:'PRIVILEGE',method:'POST',target:endpoint,label:`创建 ${share.resourceType} 到 ${share.granteeType} 的选择性共享规则`,payload:body},token=>http.post(endpoint,body,{headers:stepUpHeader(token)}));ElMessage.success('共享规则已创建，将从接收者下一次请求起生效');shareDialog.value=false;await load()}
async function revoke(rule:any){const {value}=await ElMessageBox.prompt('请输入撤销原因','撤销共享',{inputPattern:/\S+/,inputErrorMessage:'原因不能为空',type:'warning'});const endpoint=`/shares/${rule.id}`;const body={version:rule.version,reason:value};await withStepUp({purpose:'PRIVILEGE',method:'DELETE',target:endpoint,label:`撤销共享规则 #${rule.id}`,payload:body},token=>http.delete(endpoint,{data:body,headers:stepUpHeader(token)}));ElMessage.success('共享已撤销，接收者下一次请求立即失效');await load()}
onMounted(load)
</script>

<template><div class="page"><div class="page-head"><div><h1 class="page-title">系统与共享管理</h1><div class="page-subtitle">注册审批、多角色权限、部门/数据域授权与跨部门选择性共享</div></div><el-button @click="load">刷新</el-button></div>
 <el-tabs><el-tab-pane v-if="auth.can('user:manage')" label="注册审核"><div class="registration-tools"><el-input v-model="registrationFilter.keyword" clearable placeholder="用户名或姓名" @keyup.enter="load"/><el-select v-model="registrationFilter.status" clearable placeholder="全部审核状态"><el-option label="待审核" value="PENDING"/><el-option label="已批准" value="APPROVED"/><el-option label="已驳回" value="REJECTED"/></el-select><el-button @click="load">查询</el-button></div><el-alert title="注册账号默认不可登录且仅保留访客占位角色；批准时必须在同一事务内分配正式角色、部门和数据域。" type="info" :closable="false"/><div class="surface registration-table"><el-table :data="registrations" v-loading="loading"><el-table-column prop="username" label="用户名"/><el-table-column prop="realName" label="姓名"/><el-table-column label="已验证目标" min-width="180"><template #default="{row}">{{row.verificationChannel}} · {{row.destinationMasked}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='PENDING'?'warning':row.status==='APPROVED'?'success':'danger'">{{row.status}}</el-tag></template></el-table-column><el-table-column prop="submittedTime" label="申请时间" min-width="180"/><el-table-column prop="reviewComment" label="审核意见" min-width="180"/><el-table-column label="操作" width="130"><template #default="{row}"><template v-if="row.status==='PENDING'&&canAssignRoles"><el-button link type="primary" @click="openRegistrationReview(row,'APPROVE')">批准</el-button><el-button link type="danger" @click="openRegistrationReview(row,'REJECT')">驳回</el-button></template><span v-else>—</span></template></el-table-column></el-table></div></el-tab-pane>
 <el-tab-pane v-if="auth.can('user:manage')" label="用户管理"><div class="user-tools"><el-input v-model="filter.keyword" clearable placeholder="用户名或姓名" @keyup.enter="load"/><el-select v-model="filter.departmentId" clearable placeholder="全部部门"><el-option v-for="d in options.departments" :key="d.id" :label="d.name" :value="d.id"/></el-select><el-select v-model="filter.status" clearable placeholder="全部状态"><el-option label="启用" :value="1"/><el-option label="停用" :value="0"/></el-select><el-button @click="load">查询</el-button><el-button v-if="canAssignRoles" type="primary" @click="openUser()">新增用户</el-button><el-button v-if="canAssignRoles" @click="openImport">批量导入</el-button></div><div class="surface"><el-table :data="users" v-loading="loading"><el-table-column prop="username" label="用户名"/><el-table-column prop="realName" label="姓名"/><el-table-column prop="department" label="部门"/><el-table-column label="角色" min-width="170"><template #default="{row}"><el-tag v-for="r in row.roles" :key="r" size="small">{{r}}</el-tag></template></el-table-column><el-table-column label="数据域" width="120"><template #default="{row}">{{row.dataScopes.join(', ')||'—'}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="row.status===1?'success':'warning'">{{row.status===1?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="createdTime" label="创建时间" width="180"/><el-table-column label="操作" width="280"><template #default="{row}"><el-button link @click="openUser(row)">编辑</el-button><el-button v-if="canAssignRoles" link type="primary" @click="authorize(row)">授权</el-button><el-button link @click="resetPassword(row)">重置密码</el-button><el-button link :type="row.status===1?'danger':'success'" @click="toggle(row)">{{row.status===1?'停用':'启用'}}</el-button><el-button link type="danger" @click="deleteUser(row)">删除</el-button></template></el-table-column></el-table></div></el-tab-pane>
  <el-tab-pane v-if="auth.can('share:read')" label="选择性共享"><div class="share-head"><el-alert title="共享仅扩大读取范围，不授予接收者原本没有的模块权限；READ 必选，导出和附件下载须单独授权。" type="info" :closable="false"/><el-button v-if="auth.can('share:manage')" type="primary" @click="openShare()">新建共享规则</el-button></div><div class="surface"><el-table :data="shares" v-loading="loading"><el-table-column label="资源" min-width="190"><template #default="{row}"><b>{{row.resourceName}}</b><small>{{row.resourceType}} #{{row.resourceId}}</small></template></el-table-column><el-table-column label="共享给" min-width="160"><template #default="{row}">{{row.granteeName}}<small>{{row.granteeType}} #{{row.granteeId}}</small></template></el-table-column><el-table-column label="允许操作" width="190"><template #default="{row}"><el-tag v-for="op in row.operations" :key="op" size="small">{{op}}</el-tag></template></el-table-column><el-table-column label="有效期" min-width="190"><template #default="{row}">{{row.validFrom}}<small>至 {{row.validTo||'长期有效'}}</small></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':row.status==='EXPIRED'?'warning':'info'">{{row.status}}</el-tag></template></el-table-column><el-table-column prop="reason" label="原因" min-width="180"/><el-table-column label="操作" width="90"><template #default="{row}"><el-button v-if="auth.can('share:revoke')&&row.status==='ACTIVE'" link type="danger" @click="revoke(row)">撤销</el-button></template></el-table-column></el-table></div></el-tab-pane>
  <el-tab-pane v-if="auth.can('user:manage')" label="角色权限"><div class="surface option-grid"><article v-for="role in options.roles" :key="role.id"><b>{{role.name}} · {{role.code}}</b><p>{{role.description||'暂无说明'}}</p></article></div></el-tab-pane><el-tab-pane v-if="auth.can('user:manage')" label="数据域"><div class="surface option-grid"><article v-for="scope in options.scopes" :key="scope.id"><b>{{scope.name}}</b><p>{{scope.code}} · {{scope.type}}</p></article></div></el-tab-pane></el-tabs>
 <el-dialog v-model="dialog" :title="`授权 · ${selected?.realName||''}`" width="620"><el-form label-position="top"><el-form-item label="角色（可多选）"><el-select v-model="assignment.roleIds" multiple style="width:100%"><el-option v-for="role in options.roles" :key="role.id" :label="`${role.name} (${role.code})`" :value="role.id"/></el-select></el-form-item><el-form-item label="直接数据域（可写，取决于角色操作权限）"><el-select v-model="assignment.scopeIds" multiple style="width:100%"><el-option v-for="scope in options.scopes" :key="scope.id" :label="`${scope.name} (${scope.code})`" :value="scope.id"/></el-select></el-form-item><el-form-item label="部门"><el-select v-model="assignment.departmentId" clearable style="width:100%"><el-option v-for="dept in options.departments" :key="dept.id" :label="dept.name" :value="dept.id"/></el-select></el-form-item><el-form-item label="变更原因"><el-input v-model="assignment.reason" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :disabled="!assignment.roleIds.length||!assignment.reason.trim()" @click="save">保存授权</el-button></template></el-dialog>
 <el-dialog v-model="reviewDialog" :title="`${registrationReview.decision==='APPROVE'?'批准':'驳回'}注册申请 · ${reviewApplication?.username||''}`" width="660"><el-form label-position="top"><el-radio-group v-model="registrationReview.decision"><el-radio value="APPROVE">批准并启用</el-radio><el-radio value="REJECT">驳回申请</el-radio></el-radio-group><template v-if="registrationReview.decision==='APPROVE'"><el-form-item label="正式角色（必选）"><el-select v-model="registrationReview.roleIds" multiple><el-option v-for="role in options.roles" :key="role.id" :label="`${role.name} (${role.code})`" :value="role.id"/></el-select></el-form-item><el-form-item label="直接数据域（必选）"><el-select v-model="registrationReview.scopeIds" multiple><el-option v-for="scope in options.scopes" :key="scope.id" :label="`${scope.name} (${scope.code})`" :value="scope.id"/></el-select></el-form-item><el-form-item label="部门"><el-select v-model="registrationReview.departmentId" clearable><el-option v-for="dept in options.departments" :key="dept.id" :label="dept.name" :value="dept.id"/></el-select></el-form-item></template><el-form-item label="审核意见"><el-input v-model="registrationReview.comment" type="textarea" :rows="3" maxlength="1000" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="reviewDialog=false">取消</el-button><el-button :type="registrationReview.decision==='APPROVE'?'primary':'danger'" :disabled="!registrationReview.comment.trim()||(registrationReview.decision==='APPROVE'&&(!registrationReview.roleIds.length||!registrationReview.scopeIds.length))" @click="submitRegistrationReview">确认{{registrationReview.decision==='APPROVE'?'批准':'驳回'}}</el-button></template></el-dialog>
 <el-dialog v-if="auth.can('share:manage')" v-model="shareDialog" title="新建选择性共享规则" width="680"><el-form label-position="top"><div class="form-grid"><el-form-item label="资源类型"><el-select v-model="share.resourceType" @change="share.resourceId=null"><el-option label="数据域（域内全部只读资源）" value="DATA_SCOPE"/><el-option label="单个数据集" value="DATASET"/></el-select></el-form-item><el-form-item label="共享资源"><el-select v-model="share.resourceId" filterable><el-option v-for="item in resources" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="目标类型"><el-select v-model="share.granteeType" @change="share.granteeId=null"><el-option label="部门" value="DEPARTMENT"/><el-option label="角色" value="ROLE"/><el-option label="用户" value="USER"/></el-select></el-form-item><el-form-item label="共享给"><el-select v-model="share.granteeId" filterable><el-option v-for="item in grantees" :key="item.id" :label="item.name||item.realName" :value="item.id"/></el-select></el-form-item></div><el-form-item label="允许操作"><el-checkbox-group v-model="share.operations"><el-checkbox value="READ" disabled>查看 / 检索 / 看板</el-checkbox><el-checkbox value="EXPORT">数据导出</el-checkbox><el-checkbox value="DOWNLOAD">附件下载</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="结束时间（不填表示长期，过期自动失效）"><el-date-picker v-model="share.validTo" type="datetime" placeholder="选择结束时间" style="width:100%"/></el-form-item><el-form-item label="共享原因"><el-input v-model="share.reason" type="textarea" :rows="3" maxlength="1000" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="shareDialog=false">取消</el-button><el-button type="primary" @click="createShare">创建规则</el-button></template></el-dialog>
 <el-dialog v-model="userDialog" :title="userForm.id?'编辑用户资料':'新增用户'" width="680"><el-form label-position="top"><div class="form-grid"><el-form-item label="用户名"><el-input v-model="userForm.username" :disabled="!!userForm.id"/></el-form-item><el-form-item label="姓名"><el-input v-model="userForm.realName"/></el-form-item><el-form-item label="邮箱"><el-input v-model="userForm.email"/></el-form-item><el-form-item label="手机号"><el-input v-model="userForm.phone"/></el-form-item><el-form-item v-if="!userForm.id" label="部门"><el-select v-model="userForm.departmentId" clearable><el-option v-for="d in options.departments" :key="d.id" :label="d.name" :value="d.id"/></el-select></el-form-item><el-form-item v-else label="部门"><el-input :model-value="selected?.department||'未分配'" disabled/><small>部门属于授权范围，请使用用户列表中的“授权”按钮调整。</small></el-form-item><el-form-item v-if="!userForm.id" label="状态"><el-switch v-model="userForm.status" :active-value="1" :inactive-value="0"/></el-form-item></div><template v-if="!userForm.id"><el-form-item label="初始角色"><el-select v-model="userForm.roleIds" multiple><el-option v-for="r in options.roles" :key="r.id" :label="`${r.name} (${r.code})`" :value="r.id"/></el-select></el-form-item><el-form-item label="初始数据域"><el-select v-model="userForm.scopeIds" multiple><el-option v-for="s in options.scopes" :key="s.id" :label="`${s.name} (${s.code})`" :value="s.id"/></el-select></el-form-item></template><el-form-item label="操作原因"><el-input v-model="userForm.reason" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="userDialog=false">取消</el-button><el-button type="primary" :disabled="!userForm.realName||!userForm.reason||(!userForm.id&&(!userForm.username||!userForm.roleIds.length))" @click="saveUser">保存</el-button></template></el-dialog>
 <el-dialog v-model="importDialog" title="批量导入用户" width="760" @closed="closeImport"><el-alert title="支持 CSV/XLSX，表头：username、realName、email、phone、departmentCode、roleCodes、scopeCodes、status；多个角色/数据域用 | 分隔。" type="info" :closable="false"/><el-upload drag :auto-upload="false" :limit="1" accept=".csv,.xlsx" :on-change="selectImport"><div>拖入或选择用户导入文件</div></el-upload><el-input v-model="importReason" type="textarea" placeholder="导入原因"/><div v-if="importResult" class="import-result"><b>成功 {{importResult.successCount}} / 失败 {{importResult.failureCount}}</b><el-alert v-if="importResult.successes?.length" title="一次性临时密码只在本次结果中显示，请立即安全保存；关闭窗口后无法再次查看。" type="warning" :closable="false"/><el-table v-if="importResult.successes?.length" :data="importResult.successes" max-height="220"><el-table-column prop="rowNumber" label="行" width="60"/><el-table-column prop="username" label="用户名"/><el-table-column prop="temporaryPassword" label="一次性临时密码"><template #default="{row}"><span class="mono">{{row.temporaryPassword}}</span></template></el-table-column></el-table><el-table v-if="importResult.failures?.length" :data="importResult.failures" max-height="220"><el-table-column prop="rowNumber" label="行" width="60"/><el-table-column prop="username" label="用户名"/><el-table-column prop="message" label="失败原因"/></el-table></div><template #footer><el-button @click="closeImport">关闭</el-button><el-button type="primary" @click="importUsers">开始导入</el-button></template></el-dialog>
</div></template>

<style scoped>.option-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:18px}.option-grid article{padding:15px;border:1px solid #e5ebf1;border-radius:9px}.option-grid b{font-size:13px}.option-grid p{font-size:11px;color:#8190a3;margin:7px 0 0}.share-head{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;margin-bottom:12px}.user-tools{display:grid;grid-template-columns:220px 180px 150px auto auto auto;gap:10px;margin-bottom:12px}.registration-tools{display:grid;grid-template-columns:240px 180px auto;gap:10px;margin-bottom:12px}.registration-table{margin-top:12px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.el-select{width:100%}.el-table small{display:block;color:#8996a6;margin-top:4px}.el-tag+.el-tag{margin-left:4px}.import-result{margin-top:14px}@media(max-width:900px){.user-tools,.registration-tools{grid-template-columns:1fr 1fr}}@media(max-width:760px){.option-grid,.form-grid,.share-head,.user-tools,.registration-tools{grid-template-columns:1fr}}</style>
