<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {http,dataOf} from '../api/http'
import {stepUpHeader,withStepUp} from '../api/stepUp'
import {useAuthStore} from '../stores/auth'

type DatasetField=Record<string,any>&{__uiId:string;key:string;label:string;type:string;required:boolean;sensitive:boolean;maskType:string;__optionsText:string}
const auth=useAuthStore(),router=useRouter()
const rows=ref<any[]>([]),templates=ref<any[]>([]),governance=ref<any>({categories:[],categoryMappings:[],tags:[]}),total=ref(0),loading=ref(false),saving=ref(false)
const keyword=ref(''),category=ref(''),dialog=ref(false)
const scopeIds=computed(()=>auth.user?.assignedScopes||[])
const isAdmin=computed(()=>auth.user?.roles.includes('ADMIN')||false)
const fieldTypes=[['string','文本'],['number','数值'],['date','日期'],['boolean','布尔'],['file','文件'],['object','对象'],['array','数组']]
const form=reactive<any>({id:null,name:'',description:'',category:'研发数据',tagValues:[],scientificCategoryId:null,industryCategoryId:null,dataScopeId:1,templateId:null,dataCount:0,fields:[]})
const scientificCategories=computed(()=>governance.value.categories.filter((v:any)=>v.type==='SCIENTIFIC'))
const industryCategories=computed(()=>{if(!form.scientificCategoryId)return governance.value.categories.filter((v:any)=>v.type==='INDUSTRY');const allowed=new Set(governance.value.categoryMappings.filter((v:any)=>v.scientificCategoryId===form.scientificCategoryId).map((v:any)=>v.industryCategoryId));return governance.value.categories.filter((v:any)=>v.type==='INDUSTRY'&&allowed.has(v.id))})

function uid(){return crypto.randomUUID()}
function blankField(index=1):DatasetField{return{__uiId:uid(),__optionsText:'',key:`field${index}`,label:`字段 ${index}`,type:'string',required:false,sensitive:false,maskType:'GENERIC'}}
function hydrateField(raw:any):DatasetField{return{...structuredClone(raw),__uiId:uid(),__optionsText:Array.isArray(raw?.options)?JSON.stringify(raw.options):'',type:raw?.type==='text'?'string':String(raw?.type||'string'),key:String(raw?.key||''),label:String(raw?.label||''),required:Boolean(raw?.required),sensitive:Boolean(raw?.sensitive),maskType:String(raw?.maskType||'GENERIC')}}
function reset(){Object.assign(form,{id:null,name:'',description:'',category:'研发数据',tagValues:[],scientificCategoryId:null,industryCategoryId:null,dataScopeId:scopeIds.value[0]||1,templateId:null,dataCount:0,fields:[blankField()]})}
function owns(row:any){return isAdmin.value||Number(row.creatorId)===Number(auth.user?.id)}
function canEdit(row:any){return auth.can('dataset:update')&&owns(row)}
function canDelete(row:any){return auth.can('dataset:delete')&&owns(row)&&Number(row.dataCount)===0}
function shareDataset(row:any){router.push({path:'/admin',query:{shareDataset:String(row.id)}})}

async function load(){loading.value=true;try{const page=dataOf<any>(await http.get('/datasets',{params:{keyword:keyword.value||undefined,category:category.value||undefined,pageSize:50}}));rows.value=page.list;total.value=page.total}finally{loading.value=false}}
async function loadTemplates(){if(!auth.can('template:read'))return;const page=dataOf<any>(await http.get('/templates',{params:{usable:true,type:'template',pageSize:100}}));templates.value=page.list}
async function loadGovernance(){governance.value=dataOf<any>(await http.get('/governance/options'))}
function flattenTemplate(template:any){const properties=template?.schemaDefinition?.properties||{};return(template?.content?.sections||[]).flatMap((section:any)=>section.fields||[]).map((field:any)=>{const schema=structuredClone(properties[field.key]||{});const merged:any={...structuredClone(field),schema};if(merged.min==null&&schema.minimum!=null)merged.min=schema.minimum;if(merged.max==null&&schema.maximum!=null)merged.max=schema.maximum;if(merged.minLength==null&&schema.minLength!=null)merged.minLength=schema.minLength;if(merged.maxLength==null&&schema.maxLength!=null)merged.maxLength=schema.maxLength;if(merged.pattern==null&&schema.pattern!=null)merged.pattern=schema.pattern;if(merged.options==null&&Array.isArray(schema.enum))merged.options=structuredClone(schema.enum);return hydrateField(merged)})}
function applyTemplate(id:number|null){if(id==null){form.fields=[blankField()];return}const template=templates.value.find(item=>Number(item.id)===Number(id));if(template){form.fields=flattenTemplate(template);if(!form.name)form.name=`${template.name}数据集`;if(!form.tagValues.length)form.tagValues=String(template.tag||'').split(',').map((v:string)=>v.trim()).filter(Boolean)}}
function create(){if(!scopeIds.value.length)return ElMessage.warning('当前账号没有直接数据域授权，选择性共享不能用于创建数据集');reset();dialog.value=true}
async function edit(row:any){const value=dataOf<any>(await http.get(`/datasets/${row.id}`));Object.assign(form,{id:value.id,name:value.name,description:value.description||'',category:value.category||'研发数据',tagValues:String(value.tags||'').split(',').map((v:string)=>v.trim()).filter(Boolean),scientificCategoryId:value.scientificCategoryId==null?null:Number(value.scientificCategoryId),industryCategoryId:value.industryCategoryId==null?null:Number(value.industryCategoryId),dataScopeId:Number(value.dataScopeId),templateId:value.templateId==null?null:Number(value.templateId),dataCount:Number(value.dataCount),fields:(value.fieldDefinition||[]).map(hydrateField)});dialog.value=true}
function scientificChanged(){if(!industryCategories.value.some((v:any)=>v.id===form.industryCategoryId))form.industryCategoryId=null}
function addField(){form.fields.push(blankField(form.fields.length+1))}
function removeField(index:number){if(form.fields.length===1)return ElMessage.warning('数据集至少需要一个字段');form.fields.splice(index,1)}
function parseOptions(text:string,label:string){const source=text.trim();if(!source)return undefined;if(source.startsWith('[')){try{const value=JSON.parse(source);if(!Array.isArray(value))throw new Error();return value}catch{throw new Error(`${label}的可选值须为 JSON 数组，或使用逗号分隔文本`)}}return source.split(',').map(v=>v.trim()).filter(Boolean)}
function cleanField(field:DatasetField){const value:any={...field};delete value.__uiId;delete value.__optionsText;value.key=value.key.trim();value.label=value.label.trim();const options=parseOptions(field.__optionsText,value.label||value.key);if(options)value.options=options;else delete value.options;for(const key of ['unit','pattern'])if(value[key]!=null&&!String(value[key]).trim())delete value[key];for(const key of ['min','max','minLength','maxLength'])if(value[key]==null||value[key]==='')delete value[key];return value}
function body(){const fields=form.fields.map(cleanField);const keys=new Set<string>();for(const field of fields){if(!/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(field.key))throw new Error(`字段 key“${field.key}”格式不正确`);if(keys.has(field.key))throw new Error(`字段 key“${field.key}”重复`);keys.add(field.key);if(!field.label)throw new Error('字段名称不能为空')}return{name:form.name.trim(),description:form.description.trim(),category:form.category,tags:form.tagValues.join(','),scientificCategoryId:form.scientificCategoryId,industryCategoryId:form.industryCategoryId,dataScopeId:form.dataScopeId,templateId:form.templateId,fieldDefinition:fields}}
async function save(){if(!form.name.trim())return ElMessage.warning('请输入数据集名称');saving.value=true;try{const payload=body();if(form.id)await http.put(`/datasets/${form.id}`,payload);else await http.post('/datasets',payload);ElMessage.success(form.id?'数据集已更新':'数据集已创建');dialog.value=false;await load()}catch(error:any){if(!error?.response)ElMessage.error(error.message||'字段定义不正确')}finally{saving.value=false}}
async function remove(row:any){await ElMessageBox.confirm(`确认删除空数据集“${row.name}”？`,'删除数据集',{type:'warning'});const endpoint=`/datasets/${row.id}`;await withStepUp({purpose:'DELETE',method:'DELETE',target:endpoint,label:`删除数据集“${row.name}”`},token=>http.delete(endpoint,{headers:stepUpHeader(token)}));ElMessage.success('数据集已删除');await load()}
async function favorite(row:any){if(row.favorited)await http.delete(`/datasets/${row.id}/favorite`);else await http.put(`/datasets/${row.id}/favorite`);row.favorited=!row.favorited}
const go=(row:any)=>router.push('/datasets/'+row.id)
onMounted(async()=>{await Promise.all([load(),loadGovernance(),auth.can('template:read')?loadTemplates():Promise.resolve()])})
</script>

<template><div class="page"><div class="page-head"><div><h1 class="page-title">数据资产</h1><div class="page-subtitle">从已发布公共模板或本人私有模板建立受控数据集，也支持明确标识的自定义结构，共 {{total}} 个数据集</div></div><el-button v-if="auth.can('dataset:create')" type="primary" @click="create">创建数据集</el-button></div>
 <div class="surface toolbar"><el-input v-model="keyword" placeholder="搜索数据集、标签" clearable style="width:300px" @keyup.enter="load"/><el-select v-model="category" placeholder="全部分类" clearable style="width:150px"><el-option label="研发数据" value="研发数据"/><el-option label="生产数据" value="生产数据"/><el-option label="质量数据" value="质量数据"/></el-select><el-button @click="load">查询</el-button></div>
 <div class="surface"><el-table :data="rows" v-loading="loading" @row-click="go"><el-table-column label="数据集" min-width="280"><template #default="{row}"><div class="dataset-name"><i>▦</i><div><b>{{row.name}}</b><span>{{row.description||'暂无说明'}}</span></div></div></template></el-table-column><el-table-column prop="category" label="分类" width="110"/><el-table-column label="来源" min-width="155"><template #default="{row}"><el-tag v-if="row.templateId" type="primary" effect="plain">模板 #{{row.templateId}} · v{{row.templateVersion}}</el-tag><el-tag v-else type="info" effect="plain">自定义结构</el-tag></template></el-table-column><el-table-column label="记录数" width="100"><template #default="{row}"><b>{{Number(row.dataCount).toLocaleString()}}</b></template></el-table-column><el-table-column label="版本" width="75"><template #default="{row}">v{{row.version}}</template></el-table-column><el-table-column label="收藏" width="70"><template #default="{row}"><button class="favorite" @click.stop="favorite(row)">{{row.favorited?'★':'☆'}}</button></template></el-table-column><el-table-column label="负责人" prop="creatorName" width="105"/><el-table-column label="操作" width="250" fixed="right"><template #default="{row}"><el-button link type="primary" @click.stop="go(row)">进入</el-button><el-button v-if="auth.can('share:manage')" link @click.stop="shareDataset(row)">共享</el-button><el-button v-if="canEdit(row)" link @click.stop="edit(row)">编辑</el-button><el-button v-if="canDelete(row)" link type="danger" @click.stop="remove(row)">删除</el-button><el-tooltip v-else-if="auth.can('dataset:delete')&&owns(row)&&Number(row.dataCount)>0" content="已有记录的数据集必须归档，不能直接删除"><span class="disabled-action">删除</span></el-tooltip></template></el-table-column></el-table></div>

 <el-dialog v-model="dialog" :title="form.id?'编辑数据集':'创建数据集'" width="min(940px,94vw)" top="5vh"><el-alert v-if="form.dataCount>0" title="该数据集已有记录：模板来源、字段结构和数据域已冻结，只能修改名称、说明、分类和标签。" type="warning" :closable="false"/><el-form label-position="top"><div class="meta-grid"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="业务分类"><el-select v-model="form.category"><el-option label="研发数据" value="研发数据"/><el-option label="生产数据" value="生产数据"/><el-option label="质量数据" value="质量数据"/></el-select></el-form-item><el-form-item label="数据域"><el-select v-model="form.dataScopeId" :disabled="form.dataCount>0"><el-option v-for="scope in scopeIds" :key="scope" :label="`数据域 #${scope}`" :value="scope"/></el-select></el-form-item><el-form-item label="科学分类"><el-select v-model="form.scientificCategoryId" clearable @change="scientificChanged"><el-option v-for="v in scientificCategories" :key="v.id" :label="v.name" :value="v.id"/></el-select></el-form-item><el-form-item label="产业分类"><el-select v-model="form.industryCategoryId" clearable><el-option v-for="v in industryCategories" :key="v.id" :label="v.name" :value="v.id"/></el-select></el-form-item></div><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="2"/></el-form-item><el-form-item label="标签"><el-select v-model="form.tagValues" multiple filterable allow-create><el-option v-for="v in governance.tags" :key="v.id" :label="`${v.name} · ${v.group}`" :value="v.name"/></el-select></el-form-item><el-form-item v-if="auth.can('template:read')" label="结构来源"><el-select v-model="form.templateId" clearable :disabled="form.dataCount>0" placeholder="不选模板：创建自定义结构" @change="applyTemplate"><el-option v-for="template in templates" :key="template.id" :label="`${template.name} · v${template.version} · ${template.visibility==='PRIVATE'?'本人私有':'公共发布'}`" :value="template.id"/></el-select><small class="form-help">列表包含已审核发布且未停用的公共模板，以及本人未停用的私有模板；选择后复制该版本全部字段与约束。</small></el-form-item><el-alert v-else title="当前角色没有模板读取权限，本次只能创建自定义结构。" type="info" :closable="false"/></el-form>
  <div class="field-head"><div><h3>字段结构</h3><p>{{form.templateId?'字段、约束和脱敏策略来自已发布模板，不能在数据集内单独改写':'自定义结构：请直接配置字段、约束和导出脱敏策略'}}</p></div><el-button v-if="!form.templateId&&form.dataCount===0" @click="addField">＋ 添加字段</el-button></div><div class="field-editor" v-for="(field,index) in form.fields" :key="field.__uiId"><div class="field-main"><el-input v-model="field.label" :disabled="!!form.templateId||form.dataCount>0" placeholder="字段名称"/><el-input v-model="field.key" :disabled="!!form.templateId||form.dataCount>0" class="mono" placeholder="fieldKey"/><el-select v-model="field.type" :disabled="!!form.templateId||form.dataCount>0"><el-option v-for="type in fieldTypes" :key="type[0]" :label="type[1]" :value="type[0]"/></el-select><el-switch v-model="field.required" :disabled="!!form.templateId||form.dataCount>0" active-text="必填"/><el-button v-if="!form.templateId&&form.dataCount===0" type="danger" link @click="removeField(Number(index))">删除</el-button></div><div class="constraints"><el-input v-model="field.unit" :disabled="!!form.templateId||form.dataCount>0" placeholder="单位"/><el-input-number v-if="field.type==='number'" v-model="field.min" :disabled="!!form.templateId||form.dataCount>0" placeholder="最小值"/><el-input-number v-if="field.type==='number'" v-model="field.max" :disabled="!!form.templateId||form.dataCount>0" placeholder="最大值"/><el-input v-model="field.__optionsText" :disabled="!!form.templateId||form.dataCount>0" placeholder="可选值：JSON数组或逗号分隔文本"/><el-switch v-model="field.sensitive" :disabled="!!form.templateId||form.dataCount>0" active-text="敏感字段"/><el-select v-if="field.sensitive" v-model="field.maskType" :disabled="!!form.templateId||form.dataCount>0"><el-option label="通用掩码" value="GENERIC"/><el-option label="手机号" value="PHONE"/><el-option label="邮箱" value="EMAIL"/><el-option label="证件号" value="ID_CARD"/><el-option label="姓名" value="NAME"/></el-select></div></div>
  <template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">{{form.id?'保存修改':'创建数据集'}}</el-button></template></el-dialog>
</div></template>

<style scoped>
.dataset-name{display:flex;align-items:center;gap:12px;cursor:pointer}.dataset-name i{width:35px;height:35px;border-radius:9px;background:#eaf3fa;color:#2872a0;display:grid;place-items:center;font-style:normal}.dataset-name b,.dataset-name span{display:block}.dataset-name span{font-size:11px;color:#8995a4;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:300px}.favorite{border:0;background:none;color:#e4a11b;font-size:19px;cursor:pointer}.disabled-action{color:#bbb;font-size:12px;margin-left:10px;cursor:not-allowed}.meta-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:15px}.form-help{display:block;color:#8895a4;margin-top:6px}.field-head{display:flex;justify-content:space-between;align-items:center;border-top:1px solid #e6ecf2;padding-top:15px}.field-head h3{font-size:15px;margin:0}.field-head p{font-size:11px;color:#8794a5;margin:5px 0}.field-editor{border:1px solid #e6ecf2;border-radius:10px;padding:12px;margin-top:10px;background:#fbfcfe}.field-main{display:grid;grid-template-columns:1.2fr 1fr 130px 85px 50px;gap:9px;align-items:center}.constraints{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:9px;margin-top:9px}.el-select{width:100%}
@media(max-width:760px){.meta-grid,.field-main,.constraints{grid-template-columns:1fr}.field-head{align-items:flex-start}}
</style>
