<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';import {http,dataOf} from '../api/http';import {stepUpHeader,withStepUp} from '../api/stepUp';import {cancelResumableFile,isLargeFile,resumableUpload} from '../api/resumableUpload';import {ElMessage,ElMessageBox} from 'element-plus';import {useAuthStore} from '../stores/auth'
const auth=useAuthStore(),rows=ref<any[]>([]),objects=ref<any[]>([]),receivedShares=ref<any[]>([]),loading=ref(false),uploading=ref(false),uploadProgress=ref(0),uploadPhase=ref(''),uploadController=ref<AbortController|null>(null),businessType=ref('DATASET'),businessRef=ref(''),dataScopeId=ref(0),selectedFiles=ref<File[]>([]),fileInput=ref<HTMLInputElement|null>(null)
const isAdmin=computed(()=>auth.user?.roles.includes('ADMIN')||false)
const directAccess=computed(()=>isAdmin.value||auth.user?.assignedScopes?.includes(Number(dataScopeId.value))||false)
const sharedOperations=computed(()=>{const result=new Set<string>();for(const rule of receivedShares.value){if(rule.status!=='ACTIVE')continue;const matches=rule.resourceType==='DATA_SCOPE'&&Number(rule.resourceId)===Number(dataScopeId.value)||businessType.value==='DATASET'&&rule.resourceType==='DATASET'&&Number(rule.resourceId)===Number(businessRef.value);if(matches)for(const operation of rule.operations||[])result.add(String(operation))}return result})
const canUpload=computed(()=>auth.can('file:upload')&&directAccess.value)
const canDownload=computed(()=>auth.can('file:read')&&(directAccess.value||businessType.value==='TEMPLATE'||sharedOperations.value.has('DOWNLOAD')))
const canDelete=computed(()=>auth.can('file:delete')&&directAccess.value)
async function load(){if(!businessRef.value.trim())return;loading.value=true;try{rows.value=dataOf(await http.get('/files',{params:{businessType:businessType.value,businessRef:businessRef.value.trim()}}))}finally{loading.value=false}}
async function loadObjects(){if(businessType.value==='OTHER'){objects.value=[];businessRef.value='';return}let response:any;if(businessType.value==='DATASET')response=dataOf<any>(await http.get('/datasets',{params:{pageSize:100}})).list;else if(businessType.value==='TEMPLATE')response=dataOf<any>(await http.get('/templates',{params:{pageSize:100}})).list;else if(businessType.value==='TRACE_ENTITY')response=dataOf(await http.get('/trace/entities'));else response=dataOf(await http.get('/devices'));objects.value=response.map((item:any)=>({id:String(item.id),name:item.name||item.entityName||item.deviceName||item.deviceCode,dataScopeId:item.dataScopeId}));businessRef.value=objects.value[0]?.id||'';syncScope();rows.value=[];if(businessRef.value)await load()}
function syncScope(){const selected=objects.value.find(item=>item.id===businessRef.value);if(selected)dataScopeId.value=selected.dataScopeId}
function choose(event:Event){selectedFiles.value=Array.from((event.target as HTMLInputElement).files||[])}
async function upload(){if(!selectedFiles.value.length)return ElMessage.warning('请选择文件');if(selectedFiles.value.length>20)return ElMessage.warning('单批最多选择20个文件');uploading.value=true;uploadProgress.value=0;uploadController.value=new AbortController();const target={businessType:businessType.value,businessRef:businessRef.value.trim(),dataScopeId:Number(dataScopeId.value)};try{const large=selectedFiles.value.filter(isLargeFile),small=selectedFiles.value.filter(file=>!isLargeFile(file));for(const file of large){await resumableUpload(file,target,value=>{uploadProgress.value=value.percent;uploadPhase.value=value.phase==='hashing'?'计算完整性摘要':value.phase==='uploading'?`分片上传 ${value.uploadedChunks}/${value.totalChunks}`:'合并校验'},uploadController.value.signal)}if(small.length){const form=new FormData();small.forEach(file=>form.append('files',file));form.append('businessType',target.businessType);form.append('businessRef',target.businessRef);form.append('dataScopeId',String(target.dataScopeId));const result=dataOf<any>(await http.post('/files/batch',form,{signal:uploadController.value.signal}));if(result.failureCount)ElMessage.warning(`小文件成功 ${result.successCount} 个，失败 ${result.failureCount} 个`)}ElMessage.success('附件上传完成');selectedFiles.value=[];if(fileInput.value)fileInput.value.value='';await load()}catch(error:any){if(error?.code==='ERR_CANCELED'||error?.name==='AbortError')ElMessage.info('上传已暂停；重新选择同一文件即可从缺失分片继续');else throw error}finally{uploading.value=false;uploadController.value=null}}
function pauseUpload(){uploadController.value?.abort()}
async function cancelUpload(){uploadController.value?.abort();const target={businessType:businessType.value,businessRef:businessRef.value.trim(),dataScopeId:Number(dataScopeId.value)};for(const file of selectedFiles.value.filter(isLargeFile))await cancelResumableFile(file,target);uploading.value=false;uploadProgress.value=0;ElMessage.info('分片会话及临时内容已取消')}
async function fetchBlob(row:any,preview=false){const blob=await http.get(`/files/${row.id}`,{params:{preview},responseType:'blob'}) as unknown as Blob;const url=URL.createObjectURL(blob);if(preview){window.open(url,'_blank','noopener,noreferrer')}else{const link=document.createElement('a');link.href=url;link.download=row.originalName;link.click()}window.setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function remove(row:any){await ElMessageBox.confirm(`确认删除附件“${row.originalName}”？此操作会保留删除审计。`,'删除附件',{type:'warning'});const endpoint=`/files/${row.id}`;await withStepUp({purpose:'DELETE',method:'DELETE',target:endpoint,label:`删除附件“${row.originalName}”`},token=>http.delete(endpoint,{headers:stepUpHeader(token)}));ElMessage.success('附件已删除');load()}
function size(value:number){if(value<1024)return value+' B';if(value<1048576)return(value/1024).toFixed(1)+' KB';return(value/1048576).toFixed(1)+' MB'}
function previewable(type:string){return ['text/plain','application/pdf','image/png','image/jpeg','image/gif','image/webp','image/bmp'].includes(String(type).toLowerCase())}
watch(businessType,loadObjects);onMounted(async()=>{dataScopeId.value=auth.user?.assignedScopes?.[0]||0;receivedShares.value=dataOf(await http.get('/shares/mine'));await loadObjects()})
</script>
<template><div class="page"><div class="page-head"><div><h1 class="page-title">附件中心</h1><div class="page-subtitle">PostgreSQL 保存授权元数据，MongoDB GridFS 保存原始内容并校验 SHA-256</div></div></div>
 <div class="surface toolbar"><el-select v-model="businessType" style="width:160px"><el-option label="数据集" value="DATASET"/><el-option label="模板" value="TEMPLATE"/><el-option label="追溯实体" value="TRACE_ENTITY"/><el-option label="设备" value="DEVICE"/><el-option label="其他" value="OTHER"/></el-select><el-select v-if="businessType!=='OTHER'" v-model="businessRef" placeholder="选择可访问对象" filterable style="width:280px" @change="syncScope();load()"><el-option v-for="item in objects" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-input v-else v-model="businessRef" placeholder="其他业务引用" style="width:280px"/><el-input-number v-if="businessType==='OTHER'" v-model="dataScopeId" :min="1"/><el-tag v-else type="info">数据域 {{dataScopeId}}</el-tag><el-button @click="load">查询附件</el-button></div>
 <el-alert v-if="businessRef&&!directAccess" :title="`当前对象来自选择性共享；允许操作：${[...sharedOperations].join('、')||'READ'}。`" type="info" :closable="false" style="margin-bottom:14px"/>
 <div v-if="canUpload" class="surface upload-box"><input ref="fileInput" type="file" multiple @change="choose"><div><b>{{selectedFiles.length?`已选择 ${selectedFiles.length} 个文件`:'批量选择图片、PDF、3D模型、仿真或报告文件'}}</b><small>8MB及以上自动使用4MB分片；支持暂停、刷新页面后重新选择同一文件继续，并在完成时校验整文件SHA-256。</small><el-progress v-if="uploading" :percentage="uploadProgress" :format="()=>uploadPhase"/></div><template v-if="uploading"><el-button @click="pauseUpload">暂停</el-button><el-button type="danger" plain @click="cancelUpload">取消并清理</el-button></template><el-button v-else type="primary" :disabled="!selectedFiles.length||!businessRef.trim()" @click="upload">上传并校验</el-button></div>
 <div class="surface"><el-table :data="rows" v-loading="loading"><el-table-column prop="originalName" label="文件名" min-width="220"/><el-table-column prop="contentType" label="类型" width="170"/><el-table-column label="大小" width="100"><template #default="{row}">{{size(row.sizeBytes)}}</template></el-table-column><el-table-column label="SHA-256" min-width="230"><template #default="{row}"><span class="mono digest">{{row.sha256}}</span></template></el-table-column><el-table-column prop="uploadedByName" label="上传人" width="110"/><el-table-column prop="createdTime" label="时间" width="180"/><el-table-column label="操作" width="190"><template #default="{row}"><el-button v-if="canDownload&&previewable(row.contentType)" link type="primary" @click="fetchBlob(row,true)">安全预览</el-button><el-button v-if="canDownload" link @click="fetchBlob(row)">下载</el-button><el-button v-if="canDelete" link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div v-if="!rows.length&&!loading" class="empty-note">当前业务对象暂无附件</div></div>
</div></template>
<style scoped>.upload-box{padding:22px;display:flex;align-items:center;gap:16px;margin-bottom:16px}.upload-box input{width:210px}.upload-box>div{flex:1}.upload-box b,.upload-box small{display:block}.upload-box small{color:#8794a5;margin-top:6px}.digest{font-size:10px;color:#60728a;word-break:break-all}</style>
