<script setup lang="ts">
import {computed,nextTick,onMounted,reactive,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {http,dataOf} from '../api/http'
import {stepUpHeader,withStepUp} from '../api/stepUp'
import {useAuthStore} from '../stores/auth'

const route=useRoute(),auth=useAuthStore(),loading=ref(false),activeTab=ref('scientific'),overview=ref<any>({categories:[],categoryMappings:[],tags:[],dictionaries:[],dictionaryItems:[],menus:[],uiConfig:{}}),departments=ref<any[]>([]),departmentLeaders=ref<any[]>([]),roles=ref<any[]>([]),permissions=ref<any[]>([]),dataScopes=ref<any[]>([])
type GovernanceDialog='category'|'department'|'role'|'tag'|'dictionary'|'item'|'menu'|'dataScope'|'mapping'|''
const dialog=ref<GovernanceDialog>(''),editing=ref<any>(null)
const dialogVisible=computed(()=>dialog.value!=='')
const permissionTreeRef=ref<any>(null)
const category=reactive<any>({type:'SCIENTIFIC',name:'',code:'',parentId:null,productCodes:'',sortOrder:0,status:1})
const department=reactive<any>({name:'',code:'',parentId:null,leaderId:null,sortOrder:0,status:1})
const role=reactive<any>({name:'',code:'',description:'',sortOrder:0,status:1,permissionIds:[],version:1})
const tag=reactive<any>({name:'',color:'#409EFF',group:'默认分组',status:1})
const dictionary=reactive<any>({name:'',code:'',description:'',status:1})
const item=reactive<any>({dictionaryId:null,label:'',value:'',sortOrder:0,status:1})
const menu=reactive<any>({name:'',code:'',route:'',icon:'',permissionCode:'',parentId:null,sortOrder:0,status:1})
const dataScope=reactive<any>({name:'',code:'',type:'PROJECT',description:'',active:true,version:1})
const mapping=reactive<any>({scientificId:null,industryCategoryIds:[]})
const ui=reactive<any>({primaryColor:'#1677A8',fontSize:14,borderRadius:9,contentSpacing:20,version:1})
const canClassify=computed(()=>auth.can('classification:manage')),canTag=computed(()=>auth.can('tag:manage')),canDictionary=computed(()=>auth.can('dictionary:manage')),canMenu=computed(()=>auth.can('menu:manage')),canUi=computed(()=>auth.can('ui:manage')),canDataScope=computed(()=>auth.can('data-scope:manage')),canAssignPermissions=computed(()=>auth.can('role:manage')&&auth.can('permission:assign'))
const scientific=computed(()=>overview.value.categories.filter((v:any)=>v.type==='SCIENTIFIC'))
const industry=computed(()=>overview.value.categories.filter((v:any)=>v.type==='INDUSTRY'))
const dictionaryItems=computed(()=>overview.value.dictionaryItems.filter((v:any)=>!item.dictionaryId||v.dictionaryId===item.dictionaryId))
const permissionTree=computed(()=>{const groups=new Map<string,any[]>();permissions.value.filter((p:any)=>p.status===1).forEach((p:any)=>{const key=String(p.code).split(':')[0]||'other';if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(p)});return [...groups.entries()].map(([key,children])=>({id:`group:${key}`,name:key.toUpperCase(),children}))})
const tree=(rows:any[])=>{const nodes=rows.map(row=>({...row,children:[]})),map=new Map(nodes.map(row=>[row.id,row]));nodes.forEach(row=>{if(row.parentId&&map.has(Number(row.parentId)))map.get(Number(row.parentId)).children.push(row)});return nodes.filter(row=>!row.parentId||!map.has(Number(row.parentId)))}
const scientificTree=computed(()=>tree(scientific.value)),industryTree=computed(()=>tree(industry.value)),departmentTree=computed(()=>tree(departments.value)),menuTree=computed(()=>tree(overview.value.menus))

async function load(){loading.value=true;try{overview.value=dataOf<any>(await http.get('/governance/overview'));Object.assign(ui,overview.value.uiConfig||{});if(auth.can('organization:manage')||auth.can('user:manage'))departments.value=dataOf<any[]>(await http.get('/governance/departments'));if(auth.can('organization:manage'))departmentLeaders.value=dataOf<any[]>(await http.get('/governance/department-leaders'));if(auth.can('role:manage')){[roles.value,permissions.value]=await Promise.all([http.get('/governance/roles').then(response=>dataOf<any[]>(response)),http.get('/governance/permissions').then(response=>dataOf<any[]>(response))])}if(canDataScope.value)dataScopes.value=dataOf<any[]>(await http.get('/governance/data-scopes'))}finally{loading.value=false}}
async function mutate(method:'POST'|'PUT'|'DELETE',target:string,payload:any,label:string){await withStepUp({purpose:'PRIVILEGE',method,target,label,payload},token=>http.request({method,url:target,data:payload,headers:stepUpHeader(token)}));ElMessage.success('操作成功');dialog.value='';editing.value=null;await load()}
function closeDialog(){dialog.value='';editing.value=null}
async function remove(target:string,label:string){const {value}=await ElMessageBox.prompt('请输入删除原因',label,{type:'warning',inputPattern:/\S+/,inputErrorMessage:'原因不能为空'});await mutate('DELETE',target,{reason:value},label)}
function openCategory(type:string,row:any=null){editing.value=row;Object.assign(category,row?{type:row.type,name:row.name,code:row.code,parentId:row.parentId,productCodes:(row.productCodes||[]).join(','),sortOrder:row.sortOrder,status:row.status}:{type,name:'',code:'',parentId:null,productCodes:'',sortOrder:0,status:1});dialog.value='category'}
function saveCategory(){const body={name:category.name,code:category.code,parentId:category.parentId,productCodes:category.productCodes.split(',').map((v:string)=>v.trim()).filter(Boolean),sortOrder:category.sortOrder,status:category.status};if(editing.value)return mutate('PUT',`/governance/categories/${editing.value.id}`,body,'修改分类');return mutate('POST','/governance/categories',{type:category.type,...body},'创建分类')}
function openDepartment(row:any=null){editing.value=row;Object.assign(department,row?{name:row.name,code:row.code,parentId:row.parentId,leaderId:row.leaderId,sortOrder:row.sortOrder,status:row.status}:{name:'',code:'',parentId:null,leaderId:null,sortOrder:0,status:1});dialog.value='department'}
function saveDepartment(){const method=editing.value?'PUT':'POST',target=editing.value?`/governance/departments/${editing.value.id}`:'/governance/departments';return mutate(method,target,{...department},editing.value?'修改部门':'创建部门')}
function openRole(row:any=null){editing.value=row;Object.assign(role,row?{name:row.name,code:row.code,description:row.description||'',sortOrder:row.sortOrder,status:row.status,permissionIds:[...row.permissionIds],version:row.version}:{name:'',code:'',description:'',sortOrder:0,status:1,permissionIds:[],version:1});dialog.value='role';nextTick(()=>permissionTreeRef.value?.setCheckedKeys(role.permissionIds,false))}
function saveRole(){role.permissionIds=(permissionTreeRef.value?.getCheckedKeys(false)||[]).filter((id:any)=>typeof id==='number');const method=editing.value?'PUT':'POST',target=editing.value?`/governance/roles/${editing.value.id}`:'/governance/roles';const body:any={name:role.name,description:role.description,sortOrder:role.sortOrder,status:role.status,permissionIds:[...role.permissionIds]};if(editing.value)body.version=role.version;else body.code=role.code;return mutate(method,target,body,editing.value?'修改角色权限':'创建角色')}
function openTag(row:any=null){editing.value=row;Object.assign(tag,row?{name:row.name,color:row.color,group:row.group,status:row.status}:{name:'',color:'#409EFF',group:'默认分组',status:1});dialog.value='tag'}
function saveTag(){return mutate(editing.value?'PUT':'POST',editing.value?`/governance/tags/${editing.value.id}`:'/governance/tags',{...tag},editing.value?'修改标签':'创建标签')}
function openDictionary(row:any=null){editing.value=row;Object.assign(dictionary,row?{name:row.name,code:row.code,description:row.description||'',status:row.status}:{name:'',code:'',description:'',status:1});dialog.value='dictionary'}
function saveDictionary(){const body:any={name:dictionary.name,description:dictionary.description,status:dictionary.status};if(!editing.value)body.code=dictionary.code;return mutate(editing.value?'PUT':'POST',editing.value?`/governance/dictionaries/${editing.value.id}`:'/governance/dictionaries',body,editing.value?'修改字典':'创建字典')}
function openItem(row:any=null,dictionaryId:number|null=null){editing.value=row;Object.assign(item,row?{dictionaryId:row.dictionaryId,label:row.label,value:row.value,sortOrder:row.sortOrder,status:row.status}:{dictionaryId,label:'',value:'',sortOrder:0,status:1});dialog.value='item'}
function saveItem(){const body:any={label:item.label,value:item.value,sortOrder:item.sortOrder,status:item.status};if(!editing.value)body.dictionaryId=item.dictionaryId;return mutate(editing.value?'PUT':'POST',editing.value?`/governance/dictionary-items/${editing.value.id}`:'/governance/dictionary-items',body,editing.value?'修改字典项':'创建字典项')}
function openMenu(row:any=null){editing.value=row;Object.assign(menu,row?{name:row.name,code:row.code,route:row.route||'',icon:row.icon||'',permissionCode:row.permissionCode||'',parentId:row.parentId,sortOrder:row.sortOrder,status:row.status}:{name:'',code:'',route:'',icon:'',permissionCode:'',parentId:null,sortOrder:0,status:1});dialog.value='menu'}
function saveMenu(){const body:any={name:menu.name,route:menu.route||null,icon:menu.icon||null,permissionCode:menu.permissionCode||null,parentId:menu.parentId,sortOrder:menu.sortOrder,status:menu.status};if(!editing.value)body.code=menu.code;return mutate(editing.value?'PUT':'POST',editing.value?`/governance/menus/${editing.value.id}`:'/governance/menus',body,editing.value?'修改菜单':'创建菜单')}
function openDataScope(row:any=null){editing.value=row;Object.assign(dataScope,row?{name:row.name,code:row.code,type:row.type,description:row.description||'',active:row.active,version:row.version}:{name:'',code:'',type:'PROJECT',description:'',active:true,version:1});dialog.value='dataScope'}
function saveDataScope(){const body:any={name:dataScope.name,type:dataScope.type,description:dataScope.description,active:dataScope.active};if(editing.value)body.version=dataScope.version;else body.code=dataScope.code;return mutate(editing.value?'PUT':'POST',editing.value?`/governance/data-scopes/${editing.value.id}`:'/governance/data-scopes',body,editing.value?'修改数据域':'创建数据域')}
async function removeDataScope(row:any){const {value}=await ElMessageBox.prompt('请输入删除原因','删除数据域',{type:'warning',inputPattern:/\S+/,inputErrorMessage:'原因不能为空'});await mutate('DELETE',`/governance/data-scopes/${row.id}`,{reason:value,version:row.version},'删除数据域')}
function openMapping(row:any=null){mapping.scientificId=row?.id||scientific.value[0]?.id||null;mapping.industryCategoryIds=overview.value.categoryMappings.filter((v:any)=>v.scientificCategoryId===mapping.scientificId).map((v:any)=>v.industryCategoryId);dialog.value='mapping'}
function mappingChanged(){mapping.industryCategoryIds=overview.value.categoryMappings.filter((v:any)=>v.scientificCategoryId===mapping.scientificId).map((v:any)=>v.industryCategoryId)}
function saveMapping(){return mutate('PUT',`/governance/category-mappings/${mapping.scientificId}`,{industryCategoryIds:[...mapping.industryCategoryIds]},'修改分类映射')}
function saveUi(){return mutate('PUT','/governance/ui-config',{primaryColor:ui.primaryColor,fontSize:ui.fontSize,borderRadius:ui.borderRadius,contentSpacing:ui.contentSpacing,version:ui.version},'修改全局界面配置')}
function syncRouteTab(){const path=route.path;activeTab.value=path.includes('/dictionaries')?'dictionaries':path.includes('/system/roles')?'roles':path.includes('/system/scopes')?'scopes':path.includes('/system/menus')?'menus':path.includes('/system/settings')?'ui':'scientific'}
watch(()=>route.path,syncRouteTab);onMounted(()=>{syncRouteTab();load()})
</script>

<template><div class="page" v-loading="loading"><div class="page-head"><div><h1 class="page-title">治理配置</h1><div class="page-subtitle">科学/产业分类、组织角色、标签字典、动态菜单与全局界面参数</div></div><el-button @click="load">刷新</el-button></div>
 <el-tabs v-model="activeTab">
  <el-tab-pane label="科学分类" name="scientific"><div class="toolbar"><el-button v-if="canClassify" type="primary" @click="openCategory('SCIENTIFIC')">新增科学分类</el-button><el-button v-if="canClassify" @click="openMapping()">分类映射</el-button></div><div class="surface tree-box"><el-tree :data="scientificTree" node-key="id" default-expand-all><template #default="{data}"><div class="tree-row"><span><b>{{data.name}}</b><small>{{data.code}} · 关联数据 {{data.datasetCount}}</small></span><span><el-tag :type="data.status?'success':'info'">{{data.status?'启用':'停用'}}</el-tag><el-button v-if="canClassify" link @click.stop="openCategory('SCIENTIFIC',data)">编辑</el-button><el-button v-if="canClassify" link type="danger" @click.stop="remove(`/governance/categories/${data.id}`,'删除科学分类')">删除</el-button></span></div></template></el-tree></div></el-tab-pane>
  <el-tab-pane label="产业分类" name="industry"><div class="toolbar"><el-button v-if="canClassify" type="primary" @click="openCategory('INDUSTRY')">新增产业分类</el-button></div><div class="surface tree-box"><el-tree :data="industryTree" node-key="id" default-expand-all><template #default="{data}"><div class="tree-row"><span><b>{{data.name}}</b><small>{{data.code}} · 产品代码 {{(data.productCodes||[]).join(', ')||'—'}}</small></span><span><el-tag :type="data.status?'success':'info'">{{data.status?'启用':'停用'}}</el-tag><el-button v-if="canClassify" link @click.stop="openCategory('INDUSTRY',data)">编辑</el-button><el-button v-if="canClassify" link type="danger" @click.stop="remove(`/governance/categories/${data.id}`,'删除产业分类')">删除</el-button></span></div></template></el-tree></div></el-tab-pane>
  <el-tab-pane v-if="auth.can('organization:manage')||auth.can('user:manage')" label="部门" name="departments"><div class="toolbar"><el-button v-if="auth.can('organization:manage')" type="primary" @click="openDepartment()">新增部门</el-button></div><div class="surface tree-box"><el-tree :data="departmentTree" node-key="id" default-expand-all><template #default="{data}"><div class="tree-row"><span><b>{{data.name}}</b><small>{{data.code}} · {{data.leaderName||'未指定负责人'}} · {{data.userCount}} 人</small></span><span><el-button v-if="auth.can('organization:manage')" link @click.stop="openDepartment(data)">编辑</el-button><el-button v-if="auth.can('organization:manage')" link type="danger" @click.stop="remove(`/governance/departments/${data.id}`,'删除部门')">删除</el-button></span></div></template></el-tree></div></el-tab-pane>
  <el-tab-pane v-if="auth.can('role:manage')" label="角色权限" name="roles"><div class="toolbar"><el-button v-if="canAssignPermissions" type="primary" @click="openRole()">新增角色</el-button></div><div class="surface"><el-table :data="roles"><el-table-column prop="name" label="角色"/><el-table-column prop="code" label="编码"/><el-table-column prop="description" label="说明"/><el-table-column prop="userCount" label="用户数" width="90"/><el-table-column label="权限数" width="90"><template #default="{row}">{{row.permissionIds.length}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status?'success':'info'">{{row.status?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button v-if="canAssignPermissions" link @click="openRole(row)">编辑</el-button><el-button v-if="canAssignPermissions" link type="danger" @click="remove(`/governance/roles/${row.id}`,'删除角色')">删除</el-button></template></el-table-column></el-table></div></el-tab-pane>
  <el-tab-pane v-if="canDataScope" label="数据域" name="scopes"><div class="toolbar"><el-button type="primary" @click="openDataScope()">新增数据域</el-button></div><div class="surface"><el-table :data="dataScopes"><el-table-column prop="name" label="名称"/><el-table-column prop="code" label="编码"/><el-table-column prop="type" label="类型"/><el-table-column prop="userCount" label="用户数" width="80"/><el-table-column prop="resourceCount" label="资源数" width="80"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.active?'success':'info'">{{row.active?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link @click="openDataScope(row)">编辑</el-button><el-button link type="danger" @click="removeDataScope(row)">删除</el-button></template></el-table-column></el-table></div></el-tab-pane>
  <el-tab-pane label="数据标签" name="tags"><div class="toolbar"><el-button v-if="canTag" type="primary" @click="openTag()">新增标签</el-button></div><div class="surface"><el-table :data="overview.tags"><el-table-column label="标签"><template #default="{row}"><el-tag :color="row.color" effect="dark">{{row.name}}</el-tag></template></el-table-column><el-table-column prop="group" label="分组"/><el-table-column prop="usageCount" label="使用次数"/><el-table-column prop="createdTime" label="创建时间"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button v-if="canTag" link @click="openTag(row)">编辑</el-button><el-button v-if="canTag" link type="danger" @click="remove(`/governance/tags/${row.id}`,'删除标签')">删除</el-button></template></el-table-column></el-table></div></el-tab-pane>
  <el-tab-pane label="数据字典" name="dictionaries"><div class="dict-grid"><div class="surface"><div class="toolbar"><el-button v-if="canDictionary" type="primary" @click="openDictionary()">新增字典</el-button></div><el-table :data="overview.dictionaries" highlight-current-row @current-change="(row:any)=>item.dictionaryId=row?.id"><el-table-column prop="name" label="字典"/><el-table-column prop="code" label="编码"/><el-table-column prop="itemCount" label="项数" width="70"/><el-table-column label="操作" width="130"><template #default="{row}"><el-button v-if="canDictionary" link @click.stop="openDictionary(row)">编辑</el-button><el-button v-if="canDictionary" link type="danger" @click.stop="remove(`/governance/dictionaries/${row.id}`,'删除字典')">删除</el-button></template></el-table-column></el-table></div><div class="surface"><div class="toolbar"><b>字典项</b><el-button v-if="canDictionary&&item.dictionaryId" type="primary" @click="openItem(null,item.dictionaryId)">新增字典项</el-button></div><el-table :data="dictionaryItems"><el-table-column prop="label" label="名称"/><el-table-column prop="value" label="值"/><el-table-column prop="sortOrder" label="排序" width="70"/><el-table-column label="状态" width="80"><template #default="{row}">{{row.status?'启用':'停用'}}</template></el-table-column><el-table-column label="操作" width="130"><template #default="{row}"><el-button v-if="canDictionary" link @click="openItem(row)">编辑</el-button><el-button v-if="canDictionary" link type="danger" @click="remove(`/governance/dictionary-items/${row.id}`,'删除字典项')">删除</el-button></template></el-table-column></el-table></div></div></el-tab-pane>
  <el-tab-pane label="菜单管理" name="menus"><div class="toolbar"><el-button v-if="canMenu" type="primary" @click="openMenu()">新增菜单</el-button></div><div class="surface tree-box"><el-tree :data="menuTree" node-key="id" default-expand-all><template #default="{data}"><div class="tree-row"><span><b>{{data.icon}} {{data.name}}</b><small>{{data.route||'目录'}} · {{data.permissionCode||'登录可见'}}</small></span><span><el-tag :type="data.status?'success':'info'">{{data.status?'显示':'隐藏'}}</el-tag><el-button v-if="canMenu" link @click.stop="openMenu(data)">编辑</el-button><el-button v-if="canMenu" link type="danger" @click.stop="remove(`/governance/menus/${data.id}`,'删除菜单')">删除</el-button></span></div></template></el-tree></div></el-tab-pane>
  <el-tab-pane label="界面管理" name="ui"><div class="surface settings"><el-form label-position="top"><el-form-item label="平台主色"><el-color-picker v-model="ui.primaryColor"/></el-form-item><el-form-item label="基础字号"><el-slider v-model="ui.fontSize" :min="12" :max="20" show-input/></el-form-item><el-form-item label="圆角"><el-slider v-model="ui.borderRadius" :min="0" :max="24" show-input/></el-form-item><el-form-item label="内容间距"><el-slider v-model="ui.contentSpacing" :min="8" :max="40" show-input/></el-form-item><div class="preview" :style="{color:ui.primaryColor,fontSize:`${ui.fontSize}px`,borderRadius:`${ui.borderRadius}px`,padding:`${ui.contentSpacing}px`}">全局界面参数实时预览</div><el-button v-if="canUi" type="primary" @click="saveUi">保存并全局生效</el-button></el-form></div></el-tab-pane>
 </el-tabs>

 <el-dialog :model-value="dialogVisible" :title="editing?'编辑治理项':'新增治理项'" width="640" @update:model-value="(value:boolean)=>{if(!value)closeDialog()}">
  <el-form v-if="dialog==='category'" label-position="top"><el-form-item label="分类类型"><el-select v-model="category.type" disabled><el-option label="科学分类" value="SCIENTIFIC"/><el-option label="产业分类" value="INDUSTRY"/></el-select></el-form-item><div class="form-grid"><el-form-item label="名称"><el-input v-model="category.name"/></el-form-item><el-form-item label="编码"><el-input v-model="category.code"/></el-form-item><el-form-item label="上级"><el-select v-model="category.parentId" clearable><el-option v-for="v in category.type==='SCIENTIFIC'?scientific:industry" :key="v.id" :label="v.name" :value="v.id" :disabled="editing?.id===v.id"/></el-select></el-form-item><el-form-item label="排序"><el-input-number v-model="category.sortOrder"/></el-form-item></div><el-form-item v-if="category.type==='INDUSTRY'" label="产品代码（逗号分隔）"><el-input v-model="category.productCodes"/></el-form-item><el-switch v-model="category.status" :active-value="1" :inactive-value="0" active-text="启用"/></el-form>
  <el-form v-else-if="dialog==='department'" label-position="top"><div class="form-grid"><el-form-item label="名称"><el-input v-model="department.name"/></el-form-item><el-form-item label="编码"><el-input v-model="department.code"/></el-form-item><el-form-item label="上级部门"><el-select v-model="department.parentId" clearable><el-option v-for="v in departments" :key="v.id" :label="v.name" :value="v.id" :disabled="editing?.id===v.id"/></el-select></el-form-item><el-form-item label="部门负责人"><el-select v-model="department.leaderId" clearable filterable><el-option v-for="v in departmentLeaders" :key="v.id" :label="`${v.name} (${v.username})`" :value="v.id"/></el-select></el-form-item><el-form-item label="排序"><el-input-number v-model="department.sortOrder"/></el-form-item></div><el-switch v-model="department.status" :active-value="1" :inactive-value="0" active-text="启用"/></el-form>
  <el-form v-else-if="dialog==='role'" label-position="top"><div class="form-grid"><el-form-item label="名称"><el-input v-model="role.name"/></el-form-item><el-form-item label="编码"><el-input v-model="role.code" :disabled="!!editing"/></el-form-item></div><el-form-item label="说明"><el-input v-model="role.description"/></el-form-item><el-form-item label="菜单与功能权限树"><el-tree ref="permissionTreeRef" :data="permissionTree" node-key="id" show-checkbox default-expand-all :props="{label:'name',children:'children'}"><template #default="{data}"><span>{{data.name}}<small v-if="data.code"> · {{data.code}}</small></span></template></el-tree></el-form-item><el-switch v-model="role.status" :active-value="1" :inactive-value="0" active-text="启用"/></el-form>
  <el-form v-else-if="dialog==='tag'" label-position="top"><el-form-item label="标签名称"><el-input v-model="tag.name"/></el-form-item><div class="form-grid"><el-form-item label="分组"><el-input v-model="tag.group"/></el-form-item><el-form-item label="颜色"><el-color-picker v-model="tag.color"/></el-form-item></div><el-switch v-model="tag.status" :active-value="1" :inactive-value="0" active-text="启用"/></el-form>
  <el-form v-else-if="dialog==='dictionary'" label-position="top"><div class="form-grid"><el-form-item label="字典名称"><el-input v-model="dictionary.name"/></el-form-item><el-form-item label="编码"><el-input v-model="dictionary.code" :disabled="!!editing"/></el-form-item></div><el-form-item label="说明"><el-input v-model="dictionary.description" type="textarea"/></el-form-item><el-switch v-model="dictionary.status" :active-value="1" :inactive-value="0" active-text="启用"/></el-form>
  <el-form v-else-if="dialog==='item'" label-position="top"><div class="form-grid"><el-form-item label="名称"><el-input v-model="item.label"/></el-form-item><el-form-item label="值"><el-input v-model="item.value"/></el-form-item><el-form-item label="排序"><el-input-number v-model="item.sortOrder"/></el-form-item></div><el-switch v-model="item.status" :active-value="1" :inactive-value="0" active-text="启用"/></el-form>
  <el-form v-else-if="dialog==='menu'" label-position="top"><div class="form-grid"><el-form-item label="名称"><el-input v-model="menu.name"/></el-form-item><el-form-item label="编码"><el-input v-model="menu.code" :disabled="!!editing"/></el-form-item><el-form-item label="路由"><el-input v-model="menu.route"/></el-form-item><el-form-item label="图标"><el-input v-model="menu.icon"/></el-form-item><el-form-item label="权限标识（多个用 | 表示任一权限）"><el-select v-model="menu.permissionCode" clearable filterable allow-create><el-option v-for="p in permissions" :key="p.id" :label="p.code" :value="p.code"/></el-select></el-form-item><el-form-item label="上级菜单"><el-select v-model="menu.parentId" clearable><el-option v-for="v in overview.menus" :key="v.id" :label="v.name" :value="v.id" :disabled="editing?.id===v.id"/></el-select></el-form-item><el-form-item label="排序"><el-input-number v-model="menu.sortOrder"/></el-form-item></div><el-switch v-model="menu.status" :active-value="1" :inactive-value="0" active-text="显示"/></el-form>
  <el-form v-else-if="dialog==='dataScope'" label-position="top"><div class="form-grid"><el-form-item label="名称"><el-input v-model="dataScope.name"/></el-form-item><el-form-item label="编码"><el-input v-model="dataScope.code" :disabled="!!editing"/></el-form-item><el-form-item label="类型"><el-select v-model="dataScope.type"><el-option label="全局" value="GLOBAL"/><el-option label="部门" value="DEPARTMENT"/><el-option label="研发项目" value="PROJECT"/><el-option label="产品线" value="PRODUCT_LINE"/></el-select></el-form-item></div><el-form-item label="说明"><el-input v-model="dataScope.description" type="textarea"/></el-form-item><el-switch v-model="dataScope.active" active-text="启用"/></el-form>
  <el-form v-else-if="dialog==='mapping'" label-position="top"><el-form-item label="科学分类"><el-select v-model="mapping.scientificId" @change="mappingChanged"><el-option v-for="v in scientific" :key="v.id" :label="v.name" :value="v.id"/></el-select></el-form-item><el-form-item label="关联产业分类"><el-select v-model="mapping.industryCategoryIds" multiple><el-option v-for="v in industry" :key="v.id" :label="v.name" :value="v.id"/></el-select></el-form-item></el-form>
  <template #footer><el-button @click="closeDialog">取消</el-button><el-button type="primary" @click="dialog==='category'?saveCategory():dialog==='department'?saveDepartment():dialog==='role'?saveRole():dialog==='tag'?saveTag():dialog==='dictionary'?saveDictionary():dialog==='item'?saveItem():dialog==='menu'?saveMenu():dialog==='dataScope'?saveDataScope():saveMapping()">保存</el-button></template>
 </el-dialog>
</div></template>

<style scoped>
.toolbar{display:flex;justify-content:flex-end;gap:8px;margin-bottom:12px}
.tree-box{padding:14px}
.tree-box :deep(.el-tree){background:transparent;color:var(--tech-text)}
.tree-box :deep(.el-tree-node__content){height:auto;min-height:58px;padding:0 12px;border-bottom:1px solid rgba(91,184,255,.1)}
.tree-box :deep(.el-tree-node__content:hover){background:rgba(24,73,99,.28)}
.tree-box :deep(.el-tree-node:focus>.el-tree-node__content){background:rgba(24,73,99,.34)}
.tree-box :deep(.el-tree-node__expand-icon){flex:0 0 auto;color:#4d819e}
.tree-row{width:100%;min-width:0;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:10px 4px}
.tree-row>span:first-child{min-width:0}
.tree-row>span:last-child{flex:0 0 auto;display:flex;align-items:center;gap:4px}
.tree-row b,.tree-row small{display:block}
.tree-row b{color:#c7ddeb;line-height:1.4}
.tree-row small{font-size:11px;line-height:1.45;color:#8190a3;margin-top:3px;overflow-wrap:anywhere}
.dict-grid{display:grid;grid-template-columns:1fr 1.25fr;gap:14px}
.dict-grid .surface{padding:12px}
.settings{max-width:760px;padding:24px}
.preview{border:1px solid currentColor;margin:12px 0 20px;background:#f6fbfd}
.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.el-select{width:100%}
@media(max-width:800px){
  .dict-grid,.form-grid{grid-template-columns:1fr}
  .tree-box{padding:8px}
  .tree-box :deep(.el-tree-node__content){padding-right:6px}
  .tree-row{align-items:flex-start;gap:8px}
  .tree-row>span:last-child{gap:0}
}
</style>
