<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {http,dataOf} from '../api/http'
import {useAuthStore} from '../stores/auth'

const auth=useAuthStore(),loading=ref(false),policies=ref<any[]>([]),candidates=ref<any[]>([]),items=ref<any[]>([]),holds=ref<any[]>([]),datasets=ref<any[]>([]),governanceOptions=ref<any>({dictionaries:[],dictionaryItems:[]})
const importanceOptions=computed(()=>{const dictionary=governanceOptions.value.dictionaries.find((v:any)=>v.code==='DATA_IMPORTANCE');return governanceOptions.value.dictionaryItems.filter((v:any)=>v.dictionaryId===dictionary?.id)})
const archiveKeyword=ref(''),archiveState=ref(''),archivePage=ref(1),archivePageSize=ref(20),archiveTotal=ref(0)
const policyDialog=ref(false),holdDialog=ref(false),importanceDialog=ref(false),reconciling=ref(false)
const policy=reactive<any>({id:null,importanceLevel:'NORMAL',dataScopeId:null,onlineDays:365,archiveTarget:'PRIMARY_BACKUP',autoArchive:false,active:true,version:null})
const hold=reactive<any>({datasetId:null,recordId:'',reason:'质量调查期间禁止归档',validTo:null})
const importance=reactive<any>({datasetId:null,importanceLevel:'NORMAL'})
const scopeIds=()=>auth.user?.assignedScopes||[]
async function loadItems(reset=false){if(reset)archivePage.value=1;const response=await http.get('/lifecycle/items',{params:{pageNum:archivePage.value,pageSize:archivePageSize.value,state:archiveState.value||undefined,keyword:archiveKeyword.value||undefined}}),page=dataOf<any>(response);items.value=page.list;archiveTotal.value=page.total}
async function load(){loading.value=true;try{const [p,c,h,o]=await Promise.all([http.get('/lifecycle/policies'),http.get('/lifecycle/preview',{params:{limit:200}}),http.get('/lifecycle/holds'),http.get('/governance/options')]);policies.value=dataOf(p);candidates.value=dataOf(c);holds.value=dataOf(h);governanceOptions.value=dataOf<any>(o);await loadItems();if(auth.can('dataset:read')&&auth.can('lifecycle:manage')){const d=await http.get('/datasets',{params:{pageSize:100}});datasets.value=dataOf<any>(d).list}else datasets.value=[]}finally{loading.value=false}}
function editPolicy(row?:any){Object.assign(policy,row?{...row}:{id:null,importanceLevel:'NORMAL',dataScopeId:null,onlineDays:365,archiveTarget:'PRIMARY_BACKUP',autoArchive:false,active:true,version:null});policyDialog.value=true}
async function savePolicy(){const body={importanceLevel:policy.importanceLevel,dataScopeId:policy.dataScopeId,onlineDays:policy.onlineDays,archiveTarget:policy.archiveTarget,autoArchive:policy.autoArchive,active:policy.active,version:policy.version};if(policy.id)await http.put(`/lifecycle/policies/${policy.id}`,body);else await http.post('/lifecycle/policies',body);ElMessage.success('生命周期策略已保存');policyDialog.value=false;await load()}
async function archive(row:any){await ElMessageBox.confirm(`归档“${row.datasetName}”记录 ${row.recordId.slice(-10)}？系统会先写入备份ZIP并校验摘要，再迁移Mongo记录与GridFS附件。`,'执行受控归档',{type:'warning'});await http.post('/lifecycle/archive',{datasetId:row.datasetId,recordId:row.recordId});ElMessage.success('归档完成，原记录可从归档清单恢复');await load()}
function openHold(row?:any){Object.assign(hold,{datasetId:row?.datasetId||null,recordId:row?.recordId||'',reason:'质量调查期间禁止归档',validTo:null});holdDialog.value=true}
async function createHold(){await http.post('/lifecycle/holds',{...hold,validTo:hold.validTo instanceof Date?hold.validTo.toISOString():hold.validTo});ElMessage.success('保留例外已生效');holdDialog.value=false;await load()}
async function releaseHold(row:any){const {value}=await ElMessageBox.prompt('请输入解除原因','解除保留例外',{inputPattern:/\S+/,inputErrorMessage:'原因不能为空'});await http.post(`/lifecycle/holds/${row.id}/release`,{version:row.version,reason:value});ElMessage.success('保留例外已解除');await load()}
async function restore(row:any){await ElMessageBox.confirm('恢复前将重新校验归档文件SHA-256，并按原ID恢复Mongo记录和附件。确认继续？','恢复归档',{type:'warning'});await http.post(`/lifecycle/items/${row.id}/restore`);ElMessage.success('记录已恢复到在线存储');await load()}
async function retry(row:any){await http.post(`/lifecycle/items/${row.id}/retry`);ElMessage.success('失败作业已重试');await load()}
function openImportance(row?:any){Object.assign(importance,{datasetId:row?.id||datasets.value[0]?.id||null,importanceLevel:row?.importanceLevel||'NORMAL'});importanceDialog.value=true}
async function saveImportance(){await http.put(`/lifecycle/datasets/${importance.datasetId}/importance`,{importanceLevel:importance.importanceLevel});ElMessage.success('数据重要性已更新');importanceDialog.value=false;await load()}
async function reconcile(){await ElMessageBox.confirm('将检查并安全回收长时间停留在归档或恢复中的转换，同时清理已完成转换的临时内容。确认执行？','手工生命周期对账',{type:'warning'});reconciling.value=true;try{const result=dataOf<any>(await http.post('/lifecycle/reconcile'));ElMessage.success(`对账完成：归档回收 ${result.recoveredArchiving||0}，恢复回收 ${result.recoveredRestoring||0}，清理 ${result.completedCleanup||0}`);await load()}finally{reconciling.value=false}}
function stateType(value:string){return value==='ARCHIVED'?'success':value==='FAILED'?'danger':value==='ARCHIVING'||value==='RESTORING'?'warning':'info'}
onMounted(load)
</script>

<template><div class="page"><div class="page-head"><div><h1 class="page-title">数据生命周期</h1><div class="page-subtitle">按重要性和保存期自动归档，使用可挂载备份目录、清单与 SHA-256 实现可验证恢复</div></div><div><el-button v-if="auth.user?.roles.includes('ADMIN')" :loading="reconciling" @click="reconcile">手工对账</el-button><el-button v-if="auth.can('lifecycle:manage')" @click="openImportance()">设置数据重要性</el-button><el-button v-if="auth.can('lifecycle:manage')" type="primary" @click="editPolicy()">新建策略</el-button><el-button @click="load">刷新</el-button></div></div>
 <el-alert title="生产部署请把 RDP_ARCHIVE_ROOT 挂载到独立备份服务器/NAS，并按已批准的 RPO/RTO 定期执行恢复演练。系统不会把“同机目录”宣称为异地备份。" type="warning" :closable="false" style="margin-bottom:14px"/>
 <el-tabs v-loading="loading"><el-tab-pane label="到期预览"><div class="surface"><el-table :data="candidates"><el-table-column prop="datasetName" label="数据集"/><el-table-column label="记录" width="150"><template #default="{row}"><span class="mono">{{row.recordId.slice(-10)}}</span></template></el-table-column><el-table-column prop="importanceLevel" label="重要性" width="100"/><el-table-column prop="businessTime" label="业务时间" width="180"/><el-table-column prop="onlineDays" label="在线保存(天)" width="120"/><el-table-column prop="archiveTarget" label="目标"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button v-if="auth.can('lifecycle:archive')" link type="warning" @click="archive(row)">归档</el-button><el-button v-if="auth.can('lifecycle:hold')" link @click="openHold(row)">保留例外</el-button></template></el-table-column></el-table><div v-if="!candidates.length" class="empty-note">当前没有到期且可归档的已发布记录</div></div></el-tab-pane>
  <el-tab-pane label="归档清单"><div class="surface"><div class="archive-search"><el-input v-model="archiveKeyword" clearable maxlength="100" placeholder="按数据集、记录ID或归档字段检索" @keyup.enter="loadItems(true)"/><el-select v-model="archiveState" clearable placeholder="全部状态" @change="loadItems(true)"><el-option v-for="state in ['ARCHIVED','ONLINE','FAILED','ARCHIVING','RESTORING','SUPERSEDED']" :key="state" :value="state"/></el-select><el-button type="primary" @click="loadItems(true)">检索归档</el-button></div><el-table :data="items"><el-table-column prop="datasetName" label="数据集"/><el-table-column label="记录" width="145"><template #default="{row}"><span class="mono">{{row.recordId.slice(-10)}}</span></template></el-table-column><el-table-column label="状态" width="105"><template #default="{row}"><el-tag :type="stateType(row.state)">{{row.state}}</el-tag></template></el-table-column><el-table-column prop="archiveTarget" label="归档目标"/><el-table-column label="摘要" min-width="180"><template #default="{row}"><span class="mono digest">{{row.archiveDigest||'—'}}</span></template></el-table-column><el-table-column prop="archivedTime" label="归档时间" width="180"/><el-table-column prop="errorMessage" label="错误"/><el-table-column label="操作" width="120"><template #default="{row}"><el-button v-if="row.state==='ARCHIVED'&&auth.can('lifecycle:restore')" link type="success" @click="restore(row)">校验并恢复</el-button><el-button v-if="row.state==='FAILED'&&((row.retryOperation==='ARCHIVE'&&auth.can('lifecycle:archive'))||(row.retryOperation==='RESTORE'&&auth.can('lifecycle:restore')))" link type="warning" @click="retry(row)">重试</el-button></template></el-table-column></el-table><el-pagination v-if="archiveTotal>archivePageSize" v-model:current-page="archivePage" v-model:page-size="archivePageSize" :total="archiveTotal" :page-sizes="[10,20,50,100]" layout="total, sizes, prev, pager, next" style="margin-top:16px" @current-change="loadItems()" @size-change="loadItems(true)"/></div></el-tab-pane>
  <el-tab-pane label="保存策略"><div class="surface"><el-table :data="policies"><el-table-column prop="dataScopeName" label="数据域"><template #default="{row}">{{row.dataScopeName||'全局默认'}}</template></el-table-column><el-table-column prop="importanceLevel" label="重要性"/><el-table-column prop="onlineDays" label="在线天数"/><el-table-column prop="archiveTarget" label="归档目标"/><el-table-column label="自动归档"><template #default="{row}">{{row.autoArchive?'是':'否'}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.active?'success':'info'">{{row.active?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="version" label="版本"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="auth.can('lifecycle:manage')" link @click="editPolicy(row)">编辑</el-button></template></el-table-column></el-table></div></el-tab-pane>
  <el-tab-pane label="保留例外"><div class="surface"><el-table :data="holds"><el-table-column prop="datasetName" label="数据集"/><el-table-column prop="resourceRef" label="资源"/><el-table-column prop="reason" label="原因"/><el-table-column prop="validTo" label="有效至"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.active?'warning':'info'">{{row.active?'生效':'已解除'}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.active&&auth.can('lifecycle:hold')" link type="danger" @click="releaseHold(row)">解除</el-button></template></el-table-column></el-table></div></el-tab-pane></el-tabs>

 <el-dialog v-model="policyDialog" :title="policy.id?'编辑生命周期策略':'新建生命周期策略'" width="620"><el-form label-position="top"><div class="grid"><el-form-item label="数据域（空=全局默认）"><el-select v-model="policy.dataScopeId" clearable><el-option v-for="scope in scopeIds()" :key="scope" :label="`数据域 #${scope}`" :value="scope"/></el-select></el-form-item><el-form-item label="重要性"><el-select v-model="policy.importanceLevel"><el-option v-for="option in importanceOptions" :key="option.id" :label="option.label" :value="option.value"/></el-select></el-form-item><el-form-item label="在线保存天数"><el-input-number v-model="policy.onlineDays" :min="0" :max="36500"/></el-form-item><el-form-item label="归档目标标识"><el-input v-model="policy.archiveTarget"/></el-form-item></div><el-form-item><el-checkbox v-model="policy.autoArchive">到期自动归档</el-checkbox><el-checkbox v-model="policy.active">策略启用</el-checkbox></el-form-item></el-form><template #footer><el-button @click="policyDialog=false">取消</el-button><el-button type="primary" @click="savePolicy">保存</el-button></template></el-dialog>
 <el-dialog v-model="holdDialog" title="创建数据保留例外" width="560"><el-form label-position="top"><el-form-item label="数据集"><el-select v-model="hold.datasetId"><el-option v-for="row in datasets" :key="row.id" :label="row.name" :value="row.id"/></el-select></el-form-item><el-form-item label="记录ID"><el-input v-model="hold.recordId" class="mono"/></el-form-item><el-form-item label="保留原因"><el-input v-model="hold.reason" type="textarea"/></el-form-item><el-form-item label="有效至（空=人工解除）"><el-date-picker v-model="hold.validTo" type="datetime" style="width:100%"/></el-form-item></el-form><template #footer><el-button @click="holdDialog=false">取消</el-button><el-button type="primary" @click="createHold">创建</el-button></template></el-dialog>
 <el-dialog v-model="importanceDialog" title="设置数据集重要性" width="520"><el-form label-position="top"><el-form-item label="数据集"><el-select v-model="importance.datasetId"><el-option v-for="row in datasets" :key="row.id" :label="`${row.name} · ${row.importanceLevel||'NORMAL'}`" :value="row.id"/></el-select></el-form-item><el-form-item label="重要性"><el-select v-model="importance.importanceLevel"><el-option v-for="option in importanceOptions" :key="option.id" :label="option.label" :value="option.value"/></el-select></el-form-item></el-form><template #footer><el-button @click="importanceDialog=false">取消</el-button><el-button type="primary" @click="saveImportance">保存</el-button></template></el-dialog>
</div></template>
<style scoped>.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.el-select{width:100%}.digest{font-size:9px;word-break:break-all}.archive-search{display:flex;gap:10px;max-width:620px;margin-bottom:14px}@media(max-width:700px){.grid{grid-template-columns:1fr}.archive-search{flex-direction:column}}</style>
