<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue';import {useRouter} from 'vue-router';import {useAuthStore} from '../stores/auth';import {http,dataOf} from '../api/http'
const router=useRouter(),auth=useAuthStore(),loading=ref(false),captcha=ref(''),registrationEnabled=ref(false);const form=reactive({username:'',password:'',captchaKey:'',captchaCode:''})
async function loadCaptcha(){const data=dataOf<any>(await http.get('/auth/captcha'));form.captchaKey=data.captchaKey;captcha.value=data.image;form.captchaCode=''}
async function submit(){loading.value=true;try{await auth.login(form);router.push(auth.user?.mustChangePassword?'/change-password':'/dashboard')}catch{loadCaptcha()}finally{loading.value=false}}
onMounted(async()=>{await loadCaptcha();try{registrationEnabled.value=dataOf<any>(await http.get('/auth/registration-settings')).enabled===true}catch{registrationEnabled.value=false}})
</script>
<template><div class="login"><section class="story"><div class="story-inner"><div class="logo">J</div><p class="eyebrow">JUSTEAM DATA FABRIC</p><h1>让研发证据与生产事实<br/>在一条可信链路上汇合</h1><p class="lead">统一管理材料、工艺、设备、产品和质量数据，构建面向医疗器械制造的可追溯数字底座。</p><div class="feature-grid"><div><b>全域数据治理</b><span>模板、数据集与数据域统一控制</span></div><div><b>材料到产品追溯</b><span>正向与反向证据链清晰可查</span></div><div><b>ALCOA+ 审计</b><span>追加写入、签名链与受控更正</span></div><div><b>多源实时采集</b><span>PostgreSQL · MongoDB · Redis</span></div></div></div><div class="orb one"></div><div class="orb two"></div></section>
 <section class="form-side"><div class="login-card"><p class="welcome">欢迎回来</p><h2>登录数据工作台</h2><p class="hint">请输入您的平台账号和安全验证码</p><el-form label-position="top" @keyup.enter="submit"><el-form-item label="账号"><el-input v-model="form.username" size="large" autocomplete="username" placeholder="请输入用户名"/></el-form-item><el-form-item label="密码"><el-input v-model="form.password" size="large" type="password" autocomplete="current-password" show-password placeholder="请输入密码"/></el-form-item><el-form-item label="安全验证"><div class="captcha-row"><el-input v-model="form.captchaCode" size="large" placeholder="计算结果"/><img :src="captcha" @click="loadCaptcha" alt="验证码"/></div></el-form-item><el-button type="primary" size="large" :loading="loading" class="submit" @click="submit">进入平台</el-button></el-form><div class="login-foot"><router-link v-if="registrationEnabled" to="/register">申请平台账号</router-link><span v-else>账号由管理员统一分配</span><span>数据访问全程留痕</span></div></div></section>
</div></template>
<style scoped>
.login{min-height:100vh;display:grid;grid-template-columns:1.15fr .85fr;background:#fff}.story{position:relative;overflow:hidden;background:radial-gradient(circle at 20% 20%,#1d5a82,#102f50 45%,#071a2e);color:#fff;display:grid;place-items:center}.story:before{content:"";position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px);background-size:48px 48px}.story-inner{width:68%;position:relative;z-index:2}.logo{width:50px;height:50px;display:grid;place-items:center;border-radius:14px;background:linear-gradient(135deg,#47aed0,#83e0cf);font-size:28px;font-weight:900}.eyebrow{font-size:11px;letter-spacing:.24em;color:#78cddd;margin-top:26px}.story h1{font-size:38px;line-height:1.36;letter-spacing:-.03em;margin:13px 0 18px}.lead{line-height:1.8;color:#a9c1d5;max-width:570px}.feature-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px 32px;margin-top:50px;border-top:1px solid rgba(255,255,255,.1);padding-top:28px}.feature-grid b,.feature-grid span{display:block}.feature-grid b{font-size:14px}.feature-grid span{font-size:12px;color:#91aec4;margin-top:7px}.orb{position:absolute;border-radius:50%;filter:blur(2px);border:1px solid rgba(104,213,211,.18)}.orb.one{width:440px;height:440px;right:-220px;top:-100px}.orb.two{width:260px;height:260px;left:-100px;bottom:-100px}.form-side{display:grid;place-items:center;background:linear-gradient(145deg,#fff,#f6f9fc)}.login-card{width:430px}.welcome{font-size:13px;color:#1d709c;font-weight:700}.login-card h2{font-size:30px;margin:8px 0}.hint{color:#8491a3;margin-bottom:34px}.captcha-row{display:grid;grid-template-columns:1fr 140px;gap:10px}.captcha-row img{height:40px;width:140px;border-radius:7px;cursor:pointer;border:1px solid #d9e2eb}.submit{width:100%;margin-top:10px}.login-foot{display:flex;justify-content:space-between;color:#9aa6b5;font-size:11px;margin-top:28px}.login-foot a{color:#26739d;text-decoration:none}
@media(max-width:900px){.login{grid-template-columns:1fr}.story{display:none}.form-side{min-height:100vh;padding:32px 22px}.login-card{width:min(430px,100%)}}
@media(max-width:420px){.login-card h2{font-size:26px}.hint{margin-bottom:26px}.captcha-row{grid-template-columns:minmax(0,1fr) 120px}.captcha-row img{width:120px}}
</style>
