<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,reactive,ref} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessage} from 'element-plus'
import {dataOf,http} from '../api/http'

const router=useRouter(),loading=ref(false),sending=ref(false),captcha=ref(''),settings=ref<any>(null),countdown=ref(0)
const form=reactive({username:'',realName:'',email:'',phone:'',password:'',confirmPassword:'',verificationChannel:'EMAIL',verificationId:'',verificationCode:'',captchaKey:'',captchaCode:''})
let timer:number|undefined
const target=computed(()=>form.verificationChannel==='EMAIL'?form.email.trim():form.phone.trim())
const enabled=computed(()=>settings.value?.enabled===true)
function changeChannel(){form.verificationId='';form.verificationCode='';if(form.verificationChannel==='EMAIL')form.phone='';else form.email=''}
async function loadSettings(){settings.value=dataOf<any>(await http.get('/auth/registration-settings'));if(!settings.value.channels?.includes(form.verificationChannel))form.verificationChannel=settings.value.channels?.[0]||'EMAIL';if(enabled.value)await loadCaptcha()}
async function loadCaptcha(){const data=dataOf<any>(await http.get('/auth/captcha'));form.captchaKey=data.captchaKey;captcha.value=data.image;form.captchaCode=''}
function startCountdown(seconds:number){countdown.value=seconds;if(timer)window.clearInterval(timer);timer=window.setInterval(()=>{countdown.value--;if(countdown.value<=0&&timer){window.clearInterval(timer);timer=undefined}},1000)}
async function sendCode(){if(!target.value)return ElMessage.warning(`请先填写${form.verificationChannel==='EMAIL'?'邮箱':'手机号'}`);if(!form.captchaCode)return ElMessage.warning('请输入图形验证码');sending.value=true;try{const data=dataOf<any>(await http.post('/auth/registration-code',{channel:form.verificationChannel,target:target.value,captchaKey:form.captchaKey,captchaCode:form.captchaCode}));form.verificationId=data.verificationId;form.verificationCode='';startCountdown(data.resendAfterSeconds);ElMessage.success(`验证码已发送至 ${data.destinationMasked}`)}finally{sending.value=false;await loadCaptcha()}}
async function submit(){if(form.password!==form.confirmPassword)return ElMessage.warning('两次输入的密码不一致');if(!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,20}$/.test(form.password))return ElMessage.warning('密码需为8-20位并包含大小写字母和数字');if(!form.verificationId||!/^[0-9]{6}$/.test(form.verificationCode))return ElMessage.warning('请获取并填写6位邮箱/短信验证码');loading.value=true;try{await http.post('/auth/register',{...form});ElMessage.success('账号申请已提交，请等待管理员审核');router.replace('/login')}catch{await loadCaptcha()}finally{loading.value=false}}
onMounted(loadSettings);onBeforeUnmount(()=>{if(timer)window.clearInterval(timer)})
</script>

<template><div class="register-page"><div class="register-card surface" v-loading="settings===null"><div class="brand">J</div><p class="eyebrow">ACCOUNT APPLICATION</p><h1>申请平台账号</h1>
 <template v-if="settings&&!enabled"><el-result icon="warning" title="当前未开放自助注册" sub-title="自助注册是可配置能力，当前环境由管理员统一创建和分配账号。"><template #extra><el-button type="primary" @click="router.push('/login')">返回登录</el-button></template></el-result></template>
 <template v-else-if="enabled"><p class="hint">邮箱或手机验证码在 5 分钟内有效且只能使用一次；提交后账号处于待审核状态，管理员完成角色和数据域授权后方可登录。</p><el-alert v-if="settings.notificationMode==='SIMULATED'" title="当前为本机模拟通知验收模式，不代表生产邮件或短信供应商已开通。" type="info" :closable="false" show-icon/>
 <el-form label-position="top" style="margin-top:18px"><div class="two"><el-form-item label="用户名"><el-input v-model="form.username" placeholder="3-50位字母、数字或下划线"/></el-form-item><el-form-item label="真实姓名"><el-input v-model="form.realName"/></el-form-item></div><div class="two"><el-form-item label="验证码接收渠道"><el-radio-group v-model="form.verificationChannel" @change="changeChannel"><el-radio v-if="settings.channels.includes('EMAIL')" value="EMAIL">邮箱</el-radio><el-radio v-if="settings.channels.includes('PHONE')" value="PHONE">手机短信</el-radio></el-radio-group></el-form-item><el-form-item :label="form.verificationChannel==='EMAIL'?'已验证邮箱':'已验证手机号'"><el-input v-if="form.verificationChannel==='EMAIL'" v-model="form.email" type="email" placeholder="验证码通过后作为账号邮箱"/><el-input v-else v-model="form.phone" maxlength="11" placeholder="验证码通过后作为账号手机号"/></el-form-item></div><div class="two"><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password autocomplete="new-password"/></el-form-item><el-form-item label="确认密码"><el-input v-model="form.confirmPassword" type="password" show-password autocomplete="new-password"/></el-form-item></div>
 <el-form-item label="图形安全验证"><div class="captcha"><el-input v-model="form.captchaCode" placeholder="计算结果"/><img :src="captcha" alt="验证码" @click="loadCaptcha"/></div></el-form-item>
 <el-form-item :label="form.verificationChannel==='EMAIL'?'邮箱验证码':'短信验证码'"><div class="code-row"><el-input v-model="form.verificationCode" maxlength="6" placeholder="6位数字验证码"/><el-button :loading="sending" :disabled="countdown>0||!target||!form.captchaCode" @click="sendCode">{{countdown>0?`${countdown}s后重发`:'发送验证码'}}</el-button></div></el-form-item>
 <el-button type="primary" size="large" class="full" :loading="loading" :disabled="!form.username||!form.realName||!target||!form.password||!form.confirmPassword||!form.verificationId||!form.verificationCode||!form.captchaCode" @click="submit">提交账号申请</el-button><el-button class="full back" @click="router.push('/login')">返回登录</el-button></el-form></template></div></div></template>

<style scoped>.register-page{min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at top,#dceef5,#f3f6fa 55%);padding:30px}.register-card{width:min(760px,96vw);padding:36px}.brand{width:46px;height:46px;border-radius:13px;background:linear-gradient(135deg,#2d8ebc,#75d4c8);color:#fff;display:grid;place-items:center;font-size:24px;font-weight:800}.eyebrow{font-size:9px;letter-spacing:.2em;color:#2f7fa1;margin:18px 0 6px}.register-card h1{font-size:26px;margin:0}.hint{font-size:12px;line-height:1.65;color:#7d8b9d;margin:9px 0 18px}.two{display:grid;grid-template-columns:1fr 1fr;gap:15px}.captcha,.code-row{display:grid;grid-template-columns:1fr 150px;gap:10px;width:100%}.captcha img{width:150px;height:40px;border:1px solid #d9e2eb;border-radius:7px;cursor:pointer}.full{width:100%}.back{margin:10px 0 0}@media(max-width:620px){.register-card{padding:24px}.two{grid-template-columns:1fr}.captcha,.code-row{grid-template-columns:1fr 120px}.captcha img{width:120px}}</style>
