<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {http,dataOf} from '../api/http'
import {stepUpHeader,withStepUp} from '../api/stepUp'
import {useAuthStore} from '../stores/auth'

type Field=Record<string,any>&{__uiId:string;__optionsText:string;key:string;label:string;type:string;required:boolean;sensitive:boolean;maskType:string}
type Section=Record<string,any>&{__uiId:string;name:string;fields:Field[]}
type TemplateForm={id:number|null;name:string;type:string;tag:string;description:string;source:string;visibility:string;dataScopeId:number;sections:Section[];schemaDefinition:Record<string,any>}

const auth=useAuthStore(),route=useRoute()
const rows=ref<any[]>([]),total=ref(0),loading=ref(false),saving=ref(false)
const keyword=ref(''),typeFilter=ref(''),publishedFilter=ref(''),visibilityFilter=ref(''),enabledFilter=ref('')
const editorVisible=ref(false),detailVisible=ref(false),auditVisible=ref(false),versionVisible=ref(false)
const selected=ref<any|null>(null),versions=ref<any[]>([]),versionsLoading=ref(false)
const versionPreview=ref<any|null>(null)
const auditForm=reactive({auditStatus:1,auditComment:''})
const fieldTypes=[['text','文本'],['number','数值'],['date','日期'],['boolean','布尔'],['file','文件'],['object','对象'],['array','数组']]

const scopeIds=computed(()=>auth.user?.assignedScopes||[])
const isAdmin=computed(()=>auth.user?.roles.includes('ADMIN')||false)
const form=reactive<TemplateForm>(blankForm())

function uid(){return crypto.randomUUID()}
function blankField():Field{return{__uiId:uid(),__optionsText:'',key:'fieldKey',label:'字段名称',type:'text',required:false,sensitive:false,maskType:'GENERIC'}}
function blankSection():Section{return{__uiId:uid(),name:'基础信息',fields:[blankField()]}}
function blankForm():TemplateForm{return{id:null,name:'',type:'template',tag:'',description:'',source:'自主创建',visibility:'PRIVATE',dataScopeId:scopeIds.value?.[0]||0,sections:[blankSection()],schemaDefinition:{type:'object'}}}
function resetForm(){Object.assign(form,blankForm())}
function lifecycle(row:any){if(row.enabled===false)return'DISABLED';if(row.published)return'PUBLISHED';if(row.auditStatus!=null&&Number(row.auditStatus)===0)return'PENDING_REVIEW';if(row.auditStatus!=null&&Number(row.auditStatus)===2)return'REJECTED';if(row.visibility==='PRIVATE')return'PRIVATE_ACTIVE';return'DRAFT'}
function statusLabel(row:any){return({DISABLED:'已停用',PUBLISHED:'公共已发布',PENDING_REVIEW:'待审核',REJECTED:'已驳回',PRIVATE_ACTIVE:'私有可用',DRAFT:'公共草稿'} as any)[lifecycle(row)]}
function statusType(row:any){return lifecycle(row)==='PUBLISHED'?'success':lifecycle(row)==='PENDING_REVIEW'?'warning':lifecycle(row)==='REJECTED'||lifecycle(row)==='DISABLED'?'danger':'info'}
function owns(row:any){return isAdmin.value||Number(row.creatorId)===Number(auth.user?.id)}
function canEdit(row:any){return auth.can('template:update')&&owns(row)&&!row.published&&lifecycle(row)!=='PENDING_REVIEW'}
function canDelete(row:any){return auth.can('template:delete')&&owns(row)&&!row.published&&lifecycle(row)!=='PENDING_REVIEW'}
function canSubmit(row:any){return auth.can('template:publish')&&owns(row)&&row.visibility==='PUBLIC'&&!row.published&&lifecycle(row)!=='PENDING_REVIEW'}
function canAudit(row:any){return auth.can('template:audit')&&(isAdmin.value||auth.user?.assignedScopes?.includes(Number(row.dataScopeId)))&&lifecycle(row)==='PENDING_REVIEW'&&Number(row.creatorId)!==Number(auth.user?.id)}
function canRestore(row:any){return auth.can('template:update')&&owns(row)&&lifecycle(row)!=='PENDING_REVIEW'}
function canToggleEnabled(row:any){return auth.can('template:audit')&&(isAdmin.value||auth.user?.assignedScopes?.includes(Number(row.dataScopeId)))&&row.visibility==='PUBLIC'&&row.published}
function canViewVersions(row:any){return owns(row)||(auth.can('template:audit')&&(isAdmin.value||auth.user?.assignedScopes?.includes(Number(row.dataScopeId))))}

async function load(){loading.value=true;try{const params:any={keyword:keyword.value||undefined,type:typeFilter.value||undefined,visibility:visibilityFilter.value||undefined,pageSize:50};if(publishedFilter.value!=='')params.published=publishedFilter.value==='true';if(enabledFilter.value!=='')params.enabled=enabledFilter.value==='true';const page=dataOf<any>(await http.get('/templates',{params}));rows.value=page.list;total.value=page.total}finally{loading.value=false}}
async function detail(rowOrId:any){const id=typeof rowOrId==='object'?rowOrId.id:rowOrId;selected.value=dataOf(await http.get(`/templates/${id}`));detailVisible.value=true;versions.value=[];if(canViewVersions(selected.value)){versionsLoading.value=true;try{versions.value=dataOf(await http.get(`/templates/${id}/versions`))}finally{versionsLoading.value=false}}}

function hydrateField(raw:any):Field{return{...structuredClone(raw),__uiId:uid(),__optionsText:Array.isArray(raw?.options)?JSON.stringify(raw.options):'',key:String(raw?.key||''),label:String(raw?.label||''),type:String(raw?.type||'text'),required:Boolean(raw?.required),sensitive:Boolean(raw?.sensitive),maskType:String(raw?.maskType||'GENERIC')}}
function hydrateSection(raw:any,index:number):Section{return{...structuredClone(raw),__uiId:uid(),name:String(raw?.name||`章节 ${index+1}`),fields:Array.isArray(raw?.fields)?raw.fields.map(hydrateField):[]}}
function edit(row:any){const content=row.content||{};const sections=Array.isArray(content.sections)?content.sections.map(hydrateSection):[hydrateSection({name:'基础信息',fields:[]},0)];Object.assign(form,{id:row.id,name:row.name,type:row.type,tag:row.tag||'',description:row.description||'',source:row.source||'自主创建',visibility:row.visibility||'PRIVATE',dataScopeId:Number(row.dataScopeId),sections,schemaDefinition:structuredClone(row.schemaDefinition||{type:'object'})});editorVisible.value=true}
async function openEdit(row:any){const value=dataOf<any>(await http.get(`/templates/${row.id}`));edit(value)}
function create(){if(!scopeIds.value.length)return ElMessage.warning('当前账号没有直接数据域授权，选择性共享不能用于创建模板');resetForm();editorVisible.value=true}
function cloneAsDraft(row:any){edit(row);form.id=null;form.name=`${row.name}（新版本）`;form.source=`基于模板 #${row.id} v${row.version}`;editorVisible.value=true}
function addSection(){form.sections.push({__uiId:uid(),name:`章节 ${form.sections.length+1}`,fields:[blankField()]})}
function removeSection(index:number){if(form.sections.length===1)return ElMessage.warning('模板至少保留一个章节');form.sections.splice(index,1)}
function addField(section:Section){const index=form.sections.flatMap(s=>s.fields).length+1;section.fields.push({...blankField(),key:`field${index}`,label:`字段 ${index}`})}
function removeField(section:Section,index:number){section.fields.splice(index,1)}

function parseOptions(text:string,label:string){const source=text.trim();if(!source)return undefined;if(source.startsWith('[')){try{const value=JSON.parse(source);if(!Array.isArray(value))throw new Error();return value}catch{throw new Error(`${label}的可选值须为 JSON 数组，或使用逗号分隔文本`)}}return source.split(',').map(v=>v.trim()).filter(Boolean)}
function cleanField(field:Field){const value:any={...field};delete value.__uiId;delete value.__optionsText;value.key=value.key.trim();value.label=value.label.trim();const options=parseOptions(field.__optionsText,value.label||value.key);if(options)value.options=options;else delete value.options;for(const key of ['unit','pattern'])if(value[key]!=null&&!String(value[key]).trim())delete value[key];for(const key of ['min','max','minLength','maxLength'])if(value[key]==null||value[key]==='')delete value[key];return value}
function schemaProperty(field:any,existing:any){const value:any={...structuredClone(existing||{})};for(const key of ['type','format','description','minimum','maximum','minLength','maxLength','pattern','enum'])delete value[key];if(field.type==='date'){value.type='string';value.format=existing?.format==='date-time'?'date-time':'date'}else if(field.type==='file'){value.type='string';value.format='binary'}else value.type=field.type==='text'?'string':field.type;value.description=field.label;if(field.min!=null)value.minimum=Number(field.min);if(field.max!=null)value.maximum=Number(field.max);if(field.minLength!=null)value.minLength=Number(field.minLength);if(field.maxLength!=null)value.maxLength=Number(field.maxLength);if(field.pattern)value.pattern=field.pattern;if(Array.isArray(field.options))value.enum=structuredClone(field.options);return value}
function payload(){const sections=form.sections.map(section=>{const value:any={...section,name:section.name.trim(),fields:section.fields.map(cleanField)};delete value.__uiId;return value});const fields=sections.flatMap(s=>s.fields);if(!fields.length)throw new Error('模板至少需要一个字段');const keys=new Set<string>();for(const field of fields){if(!/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(field.key))throw new Error(`字段 key“${field.key}”格式不正确`);if(keys.has(field.key))throw new Error(`字段 key“${field.key}”重复`);keys.add(field.key);if(!field.label)throw new Error('字段名称不能为空');if(field.min!=null&&field.max!=null&&Number(field.min)>Number(field.max))throw new Error(`${field.label}的最小值不能大于最大值`);if(field.minLength!=null&&field.maxLength!=null&&Number(field.minLength)>Number(field.maxLength))throw new Error(`${field.label}的最小长度不能大于最大长度`);if(field.pattern)try{new RegExp(field.pattern)}catch{throw new Error(`${field.label}的正则表达式不正确`)}}
 const previous=form.schemaDefinition?.properties||{};const schema:any={...structuredClone(form.schemaDefinition||{}),type:'object',required:fields.filter(f=>f.required).map(f=>f.key),properties:{}};for(const field of fields)schema.properties[field.key]=schemaProperty(field,previous[field.key]);return{name:form.name.trim(),type:form.type,tag:form.tag.trim(),description:form.description.trim(),source:form.source.trim(),visibility:form.visibility,dataScopeId:form.dataScopeId,content:{sections},schemaDefinition:schema}}
async function save(){if(!form.name.trim())return ElMessage.warning('请输入模板名称');saving.value=true;try{const body=payload();if(form.id)await http.put(`/templates/${form.id}`,body);else await http.post('/templates',body);ElMessage.success(form.id?'模板已更新并保存版本快照':'模板已创建');editorVisible.value=false;await load();if(form.id&&detailVisible.value)await detail(form.id)}catch(error:any){if(!error?.response)ElMessage.error(error.message||'模板内容不正确')}finally{saving.value=false}}
async function toggleFavorite(row:any){if(row.favorited)await http.delete(`/templates/${row.id}/favorite`);else await http.put(`/templates/${row.id}/favorite`);row.favorited=!row.favorited;if(selected.value?.id===row.id)selected.value.favorited=row.favorited}
async function submit(row:any){await ElMessageBox.confirm(`提交“${row.name}”后，模板在审核完成前将被冻结。`,'提交发布审核',{type:'warning'});await http.post(`/templates/${row.id}/publish`);ElMessage.success('已提交独立审核');await load();await detail(row.id)}
function openAudit(row:any){selected.value=row;auditForm.auditStatus=1;auditForm.auditComment='';auditVisible.value=true}
async function audit(){if(auditForm.auditStatus===2&&!auditForm.auditComment.trim())return ElMessage.warning('驳回时必须填写审核意见');await http.post(`/templates/${selected.value.id}/audit`,auditForm);ElMessage.success(auditForm.auditStatus===1?'模板已审核发布':'模板已驳回');auditVisible.value=false;await load();await detail(selected.value.id)}
async function remove(row:any){await ElMessageBox.confirm(`确认删除草稿“${row.name}”？删除后无法恢复。`,'删除模板',{type:'warning'});const endpoint=`/templates/${row.id}`;await withStepUp({purpose:'DELETE',method:'DELETE',target:endpoint,label:`删除模板“${row.name}”`},token=>http.delete(endpoint,{headers:stepUpHeader(token)}));ElMessage.success('模板已删除');detailVisible.value=false;await load()}
async function showVersion(row:any){versionPreview.value=dataOf(await http.get(`/templates/${selected.value.id}/versions/${row.version}`));versionVisible.value=true}
async function restoreVersion(row:any){const sourceId=selected.value.id;await ElMessageBox.confirm(`将 v${row.version} 的完整内容复制为一个可追溯的新草稿。原模板的发布状态及已有数据集引用不会改变。`,'恢复历史版本',{type:'warning'});const result=dataOf<any>(await http.post(`/templates/${sourceId}/versions/${row.version}/restore`));ElMessage.success(`已生成新草稿 #${result.id}`);versionVisible.value=false;await load();await detail(result.id)}
async function toggleEnabled(row:any){const action=row.enabled?'停用':'重新启用';const {value}=await ElMessageBox.prompt(`请输入${action}“${row.name}”的原因`,`${action}模板`,{inputPattern:/\S+/,inputErrorMessage:'必须填写原因',type:'warning'});await http.put(`/templates/${row.id}/enabled`,{enabled:!row.enabled,reason:value});ElMessage.success(`模板已${action}`);await load();await detail(row.id)}

watch(()=>route.query.focus,async value=>{if(value)await detail(Number(value))})
onMounted(async()=>{await load();if(route.query.focus)await detail(Number(route.query.focus))})
</script>

<template><div class="page"><div class="page-head"><div><h1 class="page-title">模板中心</h1><div class="page-subtitle">可视化配置章节、字段和校验规则，独立审核后供数据集复用，共 {{total}} 个模板</div></div><el-button v-if="auth.can('template:create')" type="primary" @click="create">新建模板</el-button></div>
 <div class="surface toolbar"><el-input v-model="keyword" placeholder="搜索名称或标签" clearable style="width:240px" @keyup.enter="load"/><el-select v-model="typeFilter" placeholder="全部类型" clearable style="width:130px"><el-option label="完整模板" value="template"/><el-option label="模板片段" value="fragment"/></el-select><el-select v-model="visibilityFilter" placeholder="全部范围" clearable style="width:130px"><el-option label="本人私有" value="PRIVATE"/><el-option label="公共模板" value="PUBLIC"/></el-select><el-select v-model="publishedFilter" placeholder="全部发布状态" style="width:140px"><el-option label="全部发布状态" value=""/><el-option label="已发布" value="true"/><el-option label="未发布" value="false"/></el-select><el-select v-model="enabledFilter" placeholder="全部启停状态" style="width:140px"><el-option label="全部启停状态" value=""/><el-option label="启用" value="true"/><el-option label="停用" value="false"/></el-select><el-button @click="load">查询</el-button></div>
 <div class="template-grid" v-loading="loading"><article v-for="row in rows" :key="row.id" class="template-card surface" @click="detail(row)"><div class="card-top"><span class="kind">{{row.type==='template'?'完整模板':'模板片段'}}</span><button title="收藏" @click.stop="toggleFavorite(row)">{{row.favorited?'★':'☆'}}</button></div><h3>{{row.name}}</h3><p>{{row.description||'暂无模板说明'}}</p><div class="tags"><el-tag v-for="tag in (row.tag||'').split(',').filter(Boolean)" :key="tag" size="small" effect="plain">{{tag}}</el-tag></div><footer><span>v{{row.version}} · {{row.creatorName}}</span><el-tag :type="statusType(row)" size="small">{{statusLabel(row)}}</el-tag></footer></article><div v-if="!rows.length" class="empty-note">没有匹配的模板</div></div>

 <el-drawer v-model="detailVisible" :title="selected?.name" size="760"><template v-if="selected"><div class="detail-meta"><el-tag :type="statusType(selected)">{{statusLabel(selected)}}</el-tag><el-tag effect="plain">{{selected.visibility==='PRIVATE'?'仅本人可见':'公共范围'}}</el-tag><span>v{{selected.version}}</span><span>{{selected.type==='template'?'完整模板':'模板片段'}}</span><span>数据域 #{{selected.dataScopeId}}</span><span>{{selected.creatorName}}</span></div><el-alert v-if="selected.disabledReason" type="error" :title="`停用原因：${selected.disabledReason}`" :closable="false"/><el-alert v-else-if="selected.auditComment" :type="lifecycle(selected)==='REJECTED'?'error':'info'" :title="`审核意见：${selected.auditComment}`" :closable="false"/>
  <div class="detail-actions"><el-button v-if="canEdit(selected)" type="primary" @click="openEdit(selected)">编辑草稿</el-button><el-button v-if="canSubmit(selected)" type="success" @click="submit(selected)">提交发布审核</el-button><el-button v-if="canAudit(selected)" type="warning" @click="openAudit(selected)">独立审核</el-button><el-button v-if="canToggleEnabled(selected)" :type="selected.enabled?'danger':'success'" plain @click="toggleEnabled(selected)">{{selected.enabled?'停用模板':'重新启用'}}</el-button><el-button v-if="selected.published&&auth.can('template:create')" @click="cloneAsDraft(selected)">复制为新草稿</el-button><el-button @click="toggleFavorite(selected)">{{selected.favorited?'取消收藏':'收藏'}}</el-button><el-button v-if="canDelete(selected)" type="danger" plain @click="remove(selected)">删除</el-button></div>
  <section v-for="(section,index) in selected.content?.sections||[]" :key="index" class="detail-section"><h3>{{section.name||`章节 ${Number(index)+1}`}}</h3><div class="field-summary"><div v-for="field in section.fields||[]" :key="field.key"><b>{{field.label}}</b><span class="mono">{{field.key}}</span><small>{{field.type}}{{field.required?' · 必填':''}}{{field.unit?' · '+field.unit:''}}{{field.sensitive?' · '+(field.maskType||'GENERIC')+'脱敏':''}}</small></div></div></section>
  <template v-if="canViewVersions(selected)"><h3 class="history-title">版本历史</h3><el-table :data="versions" v-loading="versionsLoading"><el-table-column prop="version" label="版本" width="70"><template #default="{row}">v{{row.version}}</template></el-table-column><el-table-column prop="changeReason" label="变更"/><el-table-column prop="createdByName" label="操作人" width="110"/><el-table-column prop="createdTime" label="时间" width="170"/><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="showVersion(row)">查看/比较</el-button><el-button v-if="canRestore(selected)&&Number(row.version)!==Number(selected.version)" link type="warning" @click="restoreVersion(row)">恢复</el-button></template></el-table-column></el-table></template>
 </template></el-drawer>

 <el-dialog v-model="editorVisible" :title="form.id?'编辑模板草稿':'创建可视化模板'" width="min(1100px,94vw)" top="4vh"><el-form label-position="top"><div class="meta-grid"><el-form-item label="模板名称"><el-input v-model="form.name" maxlength="200"/></el-form-item><el-form-item label="类型"><el-select v-model="form.type"><el-option label="完整模板" value="template"/><el-option label="模板片段" value="fragment"/></el-select></el-form-item><el-form-item label="可见范围"><el-select v-model="form.visibility"><el-option label="私有模板（仅本人使用）" value="PRIVATE"/><el-option label="公共模板（审核后共享）" value="PUBLIC"/></el-select></el-form-item></div><div class="meta-grid"><el-form-item label="数据域"><el-select v-model="form.dataScopeId"><el-option v-for="scope in scopeIds" :key="scope" :label="`数据域 #${scope}`" :value="scope"/></el-select></el-form-item><el-form-item label="标签"><el-input v-model="form.tag" placeholder="以逗号分隔"/></el-form-item><el-form-item label="来源"><el-input v-model="form.source"/></el-form-item></div><el-form-item label="说明"><el-input v-model="form.description"/></el-form-item><el-alert :title="form.visibility==='PRIVATE'?'私有模板保存后可由本人直接创建数据集，无需审核。':'公共模板保存为草稿，提交并由独立审核员通过后才能供其他账号使用。'" :type="form.visibility==='PRIVATE'?'info':'warning'" :closable="false"/></el-form>
  <div class="builder-head"><div><h3>章节与字段</h3><p>字段约束会随已发布模板绑定到数据集，未知扩展属性也会原样保留。</p></div><el-button @click="addSection">＋ 添加章节</el-button></div>
  <section v-for="(section,sectionIndex) in form.sections" :key="section.__uiId" class="builder-section"><header><el-input v-model="section.name" placeholder="章节名称"/><div><el-button @click="addField(section)">添加字段</el-button><el-button type="danger" plain :disabled="form.sections.length===1" @click="removeSection(sectionIndex)">删除章节</el-button></div></header><div class="field-editor" v-for="(field,fieldIndex) in section.fields" :key="field.__uiId"><div class="field-main"><el-input v-model="field.label" placeholder="字段名称"/><el-input v-model="field.key" class="mono" placeholder="fieldKey"/><el-select v-model="field.type"><el-option v-for="type in fieldTypes" :key="type[0]" :label="type[1]" :value="type[0]"/></el-select><el-switch v-model="field.required" active-text="必填"/><el-button type="danger" link @click="removeField(section,fieldIndex)">删除</el-button></div><div class="constraints"><el-input v-model="field.unit" placeholder="单位"/><el-input-number v-if="field.type==='number'" v-model="field.min" placeholder="最小值"/><el-input-number v-if="field.type==='number'" v-model="field.max" placeholder="最大值"/><el-input-number v-if="field.type==='text'||field.type==='string'" v-model="field.minLength" :min="0" placeholder="最短"/><el-input-number v-if="field.type==='text'||field.type==='string'" v-model="field.maxLength" :min="0" placeholder="最长"/><el-input v-if="field.type==='text'||field.type==='string'" v-model="field.pattern" class="mono" placeholder="正则表达式（可选）"/><el-input v-model="field.__optionsText" placeholder="可选值：JSON数组或逗号分隔文本"/><el-switch v-model="field.sensitive" active-text="导出脱敏"/><el-select v-if="field.sensitive" v-model="field.maskType"><el-option label="通用掩码" value="GENERIC"/><el-option label="手机号" value="PHONE"/><el-option label="邮箱" value="EMAIL"/><el-option label="证件号" value="ID_CARD"/><el-option label="姓名" value="NAME"/></el-select></div></div><div v-if="!section.fields.length" class="empty-section">本章节尚无字段</div></section>
  <template #footer><el-button @click="editorVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存草稿</el-button></template></el-dialog>

 <el-dialog v-model="auditVisible" title="模板独立审核" width="520"><el-alert title="审核人不能是模板创建者；通过后模板立即发布并冻结内容。" type="warning" :closable="false"/><el-form label-position="top" style="margin-top:18px"><el-form-item label="审核结论"><el-radio-group v-model="auditForm.auditStatus"><el-radio-button :value="1">通过并发布</el-radio-button><el-radio-button :value="2">驳回</el-radio-button></el-radio-group></el-form-item><el-form-item label="审核意见"><el-input v-model="auditForm.auditComment" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="auditVisible=false">取消</el-button><el-button type="primary" @click="audit">确认审核</el-button></template></el-dialog>

 <el-dialog v-model="versionVisible" :title="versionPreview?`历史版本 v${versionPreview.version}`:'历史版本'" width="min(980px,94vw)" top="5vh"><template v-if="versionPreview"><div class="version-meta"><el-tag>{{versionPreview.visibility==='PRIVATE'?'私有':'公共'}}</el-tag><span>{{versionPreview.changeReason}}</span><span>{{versionPreview.createdByName}} · {{versionPreview.createdTime}}</span></div><div class="compare-grid"><section><h4>历史版本 v{{versionPreview.version}}</h4><pre>{{JSON.stringify({name:versionPreview.name,type:versionPreview.type,visibility:versionPreview.visibility,content:versionPreview.content,schemaDefinition:versionPreview.schemaDefinition},null,2)}}</pre></section><section><h4>当前版本 v{{selected?.version}}</h4><pre>{{JSON.stringify({name:selected?.name,type:selected?.type,visibility:selected?.visibility,content:selected?.content,schemaDefinition:selected?.schemaDefinition},null,2)}}</pre></section></div></template><template #footer><el-button @click="versionVisible=false">关闭</el-button><el-button v-if="versionPreview&&canRestore(selected)&&Number(versionPreview.version)!==Number(selected?.version)" type="warning" @click="restoreVersion(versionPreview)">恢复为新草稿</el-button></template></el-dialog>
</div></template>

<style scoped>
.template-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.template-card{padding:20px;min-height:220px;display:flex;flex-direction:column;cursor:pointer;transition:.16s}.template-card:hover{transform:translateY(-2px);border-color:#8db6cf}.card-top{display:flex;justify-content:space-between}.kind{font-size:10px;color:#1e709b;background:#eaf5fa;padding:5px 8px;border-radius:5px}.card-top button{border:0;background:none;color:#e4a11b;font-size:19px;cursor:pointer}.template-card h3{font-size:16px;margin:18px 0 8px}.template-card p{color:#78879a;font-size:12px;line-height:1.6;margin:0;flex:1}.tags{display:flex;gap:5px;margin:12px 0;min-height:24px}.template-card footer{display:flex;justify-content:space-between;align-items:center;border-top:1px solid #edf1f5;padding-top:12px;color:#8b98a8;font-size:10px}.detail-meta,.version-meta{display:flex;gap:9px;align-items:center;color:#75859a;font-size:12px;margin-bottom:16px;flex-wrap:wrap}.detail-actions{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.detail-section{border:1px solid #e8edf3;border-radius:11px;padding:16px;margin:12px 0}.detail-section h3,.history-title{font-size:14px;margin:0 0 13px}.field-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.field-summary div{background:#f7f9fc;border-radius:8px;padding:10px}.field-summary b,.field-summary span,.field-summary small{display:block}.field-summary b{font-size:11px}.field-summary span,.field-summary small{font-size:9px;color:#8391a3;margin-top:4px}.history-title{margin-top:25px}.meta-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:14px}.builder-head{display:flex;justify-content:space-between;align-items:center;border-top:1px solid #e7edf3;padding-top:16px}.builder-head h3{margin:0;font-size:15px}.builder-head p{margin:5px 0 0;color:#8794a5;font-size:11px}.builder-section{border:1px solid #dfe7ef;border-radius:12px;padding:14px;margin-top:13px;background:#fbfcfe}.builder-section>header{display:flex;justify-content:space-between;gap:15px;align-items:center}.builder-section>header>.el-input{max-width:360px}.field-editor{background:#fff;border:1px solid #e8edf3;border-radius:10px;padding:12px;margin-top:11px}.field-main{display:grid;grid-template-columns:1.2fr 1fr 130px 85px 50px;gap:9px;align-items:center}.constraints{display:grid;grid-template-columns:repeat(4,minmax(110px,1fr));gap:9px;margin-top:9px}.empty-section{text-align:center;color:#8b98a8;padding:20px}.el-select{width:100%}.compare-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.compare-grid section{min-width:0}.compare-grid h4{font-size:13px}.compare-grid pre{height:430px;overflow:auto;background:#0e2439;color:#d9e7f5;padding:14px;border-radius:10px;font-size:10px;line-height:1.55;white-space:pre-wrap;word-break:break-all}
@media(max-width:1000px){.template-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.field-main{grid-template-columns:1fr 1fr}.constraints{grid-template-columns:1fr 1fr}.field-summary{grid-template-columns:1fr 1fr}}
@media(max-width:650px){.template-grid{grid-template-columns:1fr}.meta-grid,.field-main,.constraints,.field-summary,.compare-grid{grid-template-columns:1fr}.builder-section>header{align-items:flex-start;flex-direction:column}.compare-grid pre{height:280px}}
</style>
